# Stroke Prediction

## Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV
import optuna
from optuna.samplers import TPESampler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, fbeta_score, make_scorer

## Import dataset

In [2]:
df = pd.read_csv('../dataset/healthcare-dataset-stroke-data.csv')

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [5]:
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [6]:
df.describe(include=[object])

        gender ever_married work_type Residence_type smoking_status
count     5110         5110      5110           5110           5110
unique       3            2         5              2              4
top     Female          Yes   Private          Urban   never smoked
freq      2994         3353      2925           2596           1892

## Rename column for consistent formatting of name

In [7]:
df.rename(columns={'Residence_type': 'residence_type'}, inplace=True)

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
pd.set_option('display.max_rows', None)

### Impute missing values in BMI column
For 201 entries missing BMI values, these entries will be imputed with the median BMI value

In [10]:
median_bmi = df['bmi'].median()
df['bmi'].fillna(median_bmi, inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18656\2337012406.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bmi'].fillna(median_bmi, inplace=True)

In [11]:
print(df['bmi'].isna().sum())

0

## Feature Engineering

### Converting categorical columns to numerical columns

In [12]:
df['male'] = (df['gender'] == 'Male').astype(int)

In [13]:
df['ever_married'] = (df['ever_married'] == 'Yes').astype(int)

In [14]:
df['urban'] = (df['residence_type'] == 'Urban').astype(int)

In [15]:
df['smoke'] = ((df['smoking_status'] == 'formerly smoked') | (df['smoking_status'] == 'smokes')).astype(int)

In [16]:
df['have_work'] = ((df['work_type'] == 'Govt_job') | (df['work_type'] == 'Private') | (df['work_type'] == 'Self-employed')).astype(int)

In [17]:
df['hypertension_or_heart_disease'] = df['hypertension'] | df['heart_disease']

In [18]:
df = pd.get_dummies(df, columns=['work_type', 'smoking_status'], drop_first = False)

### Extra column for the age of married people

In [19]:
df['age_ever_married'] = df['age'] * df['ever_married']

In [20]:
df['age_hypertension'] = df['age'] * df['hypertension']

In [21]:
df['age_heart_disease'] = df['age'] * df['heart_disease']

In [22]:
df['age_bmi'] = df['age'] * df['bmi']

In [23]:
df['age_avg_glucose_level'] = df['age'] * df['avg_glucose_level']

In [24]:
df['bmi_avg_glucose_level'] = df['bmi'] * df['avg_glucose_level']

In [25]:
df['avg_glucose_level_hypertension'] = df['avg_glucose_level'] * df['hypertension']

### Creating columns representing outstanding values for BMI and Average Glucose Level

In [26]:
df['obese'] = df['bmi'] >= 30

In [27]:
df['high_avg_glucose_level'] = df['avg_glucose_level'] >= 150

In [28]:
df['obese_high_avg_glucose_level'] = df['obese'] | df['high_avg_glucose_level']

### Creating column representing high age

In [29]:
df['old'] = df['age'] >= 65

### Converting boolean columns to numerical

In [30]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

### Accounting for multiple risks

In [31]:
df['risk_count'] = df['obese'] + df['high_avg_glucose_level'] + df['old'] + df['hypertension'] + df['heart_disease']

### Reformatting column names

In [32]:
df.rename(columns={'work_type_Govt_job': 'work_type_govt_job', 'work_type_Never_worked': 'work_type_never_worked', 'work_type_Private': 'work_type_private', 'work_type_Self-employed': 'work_type_self_employed'}, inplace=True)

In [33]:
df.rename(columns={'smoking_status_Unknown': 'smoking_status_unknown', 'smoking_status_formerly smoked': 'smoking_status_formerly_smoked', 'smoking_status_never smoked': 'smoking_status_never_smoked'}, inplace=True)

In [34]:
df.drop(columns=['gender', 'residence_type'], inplace=True)

### Log Transforming BMI and Average Glucose Level columns

In [35]:
df['log_bmi'] = np.log(df['bmi'])

In [36]:
df['log_avg_glucose_level'] = np.log(df['avg_glucose_level'])

In [37]:
df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,male,urban,smoke,have_work,hypertension_or_heart_disease,work_type_govt_job,work_type_never_worked,work_type_private,work_type_self_employed,work_type_children,smoking_status_unknown,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,age_ever_married,age_hypertension,age_heart_disease,age_bmi,age_avg_glucose_level,bmi_avg_glucose_level,avg_glucose_level_hypertension,obese,high_avg_glucose_level,obese_high_avg_glucose_level,old,risk_count,log_bmi,log_avg_glucose_level
0,9046,67.0,0,1,1,228.69,36.6,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,67.0,0.0,67.0,2452.2,15322.23,8370.054,0.00,1,1,1,1,4,3.600048,5.432367
1,51676,61.0,0,0,1,202.21,28.1,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,61.0,0.0,0.0,1714.1,12334.81,5682.101,0.00,0,1,1,0,1,3.335770,5.309307
2,31112,80.0,0,1,1,105.92,32.5,1,1,0,0,1,1,0,0,1,0,0,0,0,1,0,80.0,0.0,80.0,2600.0,8473.60,3442.400,0.00,1,0,1,1,3,3.481240,4.662684
3,60182,49.0,0,0,1,171.23,34.4,1,0,1,1,1,0,0,0,1,0,0,0,0,0,1,49.0,0.0,0.0,1685.6,8390.27,5890.312,0.00,1,1,1,0,2,3.538057,5.143008
4,1665,79.0,1,0,1,174.12,24.0,1,0,0,0,1,1,0,0,0,1,0,0,0,1,0,79.0,79.0,0.0,1896.0,13755.48,4178.880,174.12,0,1,1,1,3,3.178054,5.159745

In [38]:
df.shape

(5110, 36)

## Model Building

### Splitting to training, validation, and testing sets

In [39]:
columns_name = columns_name = [col for col in df.columns if col != 'id']

In [40]:
X = df[columns_name]
X.drop('stroke', axis=1, inplace=True)
y = df['stroke']

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18656\91966498.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('stroke', axis=1, inplace=True)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify = y)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size = 0.5, random_state = 42, stratify = y_test)

### Create base random forest classifier model

In [42]:
base_classifier = lgb.LGBMClassifier(random_state=42, verbose=-1)

### Create grid for hyperparameter tuning

In [43]:
param_grid_lgbm = {
    'num_leaves': [15, 31, 63, 127],
    'max_depth': [3, 5, 7, 10, -1], 
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [50, 100, 200, 300],
    'min_child_samples': [5, 10, 20, 30],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'reg_alpha': [0, 0.1, 0.5, 1], 
    'reg_lambda': [0, 0.1, 0.5, 1],  
    'scale_pos_weight': [1, 3, 5, 10, 15, 20]  
}

In [44]:
f2_scorer = make_scorer(fbeta_score, beta=2)

In [45]:
grid_lgbm = GridSearchCV(
    estimator=base_classifier,
    param_grid=param_grid_lgbm,
    scoring=f2_scorer,
    cv=5,
    verbose=2,
    n_jobs=-1
)

### Fitting base classifier on unsampled data

In [46]:
base_classifier.fit(X_train, y_train)

LGBMClassifier(random_state=42, verbose=-1)

In [47]:
importances = base_classifier.feature_importances_

In [48]:
feature_imp_df = pd.DataFrame({'Feature':[col for col in X_train], 'Importance': importances}).sort_values(
    'Importance', ascending=False)

In [49]:
print(feature_imp_df)

                           Feature  Importance
4                avg_glucose_level         463
23                         age_bmi         418
25           bmi_avg_glucose_level         417
5                              bmi         402
24           age_avg_glucose_level         347
0                              age         188
26  avg_glucose_level_hypertension         149
20                age_ever_married         133
21                age_hypertension          77
22               age_heart_disease          56
13               work_type_private          45
7                            urban          43
6                             male          38
18     smoking_status_never_smoked          36
31                      risk_count          36
11              work_type_govt_job          25
19           smoking_status_smokes          24
8                            smoke          22
17  smoking_status_formerly_smoked          20
10   hypertension_or_heart_disease          17
14         work_type_self_employed          16
3                     ever_married          12
16          smoking_status_unknown           9
1                     hypertension           2
2                    heart_disease           2
28          high_avg_glucose_level           1
29    obese_high_avg_glucose_level           1
30                             old           1
15              work_type_children           0
12          work_type_never_worked           0
9                        have_work           0
27                           obese           0
32                         log_bmi           0
33           log_avg_glucose_level           0

In [50]:
# retained_columns = ['avg_glucose_level', 'age_bmi', 'bmi_avg_glucose_level', 'bmi', 'age_avg_glucose_level', 'age', 'avg_glucose_level_hypertension', 'age_ever_married', 'age_hypertension', 'work_type_private']

In [51]:
# retained_columns = ['avg_glucose_level', 'age_bmi', 'bmi_avg_glucose_level', 'bmi', 'age_avg_glucose_level', 'age', 'avg_glucose_level_hypertension', 'age_ever_married']

In [52]:
# retained_columns = ['avg_glucose_level', 'age_bmi', 'bmi_avg_glucose_level', 'bmi', 'age_avg_glucose_level', 'age', 'avg_glucose_level_hypertension', 'age_ever_married', 'age_hypertension']

In [53]:
# retained_columns = ['avg_glucose_level', 'age_bmi', 'bmi_avg_glucose_level', 'bmi', 'age_avg_glucose_level', 'age', 'avg_glucose_level_hypertension', 'age_ever_married', 'age_hypertension', 'age_heart_disease']

In [54]:
# retained_columns = ['avg_glucose_level', 'bmi', 'age', 'age_ever_married', 'age_hypertension', 'age_heart_disease', 'urban', 'male', 'risk_count', 'work_type_self_employed']

In [55]:
# retained_columns = ['avg_glucose_level', 'age', 'bmi', 'age_ever_married', 'urban', 'hypertension', 'male', 'work_type_self_employed', 'smoke']

In [56]:
retained_columns = ['avg_glucose_level', 'age', 'bmi', 'age_ever_married', 'urban', 'hypertension', 'male', 'work_type_self_employed', 'smoke', 'smoking_status_never_smoked']

In [57]:
# retained_columns = ['avg_glucose_level', 'age', 'bmi', 'urban', 'hypertension', 'male', 'work_type_self_employed', 'smoke', 'smoking_status_never_smoked', 'work_type_private']

In [58]:
# retained_columns = ['avg_glucose_level', 'age', 'bmi', 'urban', 'hypertension', 'male', 'work_type_self_employed', 'smoke', 'smoking_status_never_smoked']

In [59]:
# retained_columns = ['avg_glucose_level', 'age', 'bmi', 'urban', 'hypertension', 'male', 'work_type_self_employed', 'smoke', 'smoking_status_never_smoked', 'work_type_private', 'smoking_status_formerly_smoked']

In [60]:
X_train_retained = X_train[retained_columns]

In [61]:
X_val_retained = X_val[retained_columns]

### Create optimizing function for hyperparameter tuning with Optuna

In [62]:
MIN_PRECISION = 0.15

In [63]:
def objective_lgbm(trial):
    params = {
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'min_child_samples': trial.suggest_int('min_child_samples', 10, 80),
        'min_child_weight': trial.suggest_float('min_child_weight', 0.001, 5, log=True), 
        'min_split_gain': trial.suggest_float('min_split_gain', 0, 3), 
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.2, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'subsample_freq': trial.suggest_int('subsample_freq', 1, 7),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.001, 10, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.001, 10, log=True),
        'max_delta_step': trial.suggest_float('max_delta_step', 0, 5),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 5, 25),
        'boosting_type': 'gbdt',  
        'max_bin': trial.suggest_int('max_bin', 200, 400),
        'random_state': 42,
        'verbose': -1,
    }
    
    model = lgb.LGBMClassifier(**params)
    
    model.fit(X_train_retained, y_train)
    
    y_pred_val = model.predict(X_val_retained)
    
    recall = recall_score(y_val, y_pred_val)
    precision = precision_score(y_val, y_pred_val)
    f2_score = fbeta_score(y_val, y_pred_val, beta=2)
    
    # if precision < MIN_PRECISION:
    #     return 0
    # return recall + (precision * 0.01)
    return f2_score + recall * 0.001 + precision * 0.00001

In [64]:
# grid_lgbm.fit(X_train_retained, y_train)

In [65]:
study_lgbm = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
study_lgbm.optimize(objective_lgbm, n_trials=500, show_progress_bar=True)

[I 2026-01-30 15:23:19,676] A new study created in memory with name: no-name-8db0f080-4bdc-4713-ad39-551946fcba6f

  0%|          | 0/500 [00:00<?, ?it/s]

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:23:19,999] Trial 0 finished with value: 0.0 and parameters: {'num_leaves': 69, 'max_depth': 15, 'min_child_samples': 61, 'min_child_weight': 0.16383993835282307, 'min_split_gain': 0.46805592132730955, 'learning_rate': 0.008889607461211927, 'n_estimators': 123, 'subsample': 0.9330880728874675, 'subsample_freq': 5, 'colsample_bytree': 0.8540362888980227, 'reg_alpha': 0.0012087541473056963, 'reg_lambda': 7.579479953348009, 'max_delta_step': 4.162213204002109, 'scale_pos_weight': 9.246782213565524, 'max_bin': 236}. Best is trial 0 with value: 0.0.
[I 2026-01-30 15:23:20,140] Trial 1 finished with value: 0.40441559641372143 and parameters: {'num_leaves': 44, 'max_depth': 6, 'min_child_samples': 47, 'min_child_weight': 0.039605150456850806, 'min_split_gain': 0.8736874205941257, 'learning_rate': 0.04777437867054351, 'n_estimators': 155, 'subsample': 0.6460723242676091, 'subsample_freq': 3, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 1.382623217936987, 'reg_lambda': 0.006290644294586149, 'max_delta_step': 2.571172192068058, 'scale_pos_weight': 16.848291377240848, 'max_bin': 209}. Best is trial 1 with value: 0.40441559641372143.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:23:20,283] Trial 2 finished with value: 0.0 and parameters: {'num_leaves': 99, 'max_depth': 5, 'min_child_samples': 14, 'min_child_weight': 3.235185145617431, 'min_split_gain': 2.896896099223678, 'learning_rate': 0.09864408593146953, 'n_estimators': 222, 'subsample': 0.5488360570031919, 'subsample_freq': 5, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'max_delta_step': 0.17194260557609198, 'scale_pos_weight': 23.186408041575643, 'max_bin': 252}. Best is trial 1 with value: 0.40441559641372143.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:23:20,506] Trial 3 finished with value: 0.35585802332461103 and parameters: {'num_leaves': 106, 'max_depth': 7, 'min_child_samples': 46, 'min_child_weight': 0.105260377776104, 'min_split_gain': 0.5545633665765811, 'learning_rate': 0.17877333612826407, 'n_estimators': 410, 'subsample': 0.9697494707820946, 'subsample_freq': 7, 'colsample_bytree': 0.7989499894055425, 'reg_alpha': 4.869640941520899, 'reg_lambda': 0.002259279742015696, 'max_delta_step': 0.979914312095726, 'scale_pos_weight': 5.904545778210761, 'max_bin': 265}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:20,662] Trial 4 finished with value: 0.0 and parameters: {'num_leaves': 70, 'max_depth': 6, 'min_child_samples': 68, 'min_child_weight': 0.020874681332882276, 'min_split_gain': 0.8428035290621423, 'learning_rate': 0.037017039861413845, 'n_estimators': 156, 'subsample': 0.9010984903770198, 'subsample_freq': 1, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 1.2273800987852967, 'reg_lambda': 0.0062353771356731605, 'max_delta_step': 0.027610585618011996, 'scale_pos_weight': 21.309228569096682, 'max_bin': 342}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:21,565] Trial 5 finished with value: 0.2187977369031795 and parameters: {'num_leaves': 115, 'max_depth': 13, 'min_child_samples': 15, 'min_child_weight': 0.021181366627251397, 'min_split_gain': 0.34760717857538914, 'learning_rate': 0.1207017234656905, 'n_estimators': 349, 'subsample': 0.6654490124263246, 'subsample_freq': 1, 'colsample_bytree': 0.6554911608578311, 'reg_alpha': 0.01998634077852888, 'reg_lambda': 0.8287522363768158, 'max_delta_step': 3.1877873567760657, 'scale_pos_weight': 22.74425485152653, 'max_bin': 294}. Best is trial 1 with value: 0.40441559641372143.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:23:21,991] Trial 6 finished with value: 0.3502554876162713 and parameters: {'num_leaves': 35, 'max_depth': 12, 'min_child_samples': 64, 'min_child_weight': 0.1191646709003216, 'min_split_gain': 2.3129015398636827, 'learning_rate': 0.030907236344562737, 'n_estimators': 309, 'subsample': 0.7137705091792748, 'subsample_freq': 1, 'colsample_bytree': 0.5539457134966522, 'reg_alpha': 0.0013357240411974098, 'reg_lambda': 0.35127047262708466, 'max_delta_step': 1.5717799053816335, 'scale_pos_weight': 15.171413823294056, 'max_bin': 382}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:22,092] Trial 7 finished with value: 0.0 and parameters: {'num_leaves': 52, 'max_depth': 8, 'min_child_samples': 63, 'min_child_weight': 0.007019683821378796, 'min_split_gain': 0.23093972948637898, 'learning_rate': 0.014560262826662182, 'n_estimators': 164, 'subsample': 0.9648488261712865, 'subsample_freq': 6, 'colsample_bytree': 0.8167018782552118, 'reg_alpha': 3.06085221067225, 'reg_lambda': 1.6394127471631603, 'max_delta_step': 0.9328502944301792, 'scale_pos_weight': 22.851179969799556, 'max_bin': 308}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:22,771] Trial 8 finished with value: 0.378239445029445 and parameters: {'num_leaves': 125, 'max_depth': 14, 'min_child_samples': 32, 'min_child_weight': 0.0025531643266569876, 'min_split_gain': 0.683805487625825, 'learning_rate': 0.024166975649069788, 'n_estimators': 428, 'subsample': 0.9303652916281717, 'subsample_freq': 1, 'colsample_bytree': 0.7553736512887829, 'reg_alpha': 0.0467351899956275, 'reg_lambda': 0.007734482156646798, 'max_delta_step': 0.599326836668414, 'scale_pos_weight': 11.752303428072558, 'max_bin': 389}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:23,011] Trial 9 finished with value: 0.2275177705159705 and parameters: {'num_leaves': 62, 'max_depth': 9, 'min_child_samples': 59, 'min_child_weight': 0.02213374957157973, 'min_split_gain': 2.915346248162882, 'learning_rate': 0.17412787871290497, 'n_estimators': 200, 'subsample': 0.7486242529461927, 'subsample_freq': 3, 'colsample_bytree': 0.6424202471887338, 'reg_alpha': 0.0014045842344024703, 'reg_lambda': 0.27431991397796696, 'max_delta_step': 2.5133951161443076, 'scale_pos_weight': 6.029575024999787, 'max_bin': 256}. Best is trial 1 with value: 0.40441559641372143.
[I 2026-01-30 15:23:23,360] Trial 10 finished with value: 0.42415710665247025 and parameters: {'num_leaves': 23, 'max_depth': 3, 'min_child_samples': 78, 'min_child_weight': 0.9390853811201847, 'min_split_gain': 1.4146392221205886, 'learning_rate': 0.06166466981746084, 'n_estimators': 244, 'subsample': 0.508664269599903, 'subsample_freq': 3, 'colsample_bytree': 0.5061555847824688, 'reg_alpha': 0.3151553491660762, 'reg_lambda': 0.04000654820971493, 'max_delta_step': 4.578189853894369, 'scale_pos_weight': 17.475437482189747, 'max_bin': 206}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:23,507] Trial 11 finished with value: 0.41871072866289444 and parameters: {'num_leaves': 21, 'max_depth': 3, 'min_child_samples': 80, 'min_child_weight': 1.1022239736772568, 'min_split_gain': 1.4236564219497265, 'learning_rate': 0.05560581896151741, 'n_estimators': 241, 'subsample': 0.5104645462798357, 'subsample_freq': 3, 'colsample_bytree': 0.5126722826512198, 'reg_alpha': 0.4726102737804255, 'reg_lambda': 0.030809434529183194, 'max_delta_step': 4.980082658737176, 'scale_pos_weight': 16.786752206761623, 'max_bin': 200}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:23,762] Trial 12 finished with value: 0.41737095473522307 and parameters: {'num_leaves': 20, 'max_depth': 3, 'min_child_samples': 77, 'min_child_weight': 1.399958993992596, 'min_split_gain': 1.530836779960659, 'learning_rate': 0.06851264233881708, 'n_estimators': 248, 'subsample': 0.5062524650464644, 'subsample_freq': 3, 'colsample_bytree': 0.5015614555704639, 'reg_alpha': 0.2903853436845006, 'reg_lambda': 0.04275514395356317, 'max_delta_step': 4.9138207980371895, 'scale_pos_weight': 18.783116459697247, 'max_bin': 209}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:24,016] Trial 13 finished with value: 0.41429245560059225 and parameters: {'num_leaves': 21, 'max_depth': 3, 'min_child_samples': 78, 'min_child_weight': 0.6743357440739147, 'min_split_gain': 1.5825495551811233, 'learning_rate': 0.06316216182248381, 'n_estimators': 271, 'subsample': 0.5707921208261757, 'subsample_freq': 4, 'colsample_bytree': 0.5737903766356575, 'reg_alpha': 0.20811240585176446, 'reg_lambda': 0.03968773339674345, 'max_delta_step': 4.898232498406144, 'scale_pos_weight': 12.997818000996622, 'max_bin': 202}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:24,505] Trial 14 finished with value: 0.420230807359503 and parameters: {'num_leaves': 146, 'max_depth': 11, 'min_child_samples': 74, 'min_child_weight': 0.5374697296050428, 'min_split_gain': 1.9039189362181312, 'learning_rate': 0.017118741192687338, 'n_estimators': 346, 'subsample': 0.8448372126058836, 'subsample_freq': 2, 'colsample_bytree': 0.5410524522319672, 'reg_alpha': 0.3598594807146819, 'reg_lambda': 0.025036066140130566, 'max_delta_step': 3.8346382837950888, 'scale_pos_weight': 18.35584899168185, 'max_bin': 233}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:25,492] Trial 15 finished with value: 0.375074056418802 and parameters: {'num_leaves': 144, 'max_depth': 11, 'min_child_samples': 34, 'min_child_weight': 0.3338100078725908, 'min_split_gain': 2.039345126976599, 'learning_rate': 0.006030426234282958, 'n_estimators': 493, 'subsample': 0.8408126019394581, 'subsample_freq': 2, 'colsample_bytree': 0.6091330191487017, 'reg_alpha': 0.08135423005992244, 'reg_lambda': 0.001261600113501015, 'max_delta_step': 3.7489861827171054, 'scale_pos_weight': 19.608102173069174, 'max_bin': 234}. Best is trial 10 with value: 0.42415710665247025.
[I 2026-01-30 15:23:25,985] Trial 16 finished with value: 0.4249777350827562 and parameters: {'num_leaves': 145, 'max_depth': 10, 'min_child_samples': 71, 'min_child_weight': 2.9310830054855828, 'min_split_gain': 2.042473668819774, 'learning_rate': 0.01626692331591632, 'n_estimators': 336, 'subsample': 0.8286207831937886, 'subsample_freq': 2, 'colsample_bytree': 0.9345096954319009, 'reg_alpha': 0.013345312075839909, 'reg_lambda': 0.01686323349512741, 'max_delta_step': 4.019507906380753, 'scale_pos_weight': 19.023039562806225, 'max_bin': 290}. Best is trial 16 with value: 0.4249777350827562.
[I 2026-01-30 15:23:26,490] Trial 17 finished with value: 0.42875960356760867 and parameters: {'num_leaves': 86, 'max_depth': 10, 'min_child_samples': 56, 'min_child_weight': 3.099782983402353, 'min_split_gain': 1.119075707378696, 'learning_rate': 0.011506486585494953, 'n_estimators': 306, 'subsample': 0.8233896586051719, 'subsample_freq': 4, 'colsample_bytree': 0.9412544406948945, 'reg_alpha': 0.006308613819682147, 'reg_lambda': 0.15840279111857727, 'max_delta_step': 4.252539310695681, 'scale_pos_weight': 24.655368883346505, 'max_bin': 334}. Best is trial 17 with value: 0.42875960356760867.
[I 2026-01-30 15:23:26,928] Trial 18 finished with value: 0.4413824375118806 and parameters: {'num_leaves': 86, 'max_depth': 10, 'min_child_samples': 53, 'min_child_weight': 4.703684538538102, 'min_split_gain': 2.444481721517656, 'learning_rate': 0.011004992153686598, 'n_estimators': 320, 'subsample': 0.8187110948675035, 'subsample_freq': 4, 'colsample_bytree': 0.9530201084764285, 'reg_alpha': 0.009098878177168203, 'reg_lambda': 0.14986764791815932, 'max_delta_step': 3.0816253702775906, 'scale_pos_weight': 24.9138169905423, 'max_bin': 342}. Best is trial 18 with value: 0.4413824375118806.
[I 2026-01-30 15:23:28,291] Trial 19 finished with value: 0.4520934487344488 and parameters: {'num_leaves': 87, 'max_depth': 9, 'min_child_samples': 54, 'min_child_weight': 2.4789172945079994, 'min_split_gain': 2.5490779353507302, 'learning_rate': 0.0050191169775294035, 'n_estimators': 395, 'subsample': 0.7594450500709057, 'subsample_freq': 5, 'colsample_bytree': 0.9047408557669123, 'reg_alpha': 0.00600730647527837, 'reg_lambda': 0.1743713668677248, 'max_delta_step': 3.213190480367871, 'scale_pos_weight': 24.344626156081016, 'max_bin': 352}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:29,155] Trial 20 finished with value: 0.41871072866289444 and parameters: {'num_leaves': 84, 'max_depth': 8, 'min_child_samples': 52, 'min_child_weight': 4.826969898307456, 'min_split_gain': 2.515394008357882, 'learning_rate': 0.005074564073274166, 'n_estimators': 407, 'subsample': 0.782440660346196, 'subsample_freq': 5, 'colsample_bytree': 0.8876113545471246, 'reg_alpha': 0.01880540283792066, 'reg_lambda': 1.8613727850139619, 'max_delta_step': 3.189501080339545, 'scale_pos_weight': 24.679516668760677, 'max_bin': 358}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:30,991] Trial 21 finished with value: 0.41884745820841507 and parameters: {'num_leaves': 89, 'max_depth': 10, 'min_child_samples': 37, 'min_child_weight': 1.974540960039218, 'min_split_gain': 2.447944777350345, 'learning_rate': 0.009046240465173867, 'n_estimators': 384, 'subsample': 0.7955327903550753, 'subsample_freq': 4, 'colsample_bytree': 0.9948174708426615, 'reg_alpha': 0.00601604678279219, 'reg_lambda': 0.12753345627675663, 'max_delta_step': 3.1395535244198953, 'scale_pos_weight': 21.09332724690936, 'max_bin': 327}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:31,739] Trial 22 finished with value: 0.4074299423186591 and parameters: {'num_leaves': 87, 'max_depth': 9, 'min_child_samples': 52, 'min_child_weight': 4.818997646876031, 'min_split_gain': 1.1505998296515159, 'learning_rate': 0.008355478135921466, 'n_estimators': 455, 'subsample': 0.7184578343730447, 'subsample_freq': 4, 'colsample_bytree': 0.9303589245947009, 'reg_alpha': 0.0052992197258858115, 'reg_lambda': 0.13922979836283259, 'max_delta_step': 1.941087149088464, 'scale_pos_weight': 24.738361422508337, 'max_bin': 358}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:32,820] Trial 23 finished with value: 0.4088135577903876 and parameters: {'num_leaves': 80, 'max_depth': 11, 'min_child_samples': 55, 'min_child_weight': 0.25904548896165536, 'min_split_gain': 2.6622797777575915, 'learning_rate': 0.011838192919915402, 'n_estimators': 296, 'subsample': 0.8809439111613812, 'subsample_freq': 6, 'colsample_bytree': 0.9299317327786486, 'reg_alpha': 0.007974726235090242, 'reg_lambda': 0.26212639467732946, 'max_delta_step': 3.3796741908223975, 'scale_pos_weight': 24.819390957289237, 'max_bin': 320}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:34,123] Trial 24 finished with value: 0.4434550279124413 and parameters: {'num_leaves': 99, 'max_depth': 9, 'min_child_samples': 40, 'min_child_weight': 2.0439872241204378, 'min_split_gain': 1.188710285377892, 'learning_rate': 0.006468166855998403, 'n_estimators': 370, 'subsample': 0.7822870870146837, 'subsample_freq': 4, 'colsample_bytree': 0.8850644169114827, 'reg_alpha': 0.03766022677328547, 'reg_lambda': 0.511316022026542, 'max_delta_step': 2.899969636394859, 'scale_pos_weight': 21.782821602304068, 'max_bin': 365}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:34,977] Trial 25 finished with value: 0.42861217714555305 and parameters: {'num_leaves': 100, 'max_depth': 8, 'min_child_samples': 26, 'min_child_weight': 1.8661466437585619, 'min_split_gain': 0.008003883831843916, 'learning_rate': 0.006074188912172886, 'n_estimators': 374, 'subsample': 0.6676074336272206, 'subsample_freq': 6, 'colsample_bytree': 0.8767735907977774, 'reg_alpha': 0.032439749337572134, 'reg_lambda': 0.6706007154860508, 'max_delta_step': 2.0998370945397147, 'scale_pos_weight': 21.332968123072174, 'max_bin': 370}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:36,551] Trial 26 finished with value: 0.45194115156630893 and parameters: {'num_leaves': 124, 'max_depth': 12, 'min_child_samples': 40, 'min_child_weight': 0.41144456107640026, 'min_split_gain': 1.7649589322107428, 'learning_rate': 0.007332328240226669, 'n_estimators': 454, 'subsample': 0.7784240554013345, 'subsample_freq': 5, 'colsample_bytree': 0.8351639921447858, 'reg_alpha': 0.06784386009871313, 'reg_lambda': 2.950519195531474, 'max_delta_step': 2.7339241291640777, 'scale_pos_weight': 20.616720751109163, 'max_bin': 399}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:37,289] Trial 27 finished with value: 0.4078433717812213 and parameters: {'num_leaves': 125, 'max_depth': 12, 'min_child_samples': 40, 'min_child_weight': 0.25211146879121143, 'min_split_gain': 1.7463604440371228, 'learning_rate': 0.007340547865302449, 'n_estimators': 468, 'subsample': 0.7711342068549677, 'subsample_freq': 5, 'colsample_bytree': 0.818674728445197, 'reg_alpha': 0.11584933931285274, 'reg_lambda': 8.208603750907526, 'max_delta_step': 2.769001046998689, 'scale_pos_weight': 20.513763816205106, 'max_bin': 400}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:37,947] Trial 28 finished with value: 0.4323051710614876 and parameters: {'num_leaves': 131, 'max_depth': 13, 'min_child_samples': 26, 'min_child_weight': 0.49918579765466925, 'min_split_gain': 1.1891908756322138, 'learning_rate': 0.00551652379018756, 'n_estimators': 440, 'subsample': 0.7281938103108292, 'subsample_freq': 7, 'colsample_bytree': 0.8548050543844647, 'reg_alpha': 0.04573664992513374, 'reg_lambda': 4.390899177532383, 'max_delta_step': 2.1592197787684055, 'scale_pos_weight': 22.687399270937483, 'max_bin': 370}. Best is trial 19 with value: 0.4520934487344488.
[I 2026-01-30 15:23:38,679] Trial 29 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 114, 'max_depth': 15, 'min_child_samples': 43, 'min_child_weight': 1.032382648235219, 'min_split_gain': 2.1869535633373394, 'learning_rate': 0.007591151272928861, 'n_estimators': 489, 'subsample': 0.6171755094079238, 'subsample_freq': 6, 'colsample_bytree': 0.8928117447351475, 'reg_alpha': 0.0026257461880874987, 'reg_lambda': 3.934511768445037, 'max_delta_step': 3.5520565409892866, 'scale_pos_weight': 14.06039938922621, 'max_bin': 391}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:39,502] Trial 30 finished with value: 0.38184446414442175 and parameters: {'num_leaves': 114, 'max_depth': 15, 'min_child_samples': 43, 'min_child_weight': 0.05659180566403682, 'min_split_gain': 2.193826146143379, 'learning_rate': 0.00880114978458489, 'n_estimators': 497, 'subsample': 0.6087152963416326, 'subsample_freq': 6, 'colsample_bytree': 0.7778620659372966, 'reg_alpha': 0.0019782964485238475, 'reg_lambda': 3.8704568085183695, 'max_delta_step': 3.605263031860443, 'scale_pos_weight': 9.920979562026098, 'max_bin': 395}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:40,532] Trial 31 finished with value: 0.39967528849017087 and parameters: {'num_leaves': 108, 'max_depth': 15, 'min_child_samples': 29, 'min_child_weight': 0.9106924162645869, 'min_split_gain': 1.8629702224043936, 'learning_rate': 0.006998210376984382, 'n_estimators': 472, 'subsample': 0.6927910541103562, 'subsample_freq': 5, 'colsample_bytree': 0.8974428736654197, 'reg_alpha': 0.0035751351559601243, 'reg_lambda': 1.940045631649656, 'max_delta_step': 2.8563559708139095, 'scale_pos_weight': 13.726374198377123, 'max_bin': 380}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:41,106] Trial 32 finished with value: 0.3544167845994394 and parameters: {'num_leaves': 130, 'max_depth': 14, 'min_child_samples': 48, 'min_child_weight': 1.4989759714894508, 'min_split_gain': 2.664860418679792, 'learning_rate': 0.020436528356397907, 'n_estimators': 385, 'subsample': 0.6289134396202046, 'subsample_freq': 6, 'colsample_bytree': 0.8505412608537563, 'reg_alpha': 0.12178246840336979, 'reg_lambda': 0.6061975118497231, 'max_delta_step': 3.4596628138323258, 'scale_pos_weight': 11.06073600736994, 'max_bin': 357}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:41,892] Trial 33 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 96, 'max_depth': 12, 'min_child_samples': 41, 'min_child_weight': 0.34713295511183706, 'min_split_gain': 1.68773280472043, 'learning_rate': 0.006676714220147992, 'n_estimators': 414, 'subsample': 0.7661785306637535, 'subsample_freq': 5, 'colsample_bytree': 0.8456315989512769, 'reg_alpha': 0.003143288508479995, 'reg_lambda': 3.840259892013035, 'max_delta_step': 2.303813145742983, 'scale_pos_weight': 14.88245291595342, 'max_bin': 372}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:42,506] Trial 34 finished with value: 0.4261823545870418 and parameters: {'num_leaves': 74, 'max_depth': 7, 'min_child_samples': 48, 'min_child_weight': 0.1637550395468252, 'min_split_gain': 2.1953573044200834, 'learning_rate': 0.00956423558092713, 'n_estimators': 448, 'subsample': 0.7455228087119673, 'subsample_freq': 7, 'colsample_bytree': 0.9088688736018392, 'reg_alpha': 0.026366037322152022, 'reg_lambda': 0.9966868680085417, 'max_delta_step': 1.5822476876171652, 'scale_pos_weight': 16.449508096222807, 'max_bin': 386}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:42,941] Trial 35 finished with value: 0.32290812738035146 and parameters: {'num_leaves': 119, 'max_depth': 14, 'min_child_samples': 37, 'min_child_weight': 2.318936391198442, 'min_split_gain': 2.729153814590809, 'learning_rate': 0.0051845123606534356, 'n_estimators': 374, 'subsample': 0.6918431884343331, 'subsample_freq': 5, 'colsample_bytree': 0.9721820951725305, 'reg_alpha': 0.07124431846712491, 'reg_lambda': 9.063946421234403, 'max_delta_step': 2.828644323550848, 'scale_pos_weight': 7.591744759996906, 'max_bin': 399}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:43,823] Trial 36 finished with value: 0.41587526427111793 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 20, 'min_child_weight': 0.7001396665146091, 'min_split_gain': 1.2955273691425484, 'learning_rate': 0.0074843528404336754, 'n_estimators': 477, 'subsample': 0.8814502976517986, 'subsample_freq': 6, 'colsample_bytree': 0.7947123626386727, 'reg_alpha': 0.014937702729279629, 'reg_lambda': 2.6314303004078536, 'max_delta_step': 4.275875016810955, 'scale_pos_weight': 23.5773758840346, 'max_bin': 355}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:44,063] Trial 37 finished with value: 0.34444424551025465 and parameters: {'num_leaves': 93, 'max_depth': 5, 'min_child_samples': 44, 'min_child_weight': 1.2510263560384518, 'min_split_gain': 2.0030979579356236, 'learning_rate': 0.013089229861211697, 'n_estimators': 110, 'subsample': 0.8008650302924516, 'subsample_freq': 5, 'colsample_bytree': 0.7380372871570824, 'reg_alpha': 0.8117619213427394, 'reg_lambda': 0.07098170369055347, 'max_delta_step': 2.601444989848463, 'scale_pos_weight': 21.60992264387778, 'max_bin': 374}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:23:44,658] Trial 38 finished with value: 0.4246786949776632 and parameters: {'num_leaves': 111, 'max_depth': 13, 'min_child_samples': 48, 'min_child_weight': 0.45810478959915024, 'min_split_gain': 0.9450000277176083, 'learning_rate': 0.010436959161910671, 'n_estimators': 405, 'subsample': 0.5793679294243185, 'subsample_freq': 4, 'colsample_bytree': 0.696826711943847, 'reg_alpha': 0.0023115056602077888, 'reg_lambda': 0.40423435281904646, 'max_delta_step': 1.736378817226796, 'scale_pos_weight': 20.079024865990228, 'max_bin': 341}. Best is trial 29 with value: 0.45348088860994523.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:24:09,382] Trial 68 finished with value: 0.0 and parameters: {'num_leaves': 33, 'max_depth': 13, 'min_child_samples': 46, 'min_child_weight': 0.95993884995467, 'min_split_gain': 1.0292163906669307, 'learning_rate': 0.005106867291324091, 'n_estimators': 469, 'subsample': 0.7432997771154822, 'subsample_freq': 6, 'colsample_bytree': 0.7614198863981232, 'reg_alpha': 0.0010549550641785527, 'reg_lambda': 2.101904541484383, 'max_delta_step': 0.4221809870905857, 'scale_pos_weight': 15.783174887478635, 'max_bin': 361}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:10,467] Trial 69 finished with value: 0.4220524801945675 and parameters: {'num_leaves': 70, 'max_depth': 14, 'min_child_samples': 42, 'min_child_weight': 0.8380692917044585, 'min_split_gain': 1.8045265817184646, 'learning_rate': 0.009567252317350517, 'n_estimators': 482, 'subsample': 0.7659795121230344, 'subsample_freq': 4, 'colsample_bytree': 0.789804294754562, 'reg_alpha': 0.005070145751125926, 'reg_lambda': 1.526181118547087, 'max_delta_step': 4.048546264993495, 'scale_pos_weight': 17.159192247933582, 'max_bin': 227}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:11,267] Trial 70 finished with value: 0.3989488567901054 and parameters: {'num_leaves': 78, 'max_depth': 15, 'min_child_samples': 28, 'min_child_weight': 0.47095773704037663, 'min_split_gain': 1.862527391124496, 'learning_rate': 0.007298919076525164, 'n_estimators': 429, 'subsample': 0.6171160591806111, 'subsample_freq': 5, 'colsample_bytree': 0.6895886392964652, 'reg_alpha': 2.3506118278942862, 'reg_lambda': 4.80371787914427, 'max_delta_step': 3.6668111240508177, 'scale_pos_weight': 11.323936507244223, 'max_bin': 369}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:12,801] Trial 71 finished with value: 0.3805153762586116 and parameters: {'num_leaves': 85, 'max_depth': 11, 'min_child_samples': 38, 'min_child_weight': 2.0048253962053826, 'min_split_gain': 1.6870708135760943, 'learning_rate': 0.006169718623401552, 'n_estimators': 412, 'subsample': 0.7977922701949977, 'subsample_freq': 4, 'colsample_bytree': 0.8882750957715335, 'reg_alpha': 0.002791156355748978, 'reg_lambda': 0.9656635960676203, 'max_delta_step': 3.8996529098815387, 'scale_pos_weight': 16.46828796161212, 'max_bin': 355}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:13,597] Trial 72 finished with value: 0.43884374246911595 and parameters: {'num_leaves': 110, 'max_depth': 13, 'min_child_samples': 35, 'min_child_weight': 1.2762490056592788, 'min_split_gain': 2.144660243090647, 'learning_rate': 0.007900479754626277, 'n_estimators': 451, 'subsample': 0.591974068834445, 'subsample_freq': 3, 'colsample_bytree': 0.9208768599402378, 'reg_alpha': 0.009691069916787937, 'reg_lambda': 2.407302865647103, 'max_delta_step': 3.3671247389083687, 'scale_pos_weight': 13.333121263223662, 'max_bin': 334}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:14,188] Trial 73 finished with value: 0.423673481957232 and parameters: {'num_leaves': 88, 'max_depth': 8, 'min_child_samples': 54, 'min_child_weight': 1.7035328485536425, 'min_split_gain': 1.961245961747774, 'learning_rate': 0.008569672796090918, 'n_estimators': 313, 'subsample': 0.5465813882727608, 'subsample_freq': 4, 'colsample_bytree': 0.7620336545802536, 'reg_alpha': 0.0017700353810703709, 'reg_lambda': 0.2064335307954187, 'max_delta_step': 3.4681169314550027, 'scale_pos_weight': 12.538210924692397, 'max_bin': 396}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:15,571] Trial 74 finished with value: 0.43171191899767664 and parameters: {'num_leaves': 150, 'max_depth': 12, 'min_child_samples': 45, 'min_child_weight': 3.505570458496932, 'min_split_gain': 2.270341943559157, 'learning_rate': 0.010682058658371355, 'n_estimators': 468, 'subsample': 0.8323884519889977, 'subsample_freq': 4, 'colsample_bytree': 0.853294128180688, 'reg_alpha': 0.0877771467993593, 'reg_lambda': 6.4144055204059764, 'max_delta_step': 2.688646201177819, 'scale_pos_weight': 23.108425358600247, 'max_bin': 379}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:16,449] Trial 75 finished with value: 0.44123668383977505 and parameters: {'num_leaves': 129, 'max_depth': 9, 'min_child_samples': 40, 'min_child_weight': 0.005527290326545996, 'min_split_gain': 1.3862451579315453, 'learning_rate': 0.00695083034783836, 'n_estimators': 399, 'subsample': 0.8492090946541323, 'subsample_freq': 5, 'colsample_bytree': 0.8131429979765727, 'reg_alpha': 0.055467548260395474, 'reg_lambda': 2.942717431637754, 'max_delta_step': 3.179256192829602, 'scale_pos_weight': 15.374286632508353, 'max_bin': 389}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:16,981] Trial 76 finished with value: 0.40469066342730775 and parameters: {'num_leaves': 100, 'max_depth': 10, 'min_child_samples': 32, 'min_child_weight': 2.678870808408603, 'min_split_gain': 1.5271866384174024, 'learning_rate': 0.005623402090558462, 'n_estimators': 443, 'subsample': 0.684429920651426, 'subsample_freq': 4, 'colsample_bytree': 0.9018638335770325, 'reg_alpha': 0.011231661327599004, 'reg_lambda': 4.492536882269217, 'max_delta_step': 1.8998644100249418, 'scale_pos_weight': 24.381890205565146, 'max_bin': 344}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:17,675] Trial 77 finished with value: 0.24749863755481402 and parameters: {'num_leaves': 93, 'max_depth': 14, 'min_child_samples': 49, 'min_child_weight': 0.5475911918421827, 'min_split_gain': 2.585346507825684, 'learning_rate': 0.006534212319665825, 'n_estimators': 341, 'subsample': 0.8048852480355242, 'subsample_freq': 5, 'colsample_bytree': 0.9348592612562364, 'reg_alpha': 0.005458671630697155, 'reg_lambda': 0.12102824198568526, 'max_delta_step': 2.882164556650486, 'scale_pos_weight': 5.330989573504551, 'max_bin': 375}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:18,066] Trial 78 finished with value: 0.3928070303810885 and parameters: {'num_leaves': 116, 'max_depth': 4, 'min_child_samples': 47, 'min_child_weight': 0.30377869581164485, 'min_split_gain': 2.0382552619945735, 'learning_rate': 0.012449844270392281, 'n_estimators': 364, 'subsample': 0.9040696698772441, 'subsample_freq': 6, 'colsample_bytree': 0.7402852516898517, 'reg_alpha': 0.003644649881922585, 'reg_lambda': 0.37106903278265874, 'max_delta_step': 2.2355797804673907, 'scale_pos_weight': 14.697644405775481, 'max_bin': 359}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:19,172] Trial 79 finished with value: 0.41233423606674297 and parameters: {'num_leaves': 70, 'max_depth': 12, 'min_child_samples': 53, 'min_child_weight': 0.07921652251324952, 'min_split_gain': 2.3449317612713263, 'learning_rate': 0.009012896321594886, 'n_estimators': 428, 'subsample': 0.7882837016494568, 'subsample_freq': 3, 'colsample_bytree': 0.949998915527234, 'reg_alpha': 0.015414760865791874, 'reg_lambda': 0.622781397689749, 'max_delta_step': 3.7278228102377855, 'scale_pos_weight': 13.694324056429414, 'max_bin': 266}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:20,623] Trial 80 finished with value: 0.39914703798227574 and parameters: {'num_leaves': 105, 'max_depth': 13, 'min_child_samples': 57, 'min_child_weight': 0.7471357429430756, 'min_split_gain': 1.7031169877168082, 'learning_rate': 0.015212079608592827, 'n_estimators': 409, 'subsample': 0.6554105056764031, 'subsample_freq': 5, 'colsample_bytree': 0.8606683435060096, 'reg_alpha': 0.025033488258971903, 'reg_lambda': 1.2890671902467383, 'max_delta_step': 2.4073928893476038, 'scale_pos_weight': 21.721272514691343, 'max_bin': 369}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:21,549] Trial 81 finished with value: 0.4253070012870013 and parameters: {'num_leaves': 131, 'max_depth': 9, 'min_child_samples': 40, 'min_child_weight': 0.004196534555750074, 'min_split_gain': 1.3130085822520694, 'learning_rate': 0.007056306673855169, 'n_estimators': 398, 'subsample': 0.8512207325894988, 'subsample_freq': 5, 'colsample_bytree': 0.8141510254273291, 'reg_alpha': 0.05773271059586324, 'reg_lambda': 2.9390723387632534, 'max_delta_step': 3.1787847946832346, 'scale_pos_weight': 15.113503174354078, 'max_bin': 385}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:22,389] Trial 82 finished with value: 0.433667536208025 and parameters: {'num_leaves': 123, 'max_depth': 9, 'min_child_samples': 41, 'min_child_weight': 0.008440995607459277, 'min_split_gain': 1.3925099380577413, 'learning_rate': 0.007447710974739639, 'n_estimators': 386, 'subsample': 0.7665164060168534, 'subsample_freq': 5, 'colsample_bytree': 0.8258654599538565, 'reg_alpha': 0.11068451311926236, 'reg_lambda': 0.0025197301010392186, 'max_delta_step': 3.135037447366958, 'scale_pos_weight': 15.948849104866213, 'max_bin': 391}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:22,994] Trial 83 finished with value: 0.42922189540189537 and parameters: {'num_leaves': 82, 'max_depth': 8, 'min_child_samples': 44, 'min_child_weight': 0.05167056332138138, 'min_split_gain': 1.1284726938543956, 'learning_rate': 0.006297806197171744, 'n_estimators': 419, 'subsample': 0.8678342169315952, 'subsample_freq': 5, 'colsample_bytree': 0.8432085974979258, 'reg_alpha': 0.04505690501251466, 'reg_lambda': 3.5275121686715445, 'max_delta_step': 3.5564150617459958, 'scale_pos_weight': 18.52754025061064, 'max_bin': 395}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:23,637] Trial 84 finished with value: 0.4222563937634402 and parameters: {'num_leaves': 129, 'max_depth': 9, 'min_child_samples': 38, 'min_child_weight': 0.0017108561948312, 'min_split_gain': 1.5930925036594932, 'learning_rate': 0.005379940694049792, 'n_estimators': 461, 'subsample': 0.7378542373099376, 'subsample_freq': 4, 'colsample_bytree': 0.8826734212571212, 'reg_alpha': 0.030723580387294905, 'reg_lambda': 0.8386866934989649, 'max_delta_step': 2.855979907401312, 'scale_pos_weight': 15.298117698782189, 'max_bin': 305}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:24,549] Trial 85 finished with value: 0.39634891206423817 and parameters: {'num_leaves': 140, 'max_depth': 10, 'min_child_samples': 36, 'min_child_weight': 0.1218786649114234, 'min_split_gain': 1.8685985332240254, 'learning_rate': 0.005013079794294778, 'n_estimators': 376, 'subsample': 0.8927228536026119, 'subsample_freq': 5, 'colsample_bytree': 0.7797302183652288, 'reg_alpha': 0.26744132199576776, 'reg_lambda': 1.9563096678388403, 'max_delta_step': 4.128656942424867, 'scale_pos_weight': 14.053019920051948, 'max_bin': 385}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:25,486] Trial 86 finished with value: 0.38510396412512693 and parameters: {'num_leaves': 134, 'max_depth': 15, 'min_child_samples': 32, 'min_child_weight': 4.387830516500938, 'min_split_gain': 1.461030619964697, 'learning_rate': 0.009740790383547795, 'n_estimators': 493, 'subsample': 0.8209310083375735, 'subsample_freq': 4, 'colsample_bytree': 0.9192055712392901, 'reg_alpha': 0.008161759663753161, 'reg_lambda': 0.1500559090794395, 'max_delta_step': 3.473856224477348, 'scale_pos_weight': 16.321098951135223, 'max_bin': 376}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:25,935] Trial 87 finished with value: 0.42729856022316304 and parameters: {'num_leaves': 122, 'max_depth': 11, 'min_child_samples': 41, 'min_child_weight': 1.1391679259087433, 'min_split_gain': 0.8232135653385237, 'learning_rate': 0.007862674161596967, 'n_estimators': 403, 'subsample': 0.7104259545504928, 'subsample_freq': 6, 'colsample_bytree': 0.9639675668893856, 'reg_alpha': 0.13782645270896332, 'reg_lambda': 6.766501208379574, 'max_delta_step': 2.980469381717321, 'scale_pos_weight': 21.129366033143448, 'max_bin': 352}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:26,414] Trial 88 finished with value: 0.4218688828670428 and parameters: {'num_leaves': 127, 'max_depth': 9, 'min_child_samples': 51, 'min_child_weight': 2.186180760300036, 'min_split_gain': 2.506879747642087, 'learning_rate': 0.010792016667113866, 'n_estimators': 434, 'subsample': 0.7527485105858721, 'subsample_freq': 5, 'colsample_bytree': 0.8372784712804437, 'reg_alpha': 0.05915068422885745, 'reg_lambda': 0.2508872105538606, 'max_delta_step': 3.2122548681615504, 'scale_pos_weight': 19.406093282779313, 'max_bin': 366}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:26,968] Trial 89 finished with value: 0.4463601466392397 and parameters: {'num_leaves': 97, 'max_depth': 8, 'min_child_samples': 47, 'min_child_weight': 0.003930668837292249, 'min_split_gain': 1.2369417163227931, 'learning_rate': 0.006774466612312267, 'n_estimators': 291, 'subsample': 0.6397141141189353, 'subsample_freq': 6, 'colsample_bytree': 0.8746692038478944, 'reg_alpha': 0.035590557448382854, 'reg_lambda': 1.591774496354718, 'max_delta_step': 2.7263387407993975, 'scale_pos_weight': 17.529666797973253, 'max_bin': 380}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:27,345] Trial 90 finished with value: 0.4344540991307819 and parameters: {'num_leaves': 97, 'max_depth': 8, 'min_child_samples': 58, 'min_child_weight': 0.40507771866457554, 'min_split_gain': 1.2177113014611964, 'learning_rate': 0.006105479497154193, 'n_estimators': 298, 'subsample': 0.6056826236844434, 'subsample_freq': 6, 'colsample_bytree': 0.8774434315866231, 'reg_alpha': 0.016528871423286726, 'reg_lambda': 1.1970531768220012, 'max_delta_step': 2.473114775604967, 'scale_pos_weight': 17.473059564544403, 'max_bin': 381}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:27,898] Trial 91 finished with value: 0.43028413163163165 and parameters: {'num_leaves': 87, 'max_depth': 7, 'min_child_samples': 46, 'min_child_weight': 0.002515975205821822, 'min_split_gain': 1.0311796034632348, 'learning_rate': 0.007039641485929039, 'n_estimators': 312, 'subsample': 0.6400728589301093, 'subsample_freq': 7, 'colsample_bytree': 0.9838279296371419, 'reg_alpha': 0.08153368654851866, 'reg_lambda': 3.008160791527408, 'max_delta_step': 2.0438487420935374, 'scale_pos_weight': 15.268178196533352, 'max_bin': 389}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:28,206] Trial 92 finished with value: 0.4189527801837425 and parameters: {'num_leaves': 92, 'max_depth': 8, 'min_child_samples': 44, 'min_child_weight': 0.004861125864824235, 'min_split_gain': 2.401528667679037, 'learning_rate': 0.005776567602662129, 'n_estimators': 265, 'subsample': 0.5678593238043783, 'subsample_freq': 6, 'colsample_bytree': 0.8669879555553291, 'reg_alpha': 0.04086683482593791, 'reg_lambda': 1.5180088700745864, 'max_delta_step': 2.7436151916600373, 'scale_pos_weight': 22.36976381008752, 'max_bin': 373}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:28,583] Trial 93 finished with value: 0.4276967165051226 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.003979129881209492, 'min_split_gain': 1.3810853959247453, 'learning_rate': 0.008591046639218418, 'n_estimators': 253, 'subsample': 0.773889612120999, 'subsample_freq': 6, 'colsample_bytree': 0.901624399493446, 'reg_alpha': 0.021532798879645574, 'reg_lambda': 0.49343764376795646, 'max_delta_step': 2.609222659736032, 'scale_pos_weight': 23.586174918847753, 'max_bin': 396}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:29,143] Trial 94 finished with value: 0.44775131103726923 and parameters: {'num_leaves': 99, 'max_depth': 9, 'min_child_samples': 42, 'min_child_weight': 0.01116768276687596, 'min_split_gain': 1.7536900872192602, 'learning_rate': 0.006775385119024225, 'n_estimators': 291, 'subsample': 0.7915020752007341, 'subsample_freq': 4, 'colsample_bytree': 0.8161230333780825, 'reg_alpha': 0.03425852133614218, 'reg_lambda': 4.077029609819209, 'max_delta_step': 3.0437061442291675, 'scale_pos_weight': 14.388988057790945, 'max_bin': 366}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:29,479] Trial 95 finished with value: 0.3544167845994394 and parameters: {'num_leaves': 100, 'max_depth': 8, 'min_child_samples': 47, 'min_child_weight': 0.02349361557982122, 'min_split_gain': 2.0147422000617303, 'learning_rate': 0.006570986628679252, 'n_estimators': 232, 'subsample': 0.7891537498772421, 'subsample_freq': 4, 'colsample_bytree': 0.9423692230342919, 'reg_alpha': 0.03604103938718033, 'reg_lambda': 5.542711488304503, 'max_delta_step': 3.0548443201925557, 'scale_pos_weight': 14.34103347859036, 'max_bin': 357}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:29,965] Trial 96 finished with value: 0.4069837493535939 and parameters: {'num_leaves': 94, 'max_depth': 10, 'min_child_samples': 42, 'min_child_weight': 0.011256620946254181, 'min_split_gain': 1.7626806171165537, 'learning_rate': 0.008039430747419413, 'n_estimators': 276, 'subsample': 0.7605285474984802, 'subsample_freq': 4, 'colsample_bytree': 0.8551062106620415, 'reg_alpha': 0.013200933674398741, 'reg_lambda': 4.292798387292392, 'max_delta_step': 2.2582351447494466, 'scale_pos_weight': 20.64521025566558, 'max_bin': 364}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:30,384] Trial 97 finished with value: 0.3802353444014346 and parameters: {'num_leaves': 104, 'max_depth': 11, 'min_child_samples': 49, 'min_child_weight': 0.00215673720720464, 'min_split_gain': 2.221564154064648, 'learning_rate': 0.005491265518875259, 'n_estimators': 296, 'subsample': 0.7280353758390645, 'subsample_freq': 4, 'colsample_bytree': 0.8250000913555333, 'reg_alpha': 0.003939213309572796, 'reg_lambda': 1.7800980208868058, 'max_delta_step': 2.851693134664878, 'scale_pos_weight': 18.029911056274056, 'max_bin': 326}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:30,861] Trial 98 finished with value: 0.4281328161283653 and parameters: {'num_leaves': 90, 'max_depth': 14, 'min_child_samples': 51, 'min_child_weight': 1.374103866926441, 'min_split_gain': 2.1070811187332246, 'learning_rate': 0.007719877758440152, 'n_estimators': 287, 'subsample': 0.8069546429220456, 'subsample_freq': 3, 'colsample_bytree': 0.7937323874502058, 'reg_alpha': 0.006285030585809462, 'reg_lambda': 0.8188460074708599, 'max_delta_step': 3.31167823589647, 'scale_pos_weight': 19.904547352648606, 'max_bin': 378}. Best is trial 29 with value: 0.45348088860994523.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:24:31,167] Trial 99 finished with value: 0.0 and parameters: {'num_leaves': 73, 'max_depth': 12, 'min_child_samples': 44, 'min_child_weight': 0.7881865402392277, 'min_split_gain': 1.8895661470472949, 'learning_rate': 0.006182745229206836, 'n_estimators': 136, 'subsample': 0.6349912025345298, 'subsample_freq': 4, 'colsample_bytree': 0.894502118392064, 'reg_alpha': 0.004653092345326549, 'reg_lambda': 2.190167941194135, 'max_delta_step': 3.785464167434971, 'scale_pos_weight': 13.740491520395198, 'max_bin': 337}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:31,521] Trial 100 finished with value: 0.4302306885322349 and parameters: {'num_leaves': 98, 'max_depth': 15, 'min_child_samples': 60, 'min_child_weight': 0.19727005297128583, 'min_split_gain': 2.7396067883518698, 'learning_rate': 0.00913488559925284, 'n_estimators': 285, 'subsample': 0.7436421528768374, 'subsample_freq': 4, 'colsample_bytree': 0.9092408157817238, 'reg_alpha': 0.003004717115867787, 'reg_lambda': 8.201322141425718, 'max_delta_step': 2.6407126826036165, 'scale_pos_weight': 16.089897463375287, 'max_bin': 347}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:32,028] Trial 101 finished with value: 0.44123668383977505 and parameters: {'num_leaves': 80, 'max_depth': 9, 'min_child_samples': 42, 'min_child_weight': 0.0030383687293692447, 'min_split_gain': 1.5576249533878257, 'learning_rate': 0.006880436584452414, 'n_estimators': 326, 'subsample': 0.8387535488696336, 'subsample_freq': 5, 'colsample_bytree': 0.8473355411198327, 'reg_alpha': 0.05247666769079277, 'reg_lambda': 2.8411458630603104, 'max_delta_step': 2.9573167559691527, 'scale_pos_weight': 16.84816884430018, 'max_bin': 383}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:32,861] Trial 102 finished with value: 0.45008886770256235 and parameters: {'num_leaves': 117, 'max_depth': 9, 'min_child_samples': 37, 'min_child_weight': 0.005588108253482772, 'min_split_gain': 1.4682041985617975, 'learning_rate': 0.007331566649964928, 'n_estimators': 444, 'subsample': 0.8195480195622263, 'subsample_freq': 5, 'colsample_bytree': 0.8182219324711679, 'reg_alpha': 0.09263163600017711, 'reg_lambda': 3.9698735521562143, 'max_delta_step': 3.1378209358772122, 'scale_pos_weight': 15.508300203867904, 'max_bin': 368}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:34,299] Trial 103 finished with value: 0.41206527954855443 and parameters: {'num_leaves': 116, 'max_depth': 8, 'min_child_samples': 37, 'min_child_weight': 0.007081280003666269, 'min_split_gain': 1.649720117700159, 'learning_rate': 0.005873720615354971, 'n_estimators': 445, 'subsample': 0.7798295935016886, 'subsample_freq': 1, 'colsample_bytree': 0.7685717279370321, 'reg_alpha': 0.09775165163937176, 'reg_lambda': 0.09249804109385307, 'max_delta_step': 3.383241021998156, 'scale_pos_weight': 14.672136219528047, 'max_bin': 371}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:34,778] Trial 104 finished with value: 0.3732686020033191 and parameters: {'num_leaves': 108, 'max_depth': 10, 'min_child_samples': 35, 'min_child_weight': 0.008080406491861938, 'min_split_gain': 1.474210639133467, 'learning_rate': 0.00740564826554295, 'n_estimators': 256, 'subsample': 0.7971275435921189, 'subsample_freq': 5, 'colsample_bytree': 0.7998901602245031, 'reg_alpha': 0.07407314175139376, 'reg_lambda': 4.601177348368217, 'max_delta_step': 2.780654529772284, 'scale_pos_weight': 13.225590146874103, 'max_bin': 366}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:35,645] Trial 105 finished with value: 0.43548703325265953 and parameters: {'num_leaves': 114, 'max_depth': 9, 'min_child_samples': 33, 'min_child_weight': 0.003521480776857762, 'min_split_gain': 1.730137464196381, 'learning_rate': 0.00846463346646439, 'n_estimators': 463, 'subsample': 0.5199461660400763, 'subsample_freq': 6, 'colsample_bytree': 0.8748367257459412, 'reg_alpha': 0.4509413066743883, 'reg_lambda': 3.4843315706902773, 'max_delta_step': 3.5070352850760727, 'scale_pos_weight': 23.960527860023777, 'max_bin': 353}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:36,561] Trial 106 finished with value: 0.4354331323443008 and parameters: {'num_leaves': 121, 'max_depth': 9, 'min_child_samples': 55, 'min_child_weight': 0.015242464857133459, 'min_split_gain': 1.2466846760206072, 'learning_rate': 0.011312274084594585, 'n_estimators': 485, 'subsample': 0.8111590552795997, 'subsample_freq': 2, 'colsample_bytree': 0.831504200688482, 'reg_alpha': 0.14121664413899893, 'reg_lambda': 7.1201692797156335, 'max_delta_step': 3.057034153935819, 'scale_pos_weight': 17.475992899231095, 'max_bin': 358}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:37,377] Trial 107 finished with value: 0.4088135577903876 and parameters: {'num_leaves': 103, 'max_depth': 8, 'min_child_samples': 45, 'min_child_weight': 3.20705988252764, 'min_split_gain': 1.0608325103428877, 'learning_rate': 0.00533049493344211, 'n_estimators': 475, 'subsample': 0.8196812191427918, 'subsample_freq': 5, 'colsample_bytree': 0.9269147826961892, 'reg_alpha': 0.0019662207629076583, 'reg_lambda': 2.2752320114814806, 'max_delta_step': 2.5311950467063395, 'scale_pos_weight': 23.381118546730608, 'max_bin': 361}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:38,063] Trial 108 finished with value: 0.30875019458314057 and parameters: {'num_leaves': 86, 'max_depth': 10, 'min_child_samples': 48, 'min_child_weight': 0.0010216896210116027, 'min_split_gain': 1.7962821402836775, 'learning_rate': 0.027857662452211194, 'n_estimators': 319, 'subsample': 0.6997621655301127, 'subsample_freq': 4, 'colsample_bytree': 0.8200601154507102, 'reg_alpha': 0.002417153361360633, 'reg_lambda': 1.5481908828746291, 'max_delta_step': 3.2801882340256148, 'scale_pos_weight': 12.812597834775957, 'max_bin': 368}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:38,941] Trial 109 finished with value: 0.4402110082090882 and parameters: {'num_leaves': 112, 'max_depth': 13, 'min_child_samples': 38, 'min_child_weight': 0.9670991930156421, 'min_split_gain': 1.6404097123741919, 'learning_rate': 0.0065334877907610766, 'n_estimators': 357, 'subsample': 0.7895257760762937, 'subsample_freq': 7, 'colsample_bytree': 0.7868123019040967, 'reg_alpha': 0.03855620706173714, 'reg_lambda': 3.9839089214860586, 'max_delta_step': 2.942766784979389, 'scale_pos_weight': 18.7858693748525, 'max_bin': 398}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:40,056] Trial 110 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 67, 'max_depth': 14, 'min_child_samples': 31, 'min_child_weight': 0.005270162618319237, 'min_split_gain': 1.8300768865144614, 'learning_rate': 0.00936186060412014, 'n_estimators': 453, 'subsample': 0.7156240480137943, 'subsample_freq': 5, 'colsample_bytree': 0.860096019772625, 'reg_alpha': 0.0012675054025226083, 'reg_lambda': 5.508979342352657, 'max_delta_step': 2.415164627445302, 'scale_pos_weight': 14.931874254577531, 'max_bin': 374}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:40,818] Trial 111 finished with value: 0.44293136750074247 and parameters: {'num_leaves': 45, 'max_depth': 9, 'min_child_samples': 39, 'min_child_weight': 0.0053027467931449175, 'min_split_gain': 1.3034691612548972, 'learning_rate': 0.0069885417672474895, 'n_estimators': 424, 'subsample': 0.8501925692247432, 'subsample_freq': 5, 'colsample_bytree': 0.8100010477684482, 'reg_alpha': 0.028532282658423214, 'reg_lambda': 2.987897650726011, 'max_delta_step': 3.1721589259008516, 'scale_pos_weight': 15.318270097074878, 'max_bin': 390}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:41,793] Trial 112 finished with value: 0.3367302753605624 and parameters: {'num_leaves': 28, 'max_depth': 9, 'min_child_samples': 35, 'min_child_weight': 0.01058819144474623, 'min_split_gain': 1.1797887113300665, 'learning_rate': 0.022317693177496725, 'n_estimators': 420, 'subsample': 0.8272085175774283, 'subsample_freq': 5, 'colsample_bytree': 0.8021114081459086, 'reg_alpha': 0.027170991848334446, 'reg_lambda': 1.842757401741952, 'max_delta_step': 2.7039233795734816, 'scale_pos_weight': 14.367704183750492, 'max_bin': 386}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:42,884] Trial 113 finished with value: 0.41884745820841507 and parameters: {'num_leaves': 41, 'max_depth': 9, 'min_child_samples': 39, 'min_child_weight': 0.006199679196478741, 'min_split_gain': 2.6049654414182215, 'learning_rate': 0.00744999837871851, 'n_estimators': 441, 'subsample': 0.6212031073152992, 'subsample_freq': 5, 'colsample_bytree': 0.7456043794943014, 'reg_alpha': 0.07385564427113678, 'reg_lambda': 0.05358673345962867, 'max_delta_step': 3.137660411953038, 'scale_pos_weight': 16.18827181209772, 'max_bin': 379}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:43,755] Trial 114 finished with value: 0.41884745820841507 and parameters: {'num_leaves': 53, 'max_depth': 10, 'min_child_samples': 43, 'min_child_weight': 0.6504131088876549, 'min_split_gain': 1.2925950447962382, 'learning_rate': 0.010011296287301776, 'n_estimators': 428, 'subsample': 0.7703277615618892, 'subsample_freq': 4, 'colsample_bytree': 0.8397657321356531, 'reg_alpha': 0.02848575368733902, 'reg_lambda': 3.884312078762738, 'max_delta_step': 3.348035791464031, 'scale_pos_weight': 15.625579758994867, 'max_bin': 393}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:44,477] Trial 115 finished with value: 0.4222563937634402 and parameters: {'num_leaves': 95, 'max_depth': 8, 'min_child_samples': 40, 'min_child_weight': 4.062536591599146, 'min_split_gain': 1.952548323834868, 'learning_rate': 0.005882444437750366, 'n_estimators': 390, 'subsample': 0.7994971593153686, 'subsample_freq': 6, 'colsample_bytree': 0.8047096851389172, 'reg_alpha': 0.02198337219940012, 'reg_lambda': 2.466727258251376, 'max_delta_step': 3.688895903140296, 'scale_pos_weight': 13.699503272782051, 'max_bin': 381}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:45,290] Trial 116 finished with value: 0.3805153762586116 and parameters: {'num_leaves': 46, 'max_depth': 9, 'min_child_samples': 28, 'min_child_weight': 1.6281532310889966, 'min_split_gain': 1.561946605344648, 'learning_rate': 0.008400340018024954, 'n_estimators': 412, 'subsample': 0.864312769735847, 'subsample_freq': 5, 'colsample_bytree': 0.5985288384357067, 'reg_alpha': 0.00815320271687618, 'reg_lambda': 1.0978193703262438, 'max_delta_step': 2.8942219443809267, 'scale_pos_weight': 16.58698924994103, 'max_bin': 392}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:46,186] Trial 117 finished with value: 0.4244061899152698 and parameters: {'num_leaves': 83, 'max_depth': 15, 'min_child_samples': 36, 'min_child_weight': 0.003252017315612904, 'min_split_gain': 1.4371580622652957, 'learning_rate': 0.0064653192242646014, 'n_estimators': 477, 'subsample': 0.7594074530791003, 'subsample_freq': 4, 'colsample_bytree': 0.7265982802484818, 'reg_alpha': 0.018052450009088557, 'reg_lambda': 3.2095959365122684, 'max_delta_step': 3.6011969600209537, 'scale_pos_weight': 24.497645566929407, 'max_bin': 400}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:46,657] Trial 118 finished with value: 0.3657314896065272 and parameters: {'num_leaves': 92, 'max_depth': 11, 'min_child_samples': 46, 'min_child_weight': 0.5197096381699114, 'min_split_gain': 1.520666301671714, 'learning_rate': 0.07643011858285302, 'n_estimators': 436, 'subsample': 0.8393747926511685, 'subsample_freq': 5, 'colsample_bytree': 0.890409678522016, 'reg_alpha': 0.005586286779413838, 'reg_lambda': 5.01959816713989, 'max_delta_step': 3.095996580022579, 'scale_pos_weight': 15.629379572880199, 'max_bin': 287}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:47,433] Trial 119 finished with value: 0.4064986287987451 and parameters: {'num_leaves': 60, 'max_depth': 10, 'min_child_samples': 42, 'min_child_weight': 2.451959445447092, 'min_split_gain': 1.7398438781832732, 'learning_rate': 0.005362355302744404, 'n_estimators': 451, 'subsample': 0.7769378871613538, 'subsample_freq': 4, 'colsample_bytree': 0.7689110933870663, 'reg_alpha': 0.01150346548861909, 'reg_lambda': 0.2146689112850692, 'max_delta_step': 3.238711613208668, 'scale_pos_weight': 12.368779911126799, 'max_bin': 348}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:47,799] Trial 120 finished with value: 0.4408183589813923 and parameters: {'num_leaves': 99, 'max_depth': 6, 'min_child_samples': 53, 'min_child_weight': 0.004222206218516226, 'min_split_gain': 1.3439766382483596, 'learning_rate': 0.006937233841188955, 'n_estimators': 292, 'subsample': 0.7469642695316694, 'subsample_freq': 5, 'colsample_bytree': 0.9140222867650742, 'reg_alpha': 0.04962943130716557, 'reg_lambda': 9.92253880793999, 'max_delta_step': 3.918020751016645, 'scale_pos_weight': 14.999646094516095, 'max_bin': 363}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:48,490] Trial 121 finished with value: 0.3591789603845998 and parameters: {'num_leaves': 126, 'max_depth': 9, 'min_child_samples': 40, 'min_child_weight': 0.0059859992814314715, 'min_split_gain': 1.1156319640640486, 'learning_rate': 0.04199784099068852, 'n_estimators': 405, 'subsample': 0.8533179508362083, 'subsample_freq': 5, 'colsample_bytree': 0.8128043636375258, 'reg_alpha': 0.06742031799545627, 'reg_lambda': 2.6246661424491693, 'max_delta_step': 3.182424437324201, 'scale_pos_weight': 15.42620773272079, 'max_bin': 388}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:49,267] Trial 122 finished with value: 0.45008886770256235 and parameters: {'num_leaves': 117, 'max_depth': 9, 'min_child_samples': 40, 'min_child_weight': 0.005169326120147943, 'min_split_gain': 0.427424737676976, 'learning_rate': 0.006875168826165276, 'n_estimators': 399, 'subsample': 0.8450697471789116, 'subsample_freq': 5, 'colsample_bytree': 0.818487623868752, 'reg_alpha': 0.03597249344736412, 'reg_lambda': 3.021412799492387, 'max_delta_step': 2.796808636424711, 'scale_pos_weight': 17.061194203628304, 'max_bin': 372}. Best is trial 29 with value: 0.45348088860994523.
[I 2026-01-30 15:24:50,098] Trial 123 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 107, 'max_depth': 9, 'min_child_samples': 38, 'min_child_weight': 0.010969980365942171, 'min_split_gain': 0.4445118716385441, 'learning_rate': 0.007740764742535021, 'n_estimators': 370, 'subsample': 0.815372177322699, 'subsample_freq': 5, 'colsample_bytree': 0.8254041518644475, 'reg_alpha': 0.036622476375780554, 'reg_lambda': 1.3781727114034816, 'max_delta_step': 2.8184894898347905, 'scale_pos_weight': 16.834079646231263, 'max_bin': 374}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:51,529] Trial 124 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 119, 'max_depth': 8, 'min_child_samples': 38, 'min_child_weight': 0.011233126888796628, 'min_split_gain': 0.479620781384786, 'learning_rate': 0.007838369275598757, 'n_estimators': 372, 'subsample': 0.8763607703589993, 'subsample_freq': 5, 'colsample_bytree': 0.8247959921114815, 'reg_alpha': 0.03565303484360263, 'reg_lambda': 1.4227909778724035, 'max_delta_step': 2.752304676805223, 'scale_pos_weight': 17.50731462571558, 'max_bin': 371}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:52,424] Trial 125 finished with value: 0.2809118338619231 and parameters: {'num_leaves': 107, 'max_depth': 9, 'min_child_samples': 37, 'min_child_weight': 0.009233361805460373, 'min_split_gain': 0.22952567735846596, 'learning_rate': 0.05410117095809576, 'n_estimators': 303, 'subsample': 0.8311216666235306, 'subsample_freq': 5, 'colsample_bytree': 0.7870139322625519, 'reg_alpha': 0.032647172682046935, 'reg_lambda': 0.957044383004443, 'max_delta_step': 2.8213159768439806, 'scale_pos_weight': 16.986783326591233, 'max_bin': 377}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:53,769] Trial 126 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 111, 'max_depth': 9, 'min_child_samples': 34, 'min_child_weight': 0.007286582201562764, 'min_split_gain': 0.5828530775603975, 'learning_rate': 0.007212343302090398, 'n_estimators': 382, 'subsample': 0.8149153147049034, 'subsample_freq': 6, 'colsample_bytree': 0.8341276376739807, 'reg_alpha': 0.0434386048866374, 'reg_lambda': 2.1160193943192334, 'max_delta_step': 2.5151767623493924, 'scale_pos_weight': 18.20052953210865, 'max_bin': 383}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:54,590] Trial 127 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 101, 'max_depth': 9, 'min_child_samples': 41, 'min_child_weight': 0.014659581590682513, 'min_split_gain': 0.35662798673794577, 'learning_rate': 0.006052579668875223, 'n_estimators': 423, 'subsample': 0.6631088395584892, 'subsample_freq': 5, 'colsample_bytree': 0.8510807202527102, 'reg_alpha': 0.022506161330352405, 'reg_lambda': 1.790158780911429, 'max_delta_step': 2.999205169040414, 'scale_pos_weight': 17.075347845161012, 'max_bin': 375}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:56,018] Trial 128 finished with value: 0.39236036234368704 and parameters: {'num_leaves': 118, 'max_depth': 8, 'min_child_samples': 43, 'min_child_weight': 0.021126242401746115, 'min_split_gain': 0.18841046234440428, 'learning_rate': 0.006585501140781862, 'n_estimators': 391, 'subsample': 0.8929899221709298, 'subsample_freq': 5, 'colsample_bytree': 0.8709665927857708, 'reg_alpha': 0.06347499606879137, 'reg_lambda': 0.7100420926354408, 'max_delta_step': 2.7025534959777793, 'scale_pos_weight': 17.837840674362045, 'max_bin': 372}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:57,611] Trial 129 finished with value: 0.4125814620606822 and parameters: {'num_leaves': 105, 'max_depth': 10, 'min_child_samples': 36, 'min_child_weight': 0.02904823585160812, 'min_split_gain': 0.7465252836326453, 'learning_rate': 0.008202237323119635, 'n_estimators': 492, 'subsample': 0.7828290152925643, 'subsample_freq': 5, 'colsample_bytree': 0.5217545280797282, 'reg_alpha': 0.08816612850565854, 'reg_lambda': 3.703832623096385, 'max_delta_step': 2.309784628980641, 'scale_pos_weight': 16.493981748398596, 'max_bin': 367}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:24:59,356] Trial 130 finished with value: 0.4297280159002286 and parameters: {'num_leaves': 116, 'max_depth': 8, 'min_child_samples': 39, 'min_child_weight': 0.0026666686626047103, 'min_split_gain': 0.8786908086951635, 'learning_rate': 0.005646492526646119, 'n_estimators': 465, 'subsample': 0.8032644931812157, 'subsample_freq': 6, 'colsample_bytree': 0.815077020216867, 'reg_alpha': 0.001570548950916062, 'reg_lambda': 6.764483250111061, 'max_delta_step': 2.6430729660853634, 'scale_pos_weight': 16.160532373463415, 'max_bin': 386}. Best is trial 123 with value: 0.4604208874849827.
[I 2026-01-30 15:25:00,144] Trial 131 finished with value: 0.4187688421663084 and parameters: {'num_leaves': 97, 'max_depth': 9, 'min_child_samples': 45, 'min_child_weight': 0.0045477783305759596, 'min_split_gain': 0.35336968539038127, 'learning_rate': 0.008867343676011843, 'n_estimators': 339, 'subsample': 0.8444297743801773, 'subsample_freq': 4, 'colsample_bytree': 0.8872437840838492, 'reg_alpha': 0.004072728574445719, 'reg_lambda': 0.027031335492222086, 'max_delta_step': 2.903264665375427, 'scale_pos_weight': 22.705318586389804, 'max_bin': 354}. Best is trial 123 with value: 0.4604208874849827.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:25:38,612] Trial 189 finished with value: 0.0 and parameters: {'num_leaves': 127, 'max_depth': 5, 'min_child_samples': 24, 'min_child_weight': 0.010411234883544436, 'min_split_gain': 2.575430749043955, 'learning_rate': 0.010019014045014327, 'n_estimators': 199, 'subsample': 0.9147180639275733, 'subsample_freq': 5, 'colsample_bytree': 0.7297403563742222, 'reg_alpha': 0.018652832430448345, 'reg_lambda': 8.289805455318623, 'max_delta_step': 1.4956355451058228, 'scale_pos_weight': 12.342282375446906, 'max_bin': 400}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:39,234] Trial 190 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 115, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.013015164522157695, 'min_split_gain': 2.73363684890892, 'learning_rate': 0.008948623500284232, 'n_estimators': 419, 'subsample': 0.8855815077997505, 'subsample_freq': 5, 'colsample_bytree': 0.7208897322027776, 'reg_alpha': 0.10581951776937974, 'reg_lambda': 4.986254041867877, 'max_delta_step': 1.6840053021330401, 'scale_pos_weight': 13.536028790526755, 'max_bin': 386}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:39,929] Trial 191 finished with value: 0.4281328161283653 and parameters: {'num_leaves': 115, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.02520193100235954, 'min_split_gain': 2.722998924499529, 'learning_rate': 0.008998956580281102, 'n_estimators': 420, 'subsample': 0.8925476865664052, 'subsample_freq': 5, 'colsample_bytree': 0.7205797948165691, 'reg_alpha': 0.11771419570822203, 'reg_lambda': 5.077652136191641, 'max_delta_step': 1.8806875604094264, 'scale_pos_weight': 13.801900842490651, 'max_bin': 386}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:40,904] Trial 192 finished with value: 0.46397127413127415 and parameters: {'num_leaves': 118, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.012091592338497395, 'min_split_gain': 2.6647187304740334, 'learning_rate': 0.007935714072748366, 'n_estimators': 410, 'subsample': 0.8819576709010765, 'subsample_freq': 5, 'colsample_bytree': 0.7574587056655482, 'reg_alpha': 0.07868618168974295, 'reg_lambda': 4.166041458657526, 'max_delta_step': 1.6927443901345947, 'scale_pos_weight': 13.216627311928676, 'max_bin': 379}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:41,576] Trial 193 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 118, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.009195832384981074, 'min_split_gain': 2.6357090892452835, 'learning_rate': 0.007997490848864643, 'n_estimators': 414, 'subsample': 0.8991853806985771, 'subsample_freq': 5, 'colsample_bytree': 0.7610329351540036, 'reg_alpha': 0.09579062386672006, 'reg_lambda': 4.160492149607136, 'max_delta_step': 1.6084827374092354, 'scale_pos_weight': 14.317884499553914, 'max_bin': 377}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:42,325] Trial 194 finished with value: 0.41233423606674297 and parameters: {'num_leaves': 122, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.016081621092197348, 'min_split_gain': 2.5096234385566043, 'learning_rate': 0.008058472541881256, 'n_estimators': 430, 'subsample': 0.8608367254468271, 'subsample_freq': 5, 'colsample_bytree': 0.7555380886334723, 'reg_alpha': 0.1371801224911411, 'reg_lambda': 3.3819795828824577, 'max_delta_step': 1.7103432670704417, 'scale_pos_weight': 13.180490532295961, 'max_bin': 381}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:43,118] Trial 195 finished with value: 0.4307580075914378 and parameters: {'num_leaves': 116, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.007028028084048885, 'min_split_gain': 2.6793776035396943, 'learning_rate': 0.008653401833016506, 'n_estimators': 423, 'subsample': 0.8816621223463722, 'subsample_freq': 5, 'colsample_bytree': 0.7451706537594167, 'reg_alpha': 0.07711346522447182, 'reg_lambda': 7.158558960503634, 'max_delta_step': 1.7361424779783101, 'scale_pos_weight': 13.976406916819093, 'max_bin': 374}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:43,869] Trial 196 finished with value: 0.4569244998637256 and parameters: {'num_leaves': 125, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.004451552193212287, 'min_split_gain': 2.763454735843334, 'learning_rate': 0.007515353949793867, 'n_estimators': 442, 'subsample': 0.8681972632816773, 'subsample_freq': 5, 'colsample_bytree': 0.7338611539939585, 'reg_alpha': 0.09269922370020894, 'reg_lambda': 4.303061162544096, 'max_delta_step': 1.868249735081213, 'scale_pos_weight': 13.488903972091448, 'max_bin': 385}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:44,657] Trial 197 finished with value: 0.4172631578129854 and parameters: {'num_leaves': 125, 'max_depth': 7, 'min_child_samples': 25, 'min_child_weight': 0.004879044719429417, 'min_split_gain': 0.4144171101907825, 'learning_rate': 0.00758327597610025, 'n_estimators': 449, 'subsample': 0.872474805763763, 'subsample_freq': 5, 'colsample_bytree': 0.7289644245391581, 'reg_alpha': 0.09384919811639673, 'reg_lambda': 3.5078420589062462, 'max_delta_step': 1.8118082122581431, 'scale_pos_weight': 14.825658225089082, 'max_bin': 380}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:45,213] Trial 198 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 130, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.018853007402733355, 'min_split_gain': 2.6371029754220117, 'learning_rate': 0.009137038556943497, 'n_estimators': 411, 'subsample': 0.8539995169729757, 'subsample_freq': 5, 'colsample_bytree': 0.7363941689480937, 'reg_alpha': 0.07602494463078953, 'reg_lambda': 4.171065790039895, 'max_delta_step': 1.8847993313802045, 'scale_pos_weight': 13.779537100584431, 'max_bin': 385}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:45,746] Trial 199 finished with value: 0.38664272844272846 and parameters: {'num_leaves': 122, 'max_depth': 6, 'min_child_samples': 31, 'min_child_weight': 0.04711399408953152, 'min_split_gain': 2.739243523552668, 'learning_rate': 0.017702054535382598, 'n_estimators': 398, 'subsample': 0.8686609619905461, 'subsample_freq': 5, 'colsample_bytree': 0.7015327116777289, 'reg_alpha': 0.1361367882699367, 'reg_lambda': 3.1451006350777364, 'max_delta_step': 1.997167593595977, 'scale_pos_weight': 13.57744431980133, 'max_bin': 249}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:46,448] Trial 200 finished with value: 0.4297280159002286 and parameters: {'num_leaves': 127, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.00436575620468629, 'min_split_gain': 2.697106416648386, 'learning_rate': 0.0073201496818252445, 'n_estimators': 460, 'subsample': 0.9384642647446941, 'subsample_freq': 5, 'colsample_bytree': 0.7266477639771095, 'reg_alpha': 0.06125634088105022, 'reg_lambda': 4.09888152435306, 'max_delta_step': 1.5307234522568698, 'scale_pos_weight': 14.497246993113954, 'max_bin': 372}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:47,102] Trial 201 finished with value: 0.4569244998637256 and parameters: {'num_leaves': 120, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.0058759482629145, 'min_split_gain': 2.7956186158568026, 'learning_rate': 0.008182386455267022, 'n_estimators': 441, 'subsample': 0.889589256598973, 'subsample_freq': 5, 'colsample_bytree': 0.757291689281845, 'reg_alpha': 0.10819523028132248, 'reg_lambda': 5.763202791293621, 'max_delta_step': 1.6508283168527813, 'scale_pos_weight': 13.430741338478915, 'max_bin': 388}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:47,879] Trial 202 finished with value: 0.423673481957232 and parameters: {'num_leaves': 120, 'max_depth': 7, 'min_child_samples': 28, 'min_child_weight': 0.005339432720979008, 'min_split_gain': 2.8469172663201956, 'learning_rate': 0.007530187132677697, 'n_estimators': 444, 'subsample': 0.8947710121031313, 'subsample_freq': 5, 'colsample_bytree': 0.7129917501296412, 'reg_alpha': 0.10670321091036238, 'reg_lambda': 4.950892766820989, 'max_delta_step': 1.68068268320888, 'scale_pos_weight': 12.627664034924495, 'max_bin': 388}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:48,540] Trial 203 finished with value: 0.40912980545711886 and parameters: {'num_leaves': 114, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.011044516282514617, 'min_split_gain': 0.5242174638394846, 'learning_rate': 0.008497644959280667, 'n_estimators': 427, 'subsample': 0.8615097581833556, 'subsample_freq': 5, 'colsample_bytree': 0.7471965650083783, 'reg_alpha': 0.1017867694315181, 'reg_lambda': 6.1381014130358444, 'max_delta_step': 1.5945044745460941, 'scale_pos_weight': 13.456864348687075, 'max_bin': 297}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:49,170] Trial 204 finished with value: 0.41884745820841507 and parameters: {'num_leaves': 123, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.00850553996898347, 'min_split_gain': 2.8165652708471707, 'learning_rate': 0.00963684331425493, 'n_estimators': 434, 'subsample': 0.8765109982605551, 'subsample_freq': 5, 'colsample_bytree': 0.800561147745071, 'reg_alpha': 0.1811232911182723, 'reg_lambda': 4.528783031476831, 'max_delta_step': 1.7776660169663707, 'scale_pos_weight': 14.038835019567413, 'max_bin': 378}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:49,757] Trial 205 finished with value: 0.4218688828670428 and parameters: {'num_leaves': 120, 'max_depth': 6, 'min_child_samples': 34, 'min_child_weight': 0.0034245276159285925, 'min_split_gain': 2.7415860874143356, 'learning_rate': 0.007737110480772621, 'n_estimators': 387, 'subsample': 0.8985153922265859, 'subsample_freq': 5, 'colsample_bytree': 0.6683641438250022, 'reg_alpha': 0.12579858970131683, 'reg_lambda': 8.708182611823094, 'max_delta_step': 1.6985559113445707, 'scale_pos_weight': 12.904981866395705, 'max_bin': 384}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:50,400] Trial 206 finished with value: 0.4222563937634402 and parameters: {'num_leaves': 118, 'max_depth': 8, 'min_child_samples': 29, 'min_child_weight': 0.00579739063868954, 'min_split_gain': 2.8029037374037977, 'learning_rate': 0.0071810106506026185, 'n_estimators': 421, 'subsample': 0.9118655514712457, 'subsample_freq': 5, 'colsample_bytree': 0.7194941665586094, 'reg_alpha': 0.08339356598977112, 'reg_lambda': 2.6588441588140848, 'max_delta_step': 1.9032715060836516, 'scale_pos_weight': 13.328857141119212, 'max_bin': 394}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:51,287] Trial 207 finished with value: 0.446747286394816 and parameters: {'num_leaves': 125, 'max_depth': 7, 'min_child_samples': 24, 'min_child_weight': 0.01245811183513167, 'min_split_gain': 2.5850080677648686, 'learning_rate': 0.009270288603524631, 'n_estimators': 444, 'subsample': 0.8802457608350139, 'subsample_freq': 5, 'colsample_bytree': 0.7391480267235289, 'reg_alpha': 0.23151839838727442, 'reg_lambda': 7.510088392333395, 'max_delta_step': 2.0946128576540066, 'scale_pos_weight': 14.044790477942218, 'max_bin': 381}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:51,838] Trial 208 finished with value: 0.4234175941073901 and parameters: {'num_leaves': 114, 'max_depth': 6, 'min_child_samples': 31, 'min_child_weight': 0.0076731426335713655, 'min_split_gain': 2.8793689561296243, 'learning_rate': 0.008479241045390997, 'n_estimators': 455, 'subsample': 0.8472200527523985, 'subsample_freq': 5, 'colsample_bytree': 0.7497981140613225, 'reg_alpha': 0.1542731012005152, 'reg_lambda': 5.445420314323993, 'max_delta_step': 1.4291868545770032, 'scale_pos_weight': 13.553583734913648, 'max_bin': 388}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:53,014] Trial 209 finished with value: 0.37238922782638445 and parameters: {'num_leaves': 122, 'max_depth': 15, 'min_child_samples': 27, 'min_child_weight': 0.23766245214670512, 'min_split_gain': 2.659636047080277, 'learning_rate': 0.007914323725378569, 'n_estimators': 411, 'subsample': 0.8657309885191138, 'subsample_freq': 5, 'colsample_bytree': 0.7828084337239846, 'reg_alpha': 0.002434059378188424, 'reg_lambda': 3.683409855085418, 'max_delta_step': 2.4935259444230633, 'scale_pos_weight': 12.393490925664421, 'max_bin': 375}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:53,812] Trial 210 finished with value: 0.44775131103726923 and parameters: {'num_leaves': 119, 'max_depth': 8, 'min_child_samples': 36, 'min_child_weight': 0.004358492367012103, 'min_split_gain': 0.43011124477400614, 'learning_rate': 0.007108938161025556, 'n_estimators': 436, 'subsample': 0.8885940054279355, 'subsample_freq': 5, 'colsample_bytree': 0.8277411709624644, 'reg_alpha': 0.06901674656870767, 'reg_lambda': 0.0022239423814595484, 'max_delta_step': 1.5635977859002441, 'scale_pos_weight': 14.547987801200767, 'max_bin': 395}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:54,701] Trial 211 finished with value: 0.45177850209582593 and parameters: {'num_leaves': 117, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.006326919434980468, 'min_split_gain': 2.753333066111028, 'learning_rate': 0.00826797920827323, 'n_estimators': 440, 'subsample': 0.8898038514370508, 'subsample_freq': 5, 'colsample_bytree': 0.7582798745892884, 'reg_alpha': 0.09314842652946065, 'reg_lambda': 6.613131571987925, 'max_delta_step': 2.3755713154169755, 'scale_pos_weight': 13.142274061110639, 'max_bin': 392}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:55,468] Trial 212 finished with value: 0.43458585158453084 and parameters: {'num_leaves': 117, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.006259737444107905, 'min_split_gain': 2.7433466399340274, 'learning_rate': 0.008833772082313144, 'n_estimators': 450, 'subsample': 0.8721985884512917, 'subsample_freq': 5, 'colsample_bytree': 0.7589823683835695, 'reg_alpha': 0.10629453434406705, 'reg_lambda': 6.488875276555034, 'max_delta_step': 2.195684855697977, 'scale_pos_weight': 12.88798180673376, 'max_bin': 391}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:56,061] Trial 213 finished with value: 0.4155893304134174 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.008565375708664303, 'min_split_gain': 2.845198680161064, 'learning_rate': 0.010540269887392885, 'n_estimators': 419, 'subsample': 0.9033344719718024, 'subsample_freq': 5, 'colsample_bytree': 0.7343109851785937, 'reg_alpha': 0.08284745976366167, 'reg_lambda': 0.01988506677872401, 'max_delta_step': 2.4543929921750687, 'scale_pos_weight': 13.568404867004187, 'max_bin': 385}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:56,593] Trial 214 finished with value: 0.4307580075914378 and parameters: {'num_leaves': 124, 'max_depth': 7, 'min_child_samples': 74, 'min_child_weight': 0.0013231741240438968, 'min_split_gain': 2.5498190854943523, 'learning_rate': 0.008198244934258182, 'n_estimators': 429, 'subsample': 0.8824164011849538, 'subsample_freq': 5, 'colsample_bytree': 0.7225875542832435, 'reg_alpha': 0.10126657594573964, 'reg_lambda': 5.132965839772524, 'max_delta_step': 1.7720317074806693, 'scale_pos_weight': 13.119647128609564, 'max_bin': 396}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:57,362] Trial 215 finished with value: 0.4386067577901155 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.14244003318526122, 'min_split_gain': 2.7064243213259362, 'learning_rate': 0.007428317659290873, 'n_estimators': 439, 'subsample': 0.8914416584509572, 'subsample_freq': 5, 'colsample_bytree': 0.6929949670398946, 'reg_alpha': 0.06063714089710962, 'reg_lambda': 7.072808662247586, 'max_delta_step': 1.61018450407217, 'scale_pos_weight': 13.995664610599485, 'max_bin': 389}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:57,797] Trial 216 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 116, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.009933277071093781, 'min_split_gain': 2.7740642638469075, 'learning_rate': 0.011466940496336255, 'n_estimators': 459, 'subsample': 0.5619912073179347, 'subsample_freq': 5, 'colsample_bytree': 0.7920476232543161, 'reg_alpha': 0.003417363048598857, 'reg_lambda': 4.357845648815838, 'max_delta_step': 1.4893189376234244, 'scale_pos_weight': 12.716996614836248, 'max_bin': 382}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:58,214] Trial 217 finished with value: 0.4446391377091377 and parameters: {'num_leaves': 116, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.06695066882800972, 'min_split_gain': 2.7483803268586238, 'learning_rate': 0.0114898744977855, 'n_estimators': 461, 'subsample': 0.5400331950242803, 'subsample_freq': 5, 'colsample_bytree': 0.7895781854781584, 'reg_alpha': 0.12009222099329275, 'reg_lambda': 4.412744458215999, 'max_delta_step': 1.4416489094417821, 'scale_pos_weight': 12.583951855817181, 'max_bin': 400}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:58,664] Trial 218 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 120, 'max_depth': 6, 'min_child_samples': 24, 'min_child_weight': 0.01015772823383014, 'min_split_gain': 2.79633408344845, 'learning_rate': 0.009347313957510208, 'n_estimators': 465, 'subsample': 0.5548598461534456, 'subsample_freq': 5, 'colsample_bytree': 0.7631822261163635, 'reg_alpha': 0.08626066054426716, 'reg_lambda': 5.846326821667109, 'max_delta_step': 1.9516602989490384, 'scale_pos_weight': 12.146919633053566, 'max_bin': 382}. Best is trial 162 with value: 0.46397127413127415.
[I 2026-01-30 15:25:59,348] Trial 219 finished with value: 0.4670956694567702 and parameters: {'num_leaves': 113, 'max_depth': 6, 'min_child_samples': 30, 'min_child_weight': 0.014471803327391484, 'min_split_gain': 2.6367701902493796, 'learning_rate': 0.010118417913370077, 'n_estimators': 483, 'subsample': 0.5657703820704191, 'subsample_freq': 5, 'colsample_bytree': 0.8041831949194596, 'reg_alpha': 0.16352107517288028, 'reg_lambda': 3.3396234818694275, 'max_delta_step': 1.645103743056067, 'scale_pos_weight': 13.245194207668575, 'max_bin': 387}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:25:59,691] Trial 220 finished with value: 0.4082277341423258 and parameters: {'num_leaves': 113, 'max_depth': 5, 'min_child_samples': 30, 'min_child_weight': 0.013433912876855636, 'min_split_gain': 0.2772069084168089, 'learning_rate': 0.008930354676132455, 'n_estimators': 477, 'subsample': 0.5711856749701137, 'subsample_freq': 5, 'colsample_bytree': 0.8023986315316968, 'reg_alpha': 0.13356679678926214, 'reg_lambda': 3.2937577834297893, 'max_delta_step': 1.6890603894863612, 'scale_pos_weight': 19.34457046230094, 'max_bin': 379}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:00,162] Trial 221 finished with value: 0.4220524801945675 and parameters: {'num_leaves': 118, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.014826769756300399, 'min_split_gain': 2.459494579485326, 'learning_rate': 0.010310772052399437, 'n_estimators': 489, 'subsample': 0.5280411644449454, 'subsample_freq': 5, 'colsample_bytree': 0.7908509918514951, 'reg_alpha': 0.2164822302310687, 'reg_lambda': 3.8873578289659547, 'max_delta_step': 1.4794648218938793, 'scale_pos_weight': 13.05598726407545, 'max_bin': 387}. Best is trial 219 with value: 0.4670956694567702.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:26:22,819] Trial 253 finished with value: 0.0 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 41, 'min_child_weight': 0.010588343872227688, 'min_split_gain': 0.2519550159581553, 'learning_rate': 0.00516465294040709, 'n_estimators': 490, 'subsample': 0.7398417260938973, 'subsample_freq': 5, 'colsample_bytree': 0.8366356130272068, 'reg_alpha': 0.004832664435551446, 'reg_lambda': 5.370299912036433, 'max_delta_step': 0.031108409552369043, 'scale_pos_weight': 13.643242162864158, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:23,985] Trial 254 finished with value: 0.4059748648648649 and parameters: {'num_leaves': 111, 'max_depth': 7, 'min_child_samples': 43, 'min_child_weight': 0.009261191381120026, 'min_split_gain': 0.18058929999538717, 'learning_rate': 0.005675256278887942, 'n_estimators': 464, 'subsample': 0.7342870671119158, 'subsample_freq': 5, 'colsample_bytree': 0.6343182606009103, 'reg_alpha': 0.004109833262690052, 'reg_lambda': 7.436333233618608, 'max_delta_step': 1.790505663082398, 'scale_pos_weight': 14.219645637833402, 'max_bin': 391}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:25,818] Trial 255 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 110, 'max_depth': 6, 'min_child_samples': 30, 'min_child_weight': 0.012240650293690427, 'min_split_gain': 0.48214594162055846, 'learning_rate': 0.00589846173377009, 'n_estimators': 484, 'subsample': 0.7753561675032824, 'subsample_freq': 5, 'colsample_bytree': 0.8332775084017324, 'reg_alpha': 0.004496283942868184, 'reg_lambda': 6.11157452393346, 'max_delta_step': 2.198455025200498, 'scale_pos_weight': 13.0670782903714, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:27,060] Trial 256 finished with value: 0.38841966382638793 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.009100506250228691, 'min_split_gain': 0.6632046934003587, 'learning_rate': 0.005005558716927794, 'n_estimators': 479, 'subsample': 0.7152175252136522, 'subsample_freq': 5, 'colsample_bytree': 0.7965829307218709, 'reg_alpha': 0.003428849713202995, 'reg_lambda': 4.892974443524898, 'max_delta_step': 1.7031753251627444, 'scale_pos_weight': 13.711262104250906, 'max_bin': 389}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:27,891] Trial 257 finished with value: 0.4418270547207549 and parameters: {'num_leaves': 112, 'max_depth': 6, 'min_child_samples': 30, 'min_child_weight': 0.010388790825564842, 'min_split_gain': 0.428893728700028, 'learning_rate': 0.0056748844318985055, 'n_estimators': 474, 'subsample': 0.7287962713275746, 'subsample_freq': 5, 'colsample_bytree': 0.766841890653359, 'reg_alpha': 0.0029256345694458072, 'reg_lambda': 8.066654416205179, 'max_delta_step': 1.9835566493242989, 'scale_pos_weight': 14.820115885567969, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:28,649] Trial 258 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 127, 'max_depth': 7, 'min_child_samples': 40, 'min_child_weight': 0.01560986587598912, 'min_split_gain': 0.3585728207681655, 'learning_rate': 0.006454157642741838, 'n_estimators': 494, 'subsample': 0.7415619694997014, 'subsample_freq': 5, 'colsample_bytree': 0.8475702106983245, 'reg_alpha': 0.00384489725611046, 'reg_lambda': 5.972730325479018, 'max_delta_step': 1.8436642941955848, 'scale_pos_weight': 14.397182554741919, 'max_bin': 395}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:29,751] Trial 259 finished with value: 0.43884374246911595 and parameters: {'num_leaves': 119, 'max_depth': 8, 'min_child_samples': 44, 'min_child_weight': 0.012026065342992297, 'min_split_gain': 0.5461933696127028, 'learning_rate': 0.008425595060909697, 'n_estimators': 456, 'subsample': 0.8996484071601742, 'subsample_freq': 5, 'colsample_bytree': 0.8471480657596898, 'reg_alpha': 0.0030456663759820236, 'reg_lambda': 4.686913867805054, 'max_delta_step': 1.6642151630448834, 'scale_pos_weight': 12.998074766129657, 'max_bin': 388}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:30,368] Trial 260 finished with value: 0.4187688421663084 and parameters: {'num_leaves': 114, 'max_depth': 5, 'min_child_samples': 57, 'min_child_weight': 0.022836737962256104, 'min_split_gain': 0.30631488671032203, 'learning_rate': 0.007854486492090458, 'n_estimators': 466, 'subsample': 0.6800850050862831, 'subsample_freq': 5, 'colsample_bytree': 0.7879241587556863, 'reg_alpha': 0.0044809916762396556, 'reg_lambda': 6.547517746020491, 'max_delta_step': 1.7873757787133426, 'scale_pos_weight': 13.440733774781927, 'max_bin': 385}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:31,119] Trial 261 finished with value: 0.41723625346500354 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 41, 'min_child_weight': 0.014101888098350656, 'min_split_gain': 0.40549673214143045, 'learning_rate': 0.005419508461797268, 'n_estimators': 459, 'subsample': 0.7554201121316716, 'subsample_freq': 5, 'colsample_bytree': 0.7443490832758446, 'reg_alpha': 0.006080069786505707, 'reg_lambda': 5.234978577344264, 'max_delta_step': 2.0916075506092415, 'scale_pos_weight': 13.908414160992047, 'max_bin': 391}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:32,309] Trial 262 finished with value: 0.45008886770256235 and parameters: {'num_leaves': 124, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.038778230976404156, 'min_split_gain': 2.2025285424292314, 'learning_rate': 0.007203603314300992, 'n_estimators': 453, 'subsample': 0.7692718012812406, 'subsample_freq': 5, 'colsample_bytree': 0.8078000142060766, 'reg_alpha': 0.002232868239038932, 'reg_lambda': 7.389183890886262, 'max_delta_step': 2.411782233240682, 'scale_pos_weight': 12.436303832838295, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:32,946] Trial 263 finished with value: 0.45160416331119463 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.010494897540314019, 'min_split_gain': 0.44844860151437055, 'learning_rate': 0.0058993970626523215, 'n_estimators': 487, 'subsample': 0.574064829483979, 'subsample_freq': 5, 'colsample_bytree': 0.8607111350415783, 'reg_alpha': 2.2301868137630954, 'reg_lambda': 4.515601608232988, 'max_delta_step': 1.902254941907082, 'scale_pos_weight': 13.297618283814169, 'max_bin': 389}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:33,506] Trial 264 finished with value: 0.4370141747760645 and parameters: {'num_leaves': 118, 'max_depth': 12, 'min_child_samples': 42, 'min_child_weight': 0.008357409570047084, 'min_split_gain': 2.7126415539100446, 'learning_rate': 0.008607876835064499, 'n_estimators': 478, 'subsample': 0.7772544288473402, 'subsample_freq': 5, 'colsample_bytree': 0.754480255243268, 'reg_alpha': 0.22763380087130133, 'reg_lambda': 8.706667646841655, 'max_delta_step': 1.6019410201971318, 'scale_pos_weight': 14.044078389359056, 'max_bin': 305}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:34,018] Trial 265 finished with value: 0.4313351648816222 and parameters: {'num_leaves': 121, 'max_depth': 6, 'min_child_samples': 39, 'min_child_weight': 0.017113326561807543, 'min_split_gain': 0.5753724397809905, 'learning_rate': 0.006415840973742289, 'n_estimators': 448, 'subsample': 0.5590816581180671, 'subsample_freq': 5, 'colsample_bytree': 0.8260967256765628, 'reg_alpha': 0.002908889274026046, 'reg_lambda': 9.92849945794469, 'max_delta_step': 1.7858197063887749, 'scale_pos_weight': 12.96153601464242, 'max_bin': 393}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:35,013] Trial 266 finished with value: 0.4362296649863029 and parameters: {'num_leaves': 83, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.008134552949653415, 'min_split_gain': 0.7766013792545483, 'learning_rate': 0.009252078844432578, 'n_estimators': 498, 'subsample': 0.7657612089979601, 'subsample_freq': 5, 'colsample_bytree': 0.8399079968014846, 'reg_alpha': 0.06693329406653742, 'reg_lambda': 5.49727629826549, 'max_delta_step': 2.1464119698246376, 'scale_pos_weight': 14.567799124189502, 'max_bin': 385}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:35,847] Trial 267 finished with value: 0.45519617215962044 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.011823479944761116, 'min_split_gain': 0.933195894249367, 'learning_rate': 0.007926115526611186, 'n_estimators': 470, 'subsample': 0.7454508682046469, 'subsample_freq': 5, 'colsample_bytree': 0.7392446014425275, 'reg_alpha': 0.005358335435677003, 'reg_lambda': 6.7465701856114135, 'max_delta_step': 1.7125793278148254, 'scale_pos_weight': 13.583468710797206, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:36,741] Trial 268 finished with value: 0.4586660210873791 and parameters: {'num_leaves': 111, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.013558082952185174, 'min_split_gain': 2.409702289369366, 'learning_rate': 0.008091807703416956, 'n_estimators': 470, 'subsample': 0.7419656000607346, 'subsample_freq': 5, 'colsample_bytree': 0.7391332894458568, 'reg_alpha': 0.006672067625417488, 'reg_lambda': 7.08741805392801, 'max_delta_step': 1.718422139947767, 'scale_pos_weight': 12.612985655259841, 'max_bin': 395}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:37,332] Trial 269 finished with value: 0.29314590090090087 and parameters: {'num_leaves': 107, 'max_depth': 8, 'min_child_samples': 26, 'min_child_weight': 0.014177948935991974, 'min_split_gain': 2.4631563169658715, 'learning_rate': 0.03844232956737226, 'n_estimators': 475, 'subsample': 0.7203720868981546, 'subsample_freq': 5, 'colsample_bytree': 0.7318371384381517, 'reg_alpha': 0.0075676858745367575, 'reg_lambda': 7.091288764900701, 'max_delta_step': 1.7089315914642325, 'scale_pos_weight': 11.80119727253594, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:38,181] Trial 270 finished with value: 0.32935464882645804 and parameters: {'num_leaves': 109, 'max_depth': 13, 'min_child_samples': 22, 'min_child_weight': 0.01833644904141573, 'min_split_gain': 2.6005637008176614, 'learning_rate': 0.008256769917478056, 'n_estimators': 468, 'subsample': 0.7388455840990198, 'subsample_freq': 5, 'colsample_bytree': 0.7433154114056507, 'reg_alpha': 0.004136593618526066, 'reg_lambda': 3.5979638775726954, 'max_delta_step': 1.6337189183706284, 'scale_pos_weight': 9.639859635099096, 'max_bin': 397}. Best is trial 219 with value: 0.4670956694567702.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:26:38,582] Trial 271 finished with value: 0.0 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 25, 'min_child_weight': 0.012507624609009395, 'min_split_gain': 2.3737149208251855, 'learning_rate': 0.007624517601615487, 'n_estimators': 166, 'subsample': 0.74397433507838, 'subsample_freq': 6, 'colsample_bytree': 0.726734525082977, 'reg_alpha': 0.021814940617978243, 'reg_lambda': 0.009260150951756592, 'max_delta_step': 1.8105757511211202, 'scale_pos_weight': 12.538879882222856, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:39,582] Trial 272 finished with value: 0.4244061899152698 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 27, 'min_child_weight': 0.012046121258436742, 'min_split_gain': 0.896635863761211, 'learning_rate': 0.00894487839465309, 'n_estimators': 484, 'subsample': 0.7303688189996983, 'subsample_freq': 5, 'colsample_bytree': 0.7067651995337623, 'reg_alpha': 0.004540206210806559, 'reg_lambda': 4.398685139222714, 'max_delta_step': 1.9948216751280563, 'scale_pos_weight': 21.102324318857764, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:40,314] Trial 273 finished with value: 0.4246786949776632 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 28, 'min_child_weight': 0.01617667237370825, 'min_split_gain': 2.4401037470174423, 'learning_rate': 0.007615507064271415, 'n_estimators': 473, 'subsample': 0.7440977846793393, 'subsample_freq': 5, 'colsample_bytree': 0.7389234334839433, 'reg_alpha': 0.0058570822522058365, 'reg_lambda': 8.336845614161549, 'max_delta_step': 1.5359972983091192, 'scale_pos_weight': 15.128580404791933, 'max_bin': 388}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:41,079] Trial 274 finished with value: 0.4370141747760645 and parameters: {'num_leaves': 87, 'max_depth': 7, 'min_child_samples': 64, 'min_child_weight': 0.19025080639673847, 'min_split_gain': 2.665771743710295, 'learning_rate': 0.007139071919279221, 'n_estimators': 482, 'subsample': 0.5935041059334609, 'subsample_freq': 5, 'colsample_bytree': 0.7237867988959011, 'reg_alpha': 0.004803257174161019, 'reg_lambda': 6.17414417906136, 'max_delta_step': 1.8649940615526934, 'scale_pos_weight': 12.16856538896691, 'max_bin': 316}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:41,919] Trial 275 finished with value: 0.4463601466392397 and parameters: {'num_leaves': 125, 'max_depth': 8, 'min_child_samples': 26, 'min_child_weight': 0.015092012818132454, 'min_split_gain': 2.5277473661360688, 'learning_rate': 0.009575023691568913, 'n_estimators': 464, 'subsample': 0.6270452825197191, 'subsample_freq': 7, 'colsample_bytree': 0.7447251433656971, 'reg_alpha': 0.005115380770844544, 'reg_lambda': 4.607388850753468, 'max_delta_step': 1.6965858778816494, 'scale_pos_weight': 13.429980586005025, 'max_bin': 382}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:42,895] Trial 276 finished with value: 0.40214894644137156 and parameters: {'num_leaves': 114, 'max_depth': 11, 'min_child_samples': 23, 'min_child_weight': 0.019970268752848033, 'min_split_gain': 2.566439604585687, 'learning_rate': 0.007981169390849639, 'n_estimators': 491, 'subsample': 0.7560737902039187, 'subsample_freq': 5, 'colsample_bytree': 0.7358237185286153, 'reg_alpha': 0.005992827883709314, 'reg_lambda': 3.335239056560018, 'max_delta_step': 1.6446384189162162, 'scale_pos_weight': 14.263009715920386, 'max_bin': 395}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:43,829] Trial 277 finished with value: 0.44293136750074247 and parameters: {'num_leaves': 120, 'max_depth': 12, 'min_child_samples': 32, 'min_child_weight': 0.011316426328049078, 'min_split_gain': 2.8295138467556162, 'learning_rate': 0.008653871769258591, 'n_estimators': 470, 'subsample': 0.6528319768877696, 'subsample_freq': 5, 'colsample_bytree': 0.7144657031444757, 'reg_alpha': 0.1660507641821421, 'reg_lambda': 8.242013801628564, 'max_delta_step': 4.749118086431537, 'scale_pos_weight': 12.910800960917484, 'max_bin': 386}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:44,671] Trial 278 finished with value: 0.42861217714555305 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 28, 'min_child_weight': 0.009061598018371145, 'min_split_gain': 1.070823253257049, 'learning_rate': 0.00985670052093994, 'n_estimators': 452, 'subsample': 0.6922512291694969, 'subsample_freq': 5, 'colsample_bytree': 0.7511042956690653, 'reg_alpha': 0.007021858550407253, 'reg_lambda': 2.582657049913446, 'max_delta_step': 1.5370364208334795, 'scale_pos_weight': 13.775792845487931, 'max_bin': 397}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:45,513] Trial 279 finished with value: 0.4418270547207549 and parameters: {'num_leaves': 122, 'max_depth': 7, 'min_child_samples': 43, 'min_child_weight': 1.3936957509760057, 'min_split_gain': 2.9181318237001146, 'learning_rate': 0.01115692528263652, 'n_estimators': 410, 'subsample': 0.7311425320874774, 'subsample_freq': 5, 'colsample_bytree': 0.7723619386308539, 'reg_alpha': 0.04621672265779063, 'reg_lambda': 9.980066209938064, 'max_delta_step': 1.7366886391105798, 'scale_pos_weight': 12.631076207754182, 'max_bin': 390}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:46,246] Trial 280 finished with value: 0.4188052508270618 and parameters: {'num_leaves': 116, 'max_depth': 8, 'min_child_samples': 30, 'min_child_weight': 0.013041587437461928, 'min_split_gain': 2.6305891603560654, 'learning_rate': 0.007201213518370265, 'n_estimators': 477, 'subsample': 0.5267471201659092, 'subsample_freq': 5, 'colsample_bytree': 0.7934492672905675, 'reg_alpha': 0.011035432689515269, 'reg_lambda': 6.9451416184706884, 'max_delta_step': 1.9343931573381057, 'scale_pos_weight': 14.279528367620062, 'max_bin': 382}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:46,988] Trial 281 finished with value: 0.4269531837418814 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 25, 'min_child_weight': 0.008890113309856177, 'min_split_gain': 2.681907125024631, 'learning_rate': 0.00803869679924117, 'n_estimators': 487, 'subsample': 0.7498609871754575, 'subsample_freq': 5, 'colsample_bytree': 0.7604604942790509, 'reg_alpha': 0.0034922408639006617, 'reg_lambda': 4.14012391667754, 'max_delta_step': 1.7655601384637258, 'scale_pos_weight': 13.435275306154434, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:47,492] Trial 282 finished with value: 0.40205619464093917 and parameters: {'num_leaves': 130, 'max_depth': 6, 'min_child_samples': 27, 'min_child_weight': 0.010842895436476433, 'min_split_gain': 2.7328174752517653, 'learning_rate': 0.026467998660963714, 'n_estimators': 456, 'subsample': 0.8641408550145778, 'subsample_freq': 5, 'colsample_bytree': 0.779538164482944, 'reg_alpha': 0.38151046235204356, 'reg_lambda': 5.486235216471544, 'max_delta_step': 1.456853207115542, 'scale_pos_weight': 14.879185659157852, 'max_bin': 279}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:48,240] Trial 283 finished with value: 0.4313351648816222 and parameters: {'num_leaves': 109, 'max_depth': 13, 'min_child_samples': 31, 'min_child_weight': 0.0014309951185962828, 'min_split_gain': 2.8040261238500532, 'learning_rate': 0.009041931448127795, 'n_estimators': 418, 'subsample': 0.7022997016478436, 'subsample_freq': 5, 'colsample_bytree': 0.8106189804030914, 'reg_alpha': 0.1261859501833023, 'reg_lambda': 4.861543921247577, 'max_delta_step': 2.0654067812736976, 'scale_pos_weight': 13.923980449426855, 'max_bin': 394}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:48,798] Trial 284 finished with value: 0.4377404243328156 and parameters: {'num_leaves': 118, 'max_depth': 7, 'min_child_samples': 24, 'min_child_weight': 0.013094795849618717, 'min_split_gain': 1.0025704116102097, 'learning_rate': 0.007619027930161315, 'n_estimators': 464, 'subsample': 0.8732777134408846, 'subsample_freq': 5, 'colsample_bytree': 0.5561228997307313, 'reg_alpha': 8.13416231978633, 'reg_lambda': 6.508248009194483, 'max_delta_step': 1.6470199579793723, 'scale_pos_weight': 13.145785053832853, 'max_bin': 379}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:49,776] Trial 285 finished with value: 0.4405967514573397 and parameters: {'num_leaves': 126, 'max_depth': 12, 'min_child_samples': 41, 'min_child_weight': 0.007543064907749849, 'min_split_gain': 2.4059664622896846, 'learning_rate': 0.006856691549939384, 'n_estimators': 445, 'subsample': 0.8751857062955516, 'subsample_freq': 6, 'colsample_bytree': 0.7275120689923337, 'reg_alpha': 0.005884347311234315, 'reg_lambda': 3.694689424667999, 'max_delta_step': 1.8468447409420015, 'scale_pos_weight': 12.518898277950877, 'max_bin': 327}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:50,430] Trial 286 finished with value: 0.4319691996889688 and parameters: {'num_leaves': 115, 'max_depth': 7, 'min_child_samples': 26, 'min_child_weight': 0.009891333377330783, 'min_split_gain': 2.1140848508258654, 'learning_rate': 0.008679876580940132, 'n_estimators': 431, 'subsample': 0.721929375961208, 'subsample_freq': 5, 'colsample_bytree': 0.818347296485931, 'reg_alpha': 0.02624905715739377, 'reg_lambda': 2.990073505636586, 'max_delta_step': 1.5629894687787407, 'scale_pos_weight': 13.456195330809406, 'max_bin': 388}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:51,411] Trial 287 finished with value: 0.39967528849017087 and parameters: {'num_leaves': 107, 'max_depth': 8, 'min_child_samples': 30, 'min_child_weight': 0.2784509725331273, 'min_split_gain': 2.873369114168212, 'learning_rate': 0.0053591733932114565, 'n_estimators': 406, 'subsample': 0.9036288102103436, 'subsample_freq': 5, 'colsample_bytree': 0.9064429032651301, 'reg_alpha': 0.0371129100728673, 'reg_lambda': 5.481254942813557, 'max_delta_step': 1.7480566547393843, 'scale_pos_weight': 14.596848050332815, 'max_bin': 384}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:52,092] Trial 288 finished with value: 0.4172631578129854 and parameters: {'num_leaves': 123, 'max_depth': 5, 'min_child_samples': 29, 'min_child_weight': 0.0153489219608527, 'min_split_gain': 2.5000001879871, 'learning_rate': 0.006068525765604675, 'n_estimators': 493, 'subsample': 0.7608705201220575, 'subsample_freq': 5, 'colsample_bytree': 0.7215889415023736, 'reg_alpha': 0.06084277883186551, 'reg_lambda': 7.501440624509707, 'max_delta_step': 1.3066357887952227, 'scale_pos_weight': 13.815543109936694, 'max_bin': 393}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:52,671] Trial 289 finished with value: 0.4459409463714727 and parameters: {'num_leaves': 120, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.08667932101353051, 'min_split_gain': 0.716618081201661, 'learning_rate': 0.00814088085442764, 'n_estimators': 358, 'subsample': 0.7497669605375415, 'subsample_freq': 5, 'colsample_bytree': 0.6992401637826927, 'reg_alpha': 0.008609265805198342, 'reg_lambda': 4.40904710008712, 'max_delta_step': 1.9501942571581017, 'scale_pos_weight': 12.873115083913806, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:53,176] Trial 290 finished with value: 0.4392739917212641 and parameters: {'num_leaves': 111, 'max_depth': 6, 'min_child_samples': 40, 'min_child_weight': 0.011513918913837465, 'min_split_gain': 2.629256703684207, 'learning_rate': 0.009418649036908604, 'n_estimators': 425, 'subsample': 0.563148828069383, 'subsample_freq': 5, 'colsample_bytree': 0.7518428843393746, 'reg_alpha': 0.0017994763931886255, 'reg_lambda': 5.848003358065164, 'max_delta_step': 1.5023462759802773, 'scale_pos_weight': 14.146354554530385, 'max_bin': 389}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:54,050] Trial 291 finished with value: 0.35757739483844747 and parameters: {'num_leaves': 81, 'max_depth': 8, 'min_child_samples': 27, 'min_child_weight': 0.008179315212636401, 'min_split_gain': 2.0226289701163926, 'learning_rate': 0.007496221302613739, 'n_estimators': 386, 'subsample': 0.8639208601614602, 'subsample_freq': 5, 'colsample_bytree': 0.7340986597169116, 'reg_alpha': 0.04293263645502806, 'reg_lambda': 4.078610157356441, 'max_delta_step': 1.6292500440792093, 'scale_pos_weight': 11.24170980800651, 'max_bin': 377}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:54,689] Trial 292 finished with value: 0.4276967165051226 and parameters: {'num_leaves': 117, 'max_depth': 7, 'min_child_samples': 61, 'min_child_weight': 0.9920534064694775, 'min_split_gain': 2.7180516543111457, 'learning_rate': 0.010476643270768003, 'n_estimators': 438, 'subsample': 0.8868010384884771, 'subsample_freq': 5, 'colsample_bytree': 0.7679281850493903, 'reg_alpha': 0.13637335495082517, 'reg_lambda': 8.015449210104215, 'max_delta_step': 1.8017554510592253, 'scale_pos_weight': 13.466060105652579, 'max_bin': 385}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:55,630] Trial 293 finished with value: 0.3708051557439792 and parameters: {'num_leaves': 113, 'max_depth': 11, 'min_child_samples': 28, 'min_child_weight': 0.027419709263764747, 'min_split_gain': 0.19248435154514118, 'learning_rate': 0.006574441938183301, 'n_estimators': 414, 'subsample': 0.9119282434608514, 'subsample_freq': 6, 'colsample_bytree': 0.8003580744816914, 'reg_alpha': 0.19590692446442426, 'reg_lambda': 0.0010171626951480692, 'max_delta_step': 1.4021771934525353, 'scale_pos_weight': 13.141847575211358, 'max_bin': 391}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:56,494] Trial 294 finished with value: 0.42729856022316304 and parameters: {'num_leaves': 122, 'max_depth': 7, 'min_child_samples': 45, 'min_child_weight': 0.0017819468396840278, 'min_split_gain': 0.4797492723432194, 'learning_rate': 0.007202830608969625, 'n_estimators': 479, 'subsample': 0.735599977057904, 'subsample_freq': 5, 'colsample_bytree': 0.7110335085929333, 'reg_alpha': 0.10535466214233387, 'reg_lambda': 3.38089399166921, 'max_delta_step': 2.0230949147637425, 'scale_pos_weight': 18.866424240796835, 'max_bin': 394}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:57,064] Trial 295 finished with value: 0.41340267228734295 and parameters: {'num_leaves': 128, 'max_depth': 6, 'min_child_samples': 43, 'min_child_weight': 0.009363086322324606, 'min_split_gain': 2.807206107170118, 'learning_rate': 0.012044492693133518, 'n_estimators': 462, 'subsample': 0.8792106586184437, 'subsample_freq': 5, 'colsample_bytree': 0.7858568911633892, 'reg_alpha': 0.005346728689690136, 'reg_lambda': 5.134782500082372, 'max_delta_step': 1.1429122056920094, 'scale_pos_weight': 19.89085329937704, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:57,692] Trial 296 finished with value: 0.42739897871739335 and parameters: {'num_leaves': 118, 'max_depth': 12, 'min_child_samples': 29, 'min_child_weight': 0.020780288652454623, 'min_split_gain': 2.5873712286617536, 'learning_rate': 0.008274602843275077, 'n_estimators': 447, 'subsample': 0.8591993945265742, 'subsample_freq': 5, 'colsample_bytree': 0.7459365471632203, 'reg_alpha': 0.05429081699358319, 'reg_lambda': 6.762194586088954, 'max_delta_step': 1.6537195800140032, 'scale_pos_weight': 12.173124805233853, 'max_bin': 381}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:58,020] Trial 297 finished with value: 0.3914620155711267 and parameters: {'num_leaves': 115, 'max_depth': 6, 'min_child_samples': 25, 'min_child_weight': 0.013881540792022326, 'min_split_gain': 2.2687710855989507, 'learning_rate': 0.05144882753227371, 'n_estimators': 470, 'subsample': 0.8989070957732849, 'subsample_freq': 5, 'colsample_bytree': 0.8198547125382043, 'reg_alpha': 0.07339787352383281, 'reg_lambda': 4.772523982386485, 'max_delta_step': 1.8603238318160709, 'scale_pos_weight': 13.833201373810347, 'max_bin': 388}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:58,531] Trial 298 finished with value: 0.4418270547207549 and parameters: {'num_leaves': 89, 'max_depth': 8, 'min_child_samples': 32, 'min_child_weight': 0.007418581624266819, 'min_split_gain': 2.333845596346323, 'learning_rate': 0.009808306228815967, 'n_estimators': 432, 'subsample': 0.7842080538213816, 'subsample_freq': 5, 'colsample_bytree': 0.7388483539613782, 'reg_alpha': 0.023193643979761595, 'reg_lambda': 6.2810620180847465, 'max_delta_step': 1.723445426347385, 'scale_pos_weight': 14.394235392237798, 'max_bin': 397}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:58,906] Trial 299 finished with value: 0.37602174843098785 and parameters: {'num_leaves': 119, 'max_depth': 7, 'min_child_samples': 42, 'min_child_weight': 0.011399087509992252, 'min_split_gain': 0.8163172900324903, 'learning_rate': 0.005023161941380107, 'n_estimators': 404, 'subsample': 0.871271131498194, 'subsample_freq': 3, 'colsample_bytree': 0.8056917515428794, 'reg_alpha': 0.003431239164808447, 'reg_lambda': 2.673815209700514, 'max_delta_step': 1.8924728580001635, 'scale_pos_weight': 12.545819570800978, 'max_bin': 392}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:59,377] Trial 300 finished with value: 0.3935018091453899 and parameters: {'num_leaves': 85, 'max_depth': 14, 'min_child_samples': 39, 'min_child_weight': 0.34819958513231153, 'min_split_gain': 2.768499503707744, 'learning_rate': 0.005889227148172162, 'n_estimators': 393, 'subsample': 0.8832296294375808, 'subsample_freq': 5, 'colsample_bytree': 0.8983953049185761, 'reg_alpha': 0.017300914095306225, 'reg_lambda': 3.8099897978877872, 'max_delta_step': 1.5676154077943538, 'scale_pos_weight': 13.659247287260177, 'max_bin': 384}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:26:59,744] Trial 301 finished with value: 0.4392739917212641 and parameters: {'num_leaves': 110, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.017050108730804307, 'min_split_gain': 2.9018415918661575, 'learning_rate': 0.02219987100908615, 'n_estimators': 455, 'subsample': 0.9239154199293307, 'subsample_freq': 5, 'colsample_bytree': 0.826591950814908, 'reg_alpha': 0.034085742434587535, 'reg_lambda': 8.656611246398091, 'max_delta_step': 2.226561852862675, 'scale_pos_weight': 15.01136168456069, 'max_bin': 335}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:00,348] Trial 302 finished with value: 0.4220524801945675 and parameters: {'num_leaves': 133, 'max_depth': 7, 'min_child_samples': 24, 'min_child_weight': 0.010148554727621037, 'min_split_gain': 0.33467294848383844, 'learning_rate': 0.008792339695027872, 'n_estimators': 422, 'subsample': 0.5503211121656759, 'subsample_freq': 5, 'colsample_bytree': 0.7226717308988062, 'reg_alpha': 5.492589420507786, 'reg_lambda': 0.07404573016347309, 'max_delta_step': 2.4707985272183897, 'scale_pos_weight': 12.913251080849651, 'max_bin': 375}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:00,599] Trial 303 finished with value: 0.40214894644137156 and parameters: {'num_leaves': 114, 'max_depth': 7, 'min_child_samples': 21, 'min_child_weight': 0.013170109116942419, 'min_split_gain': 2.6856123827137806, 'learning_rate': 0.06135448720537018, 'n_estimators': 439, 'subsample': 0.9873789372598978, 'subsample_freq': 5, 'colsample_bytree': 0.7609867040975048, 'reg_alpha': 0.002294147892293979, 'reg_lambda': 5.506061086331172, 'max_delta_step': 1.4540804012680486, 'scale_pos_weight': 11.659655434225826, 'max_bin': 389}. Best is trial 219 with value: 0.4670956694567702.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:27:35,303] Trial 354 finished with value: 0.0 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.003133929327200112, 'min_split_gain': 2.22801046601966, 'learning_rate': 0.0060440500537643944, 'n_estimators': 100, 'subsample': 0.7663462346201345, 'subsample_freq': 5, 'colsample_bytree': 0.8414649152254954, 'reg_alpha': 0.06975536490258177, 'reg_lambda': 1.9223329101577473, 'max_delta_step': 1.8559815314841985, 'scale_pos_weight': 15.136776759765581, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:35,932] Trial 355 finished with value: 0.446747286394816 and parameters: {'num_leaves': 106, 'max_depth': 6, 'min_child_samples': 35, 'min_child_weight': 0.00272659643845798, 'min_split_gain': 2.126393902270544, 'learning_rate': 0.006502273628559225, 'n_estimators': 484, 'subsample': 0.7756267261695703, 'subsample_freq': 5, 'colsample_bytree': 0.8323707878403668, 'reg_alpha': 0.04981224086448289, 'reg_lambda': 2.448774333585518, 'max_delta_step': 1.9417953475989487, 'scale_pos_weight': 15.402644789261194, 'max_bin': 395}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:36,707] Trial 356 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.002098135157525189, 'min_split_gain': 2.2470879227962444, 'learning_rate': 0.007368157677227407, 'n_estimators': 500, 'subsample': 0.7576515257929453, 'subsample_freq': 5, 'colsample_bytree': 0.8585398411410451, 'reg_alpha': 0.07702996566901871, 'reg_lambda': 1.3884969653450663, 'max_delta_step': 1.8407680732813476, 'scale_pos_weight': 14.642229582607074, 'max_bin': 396}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:37,681] Trial 357 finished with value: 0.4418270547207549 and parameters: {'num_leaves': 108, 'max_depth': 6, 'min_child_samples': 37, 'min_child_weight': 0.002765099652129678, 'min_split_gain': 2.1756761743370503, 'learning_rate': 0.007003506367068744, 'n_estimators': 493, 'subsample': 0.7482347592544913, 'subsample_freq': 5, 'colsample_bytree': 0.8204669274568769, 'reg_alpha': 0.05216937044673289, 'reg_lambda': 2.220863208782004, 'max_delta_step': 1.9715773129625174, 'scale_pos_weight': 14.93751143325588, 'max_bin': 393}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:38,386] Trial 358 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0016115062575277424, 'min_split_gain': 2.107677753394599, 'learning_rate': 0.006390110453780945, 'n_estimators': 476, 'subsample': 0.8245252722070007, 'subsample_freq': 5, 'colsample_bytree': 0.8311654159392174, 'reg_alpha': 0.0639598980997612, 'reg_lambda': 2.7983406754054574, 'max_delta_step': 1.7937493254462216, 'scale_pos_weight': 15.258185422203681, 'max_bin': 397}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:38,995] Trial 359 finished with value: 0.42170303205241355 and parameters: {'num_leaves': 106, 'max_depth': 5, 'min_child_samples': 38, 'min_child_weight': 0.0011925819778327426, 'min_split_gain': 2.063346732660758, 'learning_rate': 0.005868833631649267, 'n_estimators': 477, 'subsample': 0.8222435916207528, 'subsample_freq': 5, 'colsample_bytree': 0.8269039541835197, 'reg_alpha': 0.05737151389996904, 'reg_lambda': 2.721136010941783, 'max_delta_step': 1.7836715611828835, 'scale_pos_weight': 16.365643474351426, 'max_bin': 387}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:39,905] Trial 360 finished with value: 0.4434550279124413 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.0021088309570171143, 'min_split_gain': 2.1636106444899474, 'learning_rate': 0.0064201099169521915, 'n_estimators': 474, 'subsample': 0.8254032701143152, 'subsample_freq': 5, 'colsample_bytree': 0.8530515388808612, 'reg_alpha': 0.06226568780182152, 'reg_lambda': 2.9643519518654453, 'max_delta_step': 1.8607526380893504, 'scale_pos_weight': 15.7111727933513, 'max_bin': 400}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:40,636] Trial 361 finished with value: 0.41723625346500354 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0015702071287626578, 'min_split_gain': 2.287838034153401, 'learning_rate': 0.016189696639756432, 'n_estimators': 485, 'subsample': 0.814875556371679, 'subsample_freq': 5, 'colsample_bytree': 0.8436038270550904, 'reg_alpha': 0.07955806205758056, 'reg_lambda': 1.9293426347919467, 'max_delta_step': 1.801529098423349, 'scale_pos_weight': 15.422710889855505, 'max_bin': 394}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:41,405] Trial 362 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0016185705145785744, 'min_split_gain': 2.0736412456526048, 'learning_rate': 0.0062509289578423334, 'n_estimators': 491, 'subsample': 0.7765239706188818, 'subsample_freq': 5, 'colsample_bytree': 0.8323353118494773, 'reg_alpha': 0.0708776206320898, 'reg_lambda': 3.019520161098779, 'max_delta_step': 1.9333077052165557, 'scale_pos_weight': 16.074013227676627, 'max_bin': 379}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:42,075] Trial 363 finished with value: 0.46397127413127415 and parameters: {'num_leaves': 111, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.002434181200331842, 'min_split_gain': 1.9830548903077934, 'learning_rate': 0.0072375565926415305, 'n_estimators': 484, 'subsample': 0.7871574101740112, 'subsample_freq': 5, 'colsample_bytree': 0.8378478579962658, 'reg_alpha': 0.08223521023483711, 'reg_lambda': 2.4133532516108263, 'max_delta_step': 1.7349525414907825, 'scale_pos_weight': 14.913735390164186, 'max_bin': 391}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:42,799] Trial 364 finished with value: 0.46397127413127415 and parameters: {'num_leaves': 111, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0019587553429974043, 'min_split_gain': 1.9655653911287754, 'learning_rate': 0.007290874447180021, 'n_estimators': 469, 'subsample': 0.7872479481963154, 'subsample_freq': 5, 'colsample_bytree': 0.8354120448843952, 'reg_alpha': 0.07329080655416031, 'reg_lambda': 1.7337965198484249, 'max_delta_step': 1.73593475145935, 'scale_pos_weight': 15.254419800330433, 'max_bin': 391}. Best is trial 219 with value: 0.4670956694567702.
[I 2026-01-30 15:27:43,478] Trial 365 finished with value: 0.46757692052242156 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.001855407040646922, 'min_split_gain': 2.0193379148001367, 'learning_rate': 0.007427970551415465, 'n_estimators': 469, 'subsample': 0.7848871303596519, 'subsample_freq': 5, 'colsample_bytree': 0.841287298353238, 'reg_alpha': 0.06265905316957028, 'reg_lambda': 1.5959984997968513, 'max_delta_step': 1.7154492633720235, 'scale_pos_weight': 15.232016290315896, 'max_bin': 389}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:44,349] Trial 366 finished with value: 0.4281328161283653 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0018410846127623116, 'min_split_gain': 1.9779629391379563, 'learning_rate': 0.007267205777130037, 'n_estimators': 469, 'subsample': 0.7823844921408469, 'subsample_freq': 5, 'colsample_bytree': 0.8482050228728698, 'reg_alpha': 0.06647950616231045, 'reg_lambda': 1.4796924440398174, 'max_delta_step': 2.0585867582363835, 'scale_pos_weight': 15.950766137688754, 'max_bin': 384}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:46,996] Trial 367 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0013275830592444017, 'min_split_gain': 1.895879467993125, 'learning_rate': 0.006798823087034568, 'n_estimators': 480, 'subsample': 0.78438732931985, 'subsample_freq': 5, 'colsample_bytree': 0.8414082627299612, 'reg_alpha': 0.05453560433618594, 'reg_lambda': 1.9311760424814155, 'max_delta_step': 1.744813454343463, 'scale_pos_weight': 15.629176951570344, 'max_bin': 388}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:50,177] Trial 368 finished with value: 0.4269531837418814 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.0020063583919974234, 'min_split_gain': 1.9236483537556501, 'learning_rate': 0.007475116836743338, 'n_estimators': 476, 'subsample': 0.7702359900430057, 'subsample_freq': 5, 'colsample_bytree': 0.8340667551751659, 'reg_alpha': 0.0900660903049852, 'reg_lambda': 1.2130422993454772, 'max_delta_step': 1.9118350208254036, 'scale_pos_weight': 15.191365304753438, 'max_bin': 379}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:51,264] Trial 369 finished with value: 0.446747286394816 and parameters: {'num_leaves': 110, 'max_depth': 6, 'min_child_samples': 37, 'min_child_weight': 0.0018977305135273173, 'min_split_gain': 2.010672846869464, 'learning_rate': 0.007097773419085547, 'n_estimators': 468, 'subsample': 0.7888905457424157, 'subsample_freq': 5, 'colsample_bytree': 0.8680870403676308, 'reg_alpha': 0.04815699009925144, 'reg_lambda': 1.5862117046975526, 'max_delta_step': 1.6800425600623112, 'scale_pos_weight': 15.15454483151476, 'max_bin': 390}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:52,267] Trial 370 finished with value: 0.4386067577901155 and parameters: {'num_leaves': 111, 'max_depth': 6, 'min_child_samples': 36, 'min_child_weight': 0.0023373780974377607, 'min_split_gain': 2.0263886747377136, 'learning_rate': 0.007646651330542593, 'n_estimators': 484, 'subsample': 0.804616969795926, 'subsample_freq': 5, 'colsample_bytree': 0.8407752630003074, 'reg_alpha': 0.06392656734982723, 'reg_lambda': 1.7007530435831222, 'max_delta_step': 1.8705027526822726, 'scale_pos_weight': 15.351412658981005, 'max_bin': 384}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:53,253] Trial 371 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.0022089402190664602, 'min_split_gain': 2.059415314886903, 'learning_rate': 0.006690238658265401, 'n_estimators': 477, 'subsample': 0.7706309299872004, 'subsample_freq': 5, 'colsample_bytree': 0.8255490735490331, 'reg_alpha': 0.08134959491460163, 'reg_lambda': 2.245943592495522, 'max_delta_step': 1.7487044873618924, 'scale_pos_weight': 15.016089704652591, 'max_bin': 388}. Best is trial 365 with value: 0.46757692052242156.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:27:53,533] Trial 372 finished with value: 0.0 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.002346723905040747, 'min_split_gain': 2.057286730207819, 'learning_rate': 0.006688500205116276, 'n_estimators': 473, 'subsample': 0.7738331532636663, 'subsample_freq': 5, 'colsample_bytree': 0.8541644711985152, 'reg_alpha': 0.07890474445268787, 'reg_lambda': 2.1394342716386046, 'max_delta_step': 0.3921474222792014, 'scale_pos_weight': 15.748085862705604, 'max_bin': 386}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:54,147] Trial 373 finished with value: 0.4450950603062078 and parameters: {'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.0017454170083910656, 'min_split_gain': 1.9819917887545762, 'learning_rate': 0.007235359292919989, 'n_estimators': 490, 'subsample': 0.7679852116849728, 'subsample_freq': 5, 'colsample_bytree': 0.8259837152929214, 'reg_alpha': 0.08868435531284101, 'reg_lambda': 2.2491977317897818, 'max_delta_step': 1.6406725248984828, 'scale_pos_weight': 16.261601868049247, 'max_bin': 382}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:54,798] Trial 374 finished with value: 0.4434550279124413 and parameters: {'num_leaves': 103, 'max_depth': 6, 'min_child_samples': 38, 'min_child_weight': 0.0014731320913676461, 'min_split_gain': 2.1222698017367345, 'learning_rate': 0.006555032464192595, 'n_estimators': 467, 'subsample': 0.7872188278889262, 'subsample_freq': 5, 'colsample_bytree': 0.8229007811154223, 'reg_alpha': 0.07399709347727901, 'reg_lambda': 1.7329946694804534, 'max_delta_step': 1.7802788916476675, 'scale_pos_weight': 15.030244667220142, 'max_bin': 389}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:55,197] Trial 375 finished with value: 0.45008886770256235 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.0021938956506027136, 'min_split_gain': 1.9618235840487692, 'learning_rate': 0.0074916315218106575, 'n_estimators': 483, 'subsample': 0.7639229862841331, 'subsample_freq': 5, 'colsample_bytree': 0.8447715972480804, 'reg_alpha': 0.06469107530478713, 'reg_lambda': 2.439570489059424, 'max_delta_step': 1.727783787915536, 'scale_pos_weight': 15.451306989232654, 'max_bin': 376}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:55,653] Trial 376 finished with value: 0.4463601466392397 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.0025297351315511224, 'min_split_gain': 2.1000923407535645, 'learning_rate': 0.006988422646989741, 'n_estimators': 477, 'subsample': 0.7806934643559669, 'subsample_freq': 5, 'colsample_bytree': 0.8367341748322328, 'reg_alpha': 0.045795399541419854, 'reg_lambda': 1.2846882913849504, 'max_delta_step': 1.6206463733496006, 'scale_pos_weight': 14.921319299595988, 'max_bin': 385}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:56,225] Trial 377 finished with value: 0.45519617215962044 and parameters: {'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 39, 'min_child_weight': 0.003198579627289972, 'min_split_gain': 2.0133525599570334, 'learning_rate': 0.007975917889127432, 'n_estimators': 492, 'subsample': 0.793425830167432, 'subsample_freq': 5, 'colsample_bytree': 0.8146467347834351, 'reg_alpha': 0.08351374360311577, 'reg_lambda': 1.8960255481741322, 'max_delta_step': 1.7963543644455788, 'scale_pos_weight': 16.731076263594325, 'max_bin': 390}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:56,608] Trial 378 finished with value: 0.413218542704314 and parameters: {'num_leaves': 102, 'max_depth': 4, 'min_child_samples': 36, 'min_child_weight': 0.0018301892045842147, 'min_split_gain': 2.1503606655913217, 'learning_rate': 0.00759630917140414, 'n_estimators': 486, 'subsample': 0.8086647153994143, 'subsample_freq': 5, 'colsample_bytree': 0.8579810662499308, 'reg_alpha': 0.09427372711888735, 'reg_lambda': 2.4016594393184554, 'max_delta_step': 1.7148307507043616, 'scale_pos_weight': 14.822351616037212, 'max_bin': 379}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:57,110] Trial 379 finished with value: 0.4569244998637256 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0012969782956009914, 'min_split_gain': 1.9252070249321949, 'learning_rate': 0.006645989802123153, 'n_estimators': 472, 'subsample': 0.763815622550755, 'subsample_freq': 5, 'colsample_bytree': 0.8207170194790581, 'reg_alpha': 0.059651436347853436, 'reg_lambda': 1.4685713813511008, 'max_delta_step': 1.8467435803301344, 'scale_pos_weight': 15.354898860261136, 'max_bin': 387}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:57,463] Trial 380 finished with value: 0.33056924512366137 and parameters: {'num_leaves': 108, 'max_depth': 8, 'min_child_samples': 39, 'min_child_weight': 0.0012773475801593956, 'min_split_gain': 1.9687318876554558, 'learning_rate': 0.07553161910429858, 'n_estimators': 466, 'subsample': 0.7607011134923574, 'subsample_freq': 5, 'colsample_bytree': 0.8232467794477486, 'reg_alpha': 0.054280822720739176, 'reg_lambda': 0.8356199526421184, 'max_delta_step': 1.8906958814599084, 'scale_pos_weight': 15.87816774118501, 'max_bin': 391}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:58,058] Trial 381 finished with value: 0.44123668383977505 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0010111590523773414, 'min_split_gain': 1.9105244582728245, 'learning_rate': 0.006593086693352625, 'n_estimators': 474, 'subsample': 0.7746195749898968, 'subsample_freq': 5, 'colsample_bytree': 0.8299044606838202, 'reg_alpha': 0.06645988342053494, 'reg_lambda': 1.4967408263105257, 'max_delta_step': 2.0190261233184947, 'scale_pos_weight': 15.47075666870201, 'max_bin': 258}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:58,866] Trial 382 finished with value: 0.4463601466392397 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.0017410979416127928, 'min_split_gain': 2.031646725677969, 'learning_rate': 0.006314165899821885, 'n_estimators': 481, 'subsample': 0.7857404886578366, 'subsample_freq': 5, 'colsample_bytree': 0.8141285726274814, 'reg_alpha': 0.059840795014911005, 'reg_lambda': 1.0345020819164963, 'max_delta_step': 1.8396159350169947, 'scale_pos_weight': 15.22611062933942, 'max_bin': 388}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:27:59,594] Trial 383 finished with value: 0.446747286394816 and parameters: {'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.001459798664672581, 'min_split_gain': 1.8750494979310208, 'learning_rate': 0.0069811245532553365, 'n_estimators': 464, 'subsample': 0.7614363723325203, 'subsample_freq': 5, 'colsample_bytree': 0.8371160031967549, 'reg_alpha': 0.09690370266502076, 'reg_lambda': 1.77068647473428, 'max_delta_step': 2.912546098816617, 'scale_pos_weight': 16.14994026488986, 'max_bin': 392}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:00,237] Trial 384 finished with value: 0.45160416331119463 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.002423229610350545, 'min_split_gain': 2.0987461108975487, 'learning_rate': 0.005997740420038524, 'n_estimators': 471, 'subsample': 0.7720868676977256, 'subsample_freq': 5, 'colsample_bytree': 0.8266579376680916, 'reg_alpha': 0.06987964175754446, 'reg_lambda': 2.1863778087596923, 'max_delta_step': 1.77047734809225, 'scale_pos_weight': 14.934696419921632, 'max_bin': 381}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:01,001] Trial 385 finished with value: 0.4463601466392397 and parameters: {'num_leaves': 110, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0034109212563264517, 'min_split_gain': 1.9463043005986786, 'learning_rate': 0.007158325339090226, 'n_estimators': 492, 'subsample': 0.7790197953929727, 'subsample_freq': 5, 'colsample_bytree': 0.8490171852286001, 'reg_alpha': 0.10833063367604556, 'reg_lambda': 1.3912310557941476, 'max_delta_step': 1.8679239976337119, 'scale_pos_weight': 15.414674188986451, 'max_bin': 386}. Best is trial 365 with value: 0.46757692052242156.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:28:01,366] Trial 386 finished with value: 0.0 and parameters: {'num_leaves': 106, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.0015882260301271673, 'min_split_gain': 2.222186121433633, 'learning_rate': 0.006687909612649783, 'n_estimators': 478, 'subsample': 0.7999633418102711, 'subsample_freq': 5, 'colsample_bytree': 0.8165979874015129, 'reg_alpha': 0.04823110493771191, 'reg_lambda': 1.1443881238284033, 'max_delta_step': 0.9174555158854161, 'scale_pos_weight': 14.731777817963419, 'max_bin': 391}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:02,076] Trial 387 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 39, 'min_child_weight': 0.0011287083461342295, 'min_split_gain': 2.0467535828877725, 'learning_rate': 0.0076165677827326715, 'n_estimators': 488, 'subsample': 0.7633658533806783, 'subsample_freq': 5, 'colsample_bytree': 0.8327459576960107, 'reg_alpha': 0.08096337237093285, 'reg_lambda': 2.6847189398437092, 'max_delta_step': 1.659565395331604, 'scale_pos_weight': 15.73919720265618, 'max_bin': 383}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:02,735] Trial 388 finished with value: 0.43295439784183315 and parameters: {'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.0029553710767350277, 'min_split_gain': 2.1725296371171767, 'learning_rate': 0.008005842353783675, 'n_estimators': 500, 'subsample': 0.7543631976777111, 'subsample_freq': 5, 'colsample_bytree': 0.8147956425694539, 'reg_alpha': 0.06075720343307298, 'reg_lambda': 1.6753396859298122, 'max_delta_step': 1.9770842378837379, 'scale_pos_weight': 15.246560748210864, 'max_bin': 387}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:03,399] Trial 389 finished with value: 0.4446391377091377 and parameters: {'num_leaves': 112, 'max_depth': 7, 'min_child_samples': 40, 'min_child_weight': 0.0019658106009936634, 'min_split_gain': 1.8281462187574347, 'learning_rate': 0.006002229084215111, 'n_estimators': 483, 'subsample': 0.7919457594249646, 'subsample_freq': 5, 'colsample_bytree': 0.8431201504332395, 'reg_alpha': 0.11927040859180082, 'reg_lambda': 2.159047300460116, 'max_delta_step': 1.7506374359212897, 'scale_pos_weight': 14.617939051919636, 'max_bin': 392}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:04,188] Trial 390 finished with value: 0.4586660210873791 and parameters: {'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.00397978174439681, 'min_split_gain': 2.411213325338657, 'learning_rate': 0.006584341835934025, 'n_estimators': 474, 'subsample': 0.7737396465998684, 'subsample_freq': 5, 'colsample_bytree': 0.8256385348868904, 'reg_alpha': 0.092396005018124, 'reg_lambda': 2.6920397804675433, 'max_delta_step': 2.1109658110383878, 'scale_pos_weight': 14.84204776629331, 'max_bin': 395}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:04,874] Trial 391 finished with value: 0.42318562462213666 and parameters: {'num_leaves': 23, 'max_depth': 8, 'min_child_samples': 79, 'min_child_weight': 0.003985134341398896, 'min_split_gain': 2.3956806414764316, 'learning_rate': 0.00737697500904303, 'n_estimators': 492, 'subsample': 0.7797310590735639, 'subsample_freq': 5, 'colsample_bytree': 0.8519010015421797, 'reg_alpha': 0.09788378295591092, 'reg_lambda': 2.7161900996564485, 'max_delta_step': 2.095008700612545, 'scale_pos_weight': 14.546273521372107, 'max_bin': 395}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:05,622] Trial 392 finished with value: 0.43458585158453084 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0027310675996341217, 'min_split_gain': 2.431855243845025, 'learning_rate': 0.006963044235647577, 'n_estimators': 463, 'subsample': 0.8052926378107392, 'subsample_freq': 5, 'colsample_bytree': 0.8301670887634861, 'reg_alpha': 0.12963400599985778, 'reg_lambda': 3.091526305218633, 'max_delta_step': 2.042666712057718, 'scale_pos_weight': 14.90018000727607, 'max_bin': 395}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:06,358] Trial 393 finished with value: 0.33374068679068675 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0035000733286765437, 'min_split_gain': 2.3075747377176126, 'learning_rate': 0.008003400504255052, 'n_estimators': 483, 'subsample': 0.7895490441098202, 'subsample_freq': 5, 'colsample_bytree': 0.8059847999336406, 'reg_alpha': 0.08404154398737114, 'reg_lambda': 2.4750727402293156, 'max_delta_step': 1.9524407948650029, 'scale_pos_weight': 8.71439959841478, 'max_bin': 393}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:07,293] Trial 394 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.00429867003575486, 'min_split_gain': 2.259846007978681, 'learning_rate': 0.0062198915626606064, 'n_estimators': 475, 'subsample': 0.8326115524496787, 'subsample_freq': 5, 'colsample_bytree': 0.8391002817419939, 'reg_alpha': 0.10963353913537807, 'reg_lambda': 1.9929891848643744, 'max_delta_step': 2.7930284764133857, 'scale_pos_weight': 14.70302575570497, 'max_bin': 396}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:07,976] Trial 395 finished with value: 0.46397127413127415 and parameters: {'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.0045088109296121445, 'min_split_gain': 2.3476651457578077, 'learning_rate': 0.005782945058612567, 'n_estimators': 471, 'subsample': 0.8329517131766406, 'subsample_freq': 5, 'colsample_bytree': 0.8662372365785683, 'reg_alpha': 0.10822977085925811, 'reg_lambda': 1.9248649661278079, 'max_delta_step': 2.8177405412142624, 'scale_pos_weight': 14.989876638098023, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:08,312] Trial 396 finished with value: 0.06499245232245231 and parameters: {'num_leaves': 99, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.004183887254855233, 'min_split_gain': 2.4631485903206203, 'learning_rate': 0.005593001768759715, 'n_estimators': 222, 'subsample': 0.8278067223678582, 'subsample_freq': 5, 'colsample_bytree': 0.8729320954164094, 'reg_alpha': 0.1406492803756841, 'reg_lambda': 1.7807221348764444, 'max_delta_step': 2.8171676040773104, 'scale_pos_weight': 15.032758218644934, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:09,141] Trial 397 finished with value: 0.4450950603062078 and parameters: {'num_leaves': 104, 'max_depth': 8, 'min_child_samples': 34, 'min_child_weight': 0.004936766965455815, 'min_split_gain': 2.3451527181576797, 'learning_rate': 0.005818524444518898, 'n_estimators': 475, 'subsample': 0.8198299005642586, 'subsample_freq': 5, 'colsample_bytree': 0.8614231805800522, 'reg_alpha': 0.11265002587308881, 'reg_lambda': 2.009429835590907, 'max_delta_step': 2.920114733508418, 'scale_pos_weight': 18.378421015893693, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:09,760] Trial 398 finished with value: 0.423673481957232 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.004533270781086377, 'min_split_gain': 2.265249069890415, 'learning_rate': 0.005407715938017296, 'n_estimators': 463, 'subsample': 0.8386354025986826, 'subsample_freq': 5, 'colsample_bytree': 0.8491264511707526, 'reg_alpha': 0.10092695237324431, 'reg_lambda': 2.0845079174601886, 'max_delta_step': 2.7693493577516475, 'scale_pos_weight': 15.59746606539705, 'max_bin': 395}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:10,529] Trial 399 finished with value: 0.45177850209582593 and parameters: {'num_leaves': 103, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.0037779106633445926, 'min_split_gain': 2.3618632831076463, 'learning_rate': 0.006146687481112353, 'n_estimators': 492, 'subsample': 0.8311502975401831, 'subsample_freq': 5, 'colsample_bytree': 0.8576062905535815, 'reg_alpha': 0.1532316900546598, 'reg_lambda': 2.438258753451279, 'max_delta_step': 2.746374032257459, 'scale_pos_weight': 15.010361708749144, 'max_bin': 390}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:11,162] Trial 400 finished with value: 0.44123668383977505 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.00427855832161, 'min_split_gain': 2.286030427040151, 'learning_rate': 0.005765877866238187, 'n_estimators': 476, 'subsample': 0.834694264046297, 'subsample_freq': 5, 'colsample_bytree': 0.8382440227362475, 'reg_alpha': 0.12162116193957813, 'reg_lambda': 1.7942220968333045, 'max_delta_step': 2.893216655102133, 'scale_pos_weight': 14.751462410041066, 'max_bin': 396}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:11,733] Trial 401 finished with value: 0.4281328161283653 and parameters: {'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.003259282933887411, 'min_split_gain': 2.2205235178342364, 'learning_rate': 0.0062564584033603515, 'n_estimators': 468, 'subsample': 0.5011465565240791, 'subsample_freq': 5, 'colsample_bytree': 0.8439868685156664, 'reg_alpha': 0.09147116378047873, 'reg_lambda': 2.594017540507758, 'max_delta_step': 2.830472382250521, 'scale_pos_weight': 16.008202492707326, 'max_bin': 392}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:12,710] Trial 402 finished with value: 0.44841184267849943 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0037841801812155025, 'min_split_gain': 2.4009168914128, 'learning_rate': 0.006369992930791394, 'n_estimators': 500, 'subsample': 0.8173852390677375, 'subsample_freq': 5, 'colsample_bytree': 0.8244979483062717, 'reg_alpha': 0.1932807535816622, 'reg_lambda': 2.0933081215498115, 'max_delta_step': 2.697312087387669, 'scale_pos_weight': 15.293685196538046, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:13,543] Trial 403 finished with value: 0.44984250125125125 and parameters: {'num_leaves': 101, 'max_depth': 8, 'min_child_samples': 34, 'min_child_weight': 0.003187347473645789, 'min_split_gain': 2.3295153710560865, 'learning_rate': 0.007588065397439898, 'n_estimators': 486, 'subsample': 0.8158877473065543, 'subsample_freq': 5, 'colsample_bytree': 0.8610268311831037, 'reg_alpha': 0.07807556017109174, 'reg_lambda': 1.5017548401507341, 'max_delta_step': 2.766449303309366, 'scale_pos_weight': 14.634833583754874, 'max_bin': 390}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:14,341] Trial 404 finished with value: 0.45177850209582593 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 31, 'min_child_weight': 0.004594693267844437, 'min_split_gain': 2.2645469370976343, 'learning_rate': 0.008260586169854103, 'n_estimators': 477, 'subsample': 0.8288694802332166, 'subsample_freq': 5, 'colsample_bytree': 0.8291351245311669, 'reg_alpha': 0.10032339613083414, 'reg_lambda': 1.2962936708187605, 'max_delta_step': 1.6110051067816218, 'scale_pos_weight': 15.752717631642032, 'max_bin': 400}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:15,026] Trial 405 finished with value: 0.4386067577901155 and parameters: {'num_leaves': 106, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0028083971352143217, 'min_split_gain': 2.1578741256298177, 'learning_rate': 0.0071611526814131694, 'n_estimators': 490, 'subsample': 0.8060380714132346, 'subsample_freq': 5, 'colsample_bytree': 0.8403168007681063, 'reg_alpha': 0.13045172000335348, 'reg_lambda': 2.7904800041529163, 'max_delta_step': 3.015454938071845, 'scale_pos_weight': 16.574206952977562, 'max_bin': 393}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:15,752] Trial 406 finished with value: 0.46576710953659795 and parameters: {'num_leaves': 99, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.005689414361153813, 'min_split_gain': 2.1874010061792615, 'learning_rate': 0.00550675268000792, 'n_estimators': 461, 'subsample': 0.8006956263547624, 'subsample_freq': 5, 'colsample_bytree': 0.8777304244551006, 'reg_alpha': 0.07923893555270983, 'reg_lambda': 1.888003146962824, 'max_delta_step': 2.930089548240697, 'scale_pos_weight': 15.086743569110332, 'max_bin': 388}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:16,475] Trial 407 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.0021391836357166965, 'min_split_gain': 2.191565286583375, 'learning_rate': 0.005418120143569562, 'n_estimators': 463, 'subsample': 0.8003112601260858, 'subsample_freq': 5, 'colsample_bytree': 0.8785401646771023, 'reg_alpha': 0.07498027917783728, 'reg_lambda': 1.748988296266447, 'max_delta_step': 2.980853462670301, 'scale_pos_weight': 15.11551395085226, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:17,236] Trial 408 finished with value: 0.41395537547129657 and parameters: {'num_leaves': 98, 'max_depth': 8, 'min_child_samples': 34, 'min_child_weight': 0.0023136234241493345, 'min_split_gain': 2.2277361002554614, 'learning_rate': 0.005159534572487346, 'n_estimators': 461, 'subsample': 0.8010319857004097, 'subsample_freq': 5, 'colsample_bytree': 0.8815742758151071, 'reg_alpha': 0.07374017548055398, 'reg_lambda': 1.7184359198404722, 'max_delta_step': 2.926647164686511, 'scale_pos_weight': 15.188534635638243, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:17,873] Trial 409 finished with value: 0.4569244998637256 and parameters: {'num_leaves': 99, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.001998694904506389, 'min_split_gain': 2.1948522543515323, 'learning_rate': 0.005385014919784071, 'n_estimators': 469, 'subsample': 0.813204295867237, 'subsample_freq': 5, 'colsample_bytree': 0.8901629345843215, 'reg_alpha': 0.07156862885480039, 'reg_lambda': 1.9968463002047379, 'max_delta_step': 3.0487555140698777, 'scale_pos_weight': 15.577144448403269, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:18,570] Trial 410 finished with value: 0.44123668383977505 and parameters: {'num_leaves': 96, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0026874014349510342, 'min_split_gain': 2.121617034077549, 'learning_rate': 0.005468816799762989, 'n_estimators': 477, 'subsample': 0.7994693585121508, 'subsample_freq': 5, 'colsample_bytree': 0.8778676470434117, 'reg_alpha': 0.08088512792479184, 'reg_lambda': 1.3435247097077578, 'max_delta_step': 3.002412221221454, 'scale_pos_weight': 15.058492273912204, 'max_bin': 400}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:19,573] Trial 411 finished with value: 0.4156908145591165 and parameters: {'num_leaves': 97, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.00204153376242531, 'min_split_gain': 2.3085833816444405, 'learning_rate': 0.005820238553930608, 'n_estimators': 467, 'subsample': 0.9537416120024106, 'subsample_freq': 5, 'colsample_bytree': 0.8765567719311758, 'reg_alpha': 0.09042766871437087, 'reg_lambda': 1.6853127827759542, 'max_delta_step': 2.842779996993233, 'scale_pos_weight': 14.721081242470877, 'max_bin': 393}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:20,345] Trial 412 finished with value: 0.44841184267849943 and parameters: {'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.00310673549591188, 'min_split_gain': 2.1698547294692214, 'learning_rate': 0.005198486020288365, 'n_estimators': 481, 'subsample': 0.8219892381683849, 'subsample_freq': 5, 'colsample_bytree': 0.8646261225051118, 'reg_alpha': 0.07095848537222023, 'reg_lambda': 2.2711227677385866, 'max_delta_step': 2.908190170998879, 'scale_pos_weight': 16.14293848115048, 'max_bin': 394}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:21,070] Trial 413 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 100, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.002325401197060109, 'min_split_gain': 2.3929387610775734, 'learning_rate': 0.00591117354048998, 'n_estimators': 458, 'subsample': 0.792446761076112, 'subsample_freq': 5, 'colsample_bytree': 0.8712936788495949, 'reg_alpha': 0.10476698226070293, 'reg_lambda': 1.86732388063634, 'max_delta_step': 2.9170102663091515, 'scale_pos_weight': 15.561524253576922, 'max_bin': 391}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:21,916] Trial 414 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.001632412599512798, 'min_split_gain': 2.227432128150272, 'learning_rate': 0.005476446252673626, 'n_estimators': 491, 'subsample': 0.8129595602514217, 'subsample_freq': 5, 'colsample_bytree': 0.8691460576415252, 'reg_alpha': 0.044999627437062824, 'reg_lambda': 1.136374981158061, 'max_delta_step': 2.7724210369510027, 'scale_pos_weight': 15.12016028276126, 'max_bin': 397}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:22,571] Trial 415 finished with value: 0.44984250125125125 and parameters: {'num_leaves': 105, 'max_depth': 8, 'min_child_samples': 34, 'min_child_weight': 0.003516370060903156, 'min_split_gain': 2.2789987047048554, 'learning_rate': 0.005718689830764524, 'n_estimators': 473, 'subsample': 0.8020514546166776, 'subsample_freq': 5, 'colsample_bytree': 0.8544460833345472, 'reg_alpha': 0.7673094832554932, 'reg_lambda': 1.4911992058333972, 'max_delta_step': 2.6333044961042384, 'scale_pos_weight': 14.495165246061005, 'max_bin': 389}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:23,372] Trial 416 finished with value: 0.4569244998637256 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.0029409457979662, 'min_split_gain': 2.120411238518592, 'learning_rate': 0.006077235772885002, 'n_estimators': 483, 'subsample': 0.7876452512453309, 'subsample_freq': 5, 'colsample_bytree': 0.8864212251559773, 'reg_alpha': 0.08604434725790536, 'reg_lambda': 2.35177029920263, 'max_delta_step': 2.8489183322834926, 'scale_pos_weight': 14.900195538574556, 'max_bin': 237}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:24,201] Trial 417 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0021466365868114154, 'min_split_gain': 2.3433881009413806, 'learning_rate': 0.005033942161794849, 'n_estimators': 494, 'subsample': 0.7970655856499729, 'subsample_freq': 5, 'colsample_bytree': 0.8914166941359795, 'reg_alpha': 0.15232090745221907, 'reg_lambda': 2.1576545286225284, 'max_delta_step': 2.6703576534085505, 'scale_pos_weight': 15.838129853394664, 'max_bin': 400}. Best is trial 365 with value: 0.46757692052242156.
[I 2026-01-30 15:28:24,737] Trial 418 finished with value: 0.43458585158453084 and parameters: {'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.002470086293539629, 'min_split_gain': 2.18492442809624, 'learning_rate': 0.006450410521442294, 'n_estimators': 464, 'subsample': 0.8104636065824312, 'subsample_freq': 5, 'colsample_bytree': 0.8667578013548574, 'reg_alpha': 0.06866081642958967, 'reg_lambda': 1.9133498388708785, 'max_delta_step': 3.052190460266647, 'scale_pos_weight': 15.445575884124748, 'max_bin': 279}. Best is trial 365 with value: 0.46757692052242156.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-30 15:28:45,361] Trial 450 finished with value: 0.0 and parameters: {'num_leaves': 99, 'max_depth': 8, 'min_child_samples': 33, 'min_child_weight': 0.0020577833289426844, 'min_split_gain': 1.9862724475585363, 'learning_rate': 0.005871809563174264, 'n_estimators': 145, 'subsample': 0.847427995671451, 'subsample_freq': 5, 'colsample_bytree': 0.8567896965847186, 'reg_alpha': 0.06130788406500791, 'reg_lambda': 2.563516193521104, 'max_delta_step': 3.0441051021478356, 'scale_pos_weight': 16.85903254906113, 'max_bin': 386}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:46,002] Trial 451 finished with value: 0.4253070012870013 and parameters: {'num_leaves': 92, 'max_depth': 7, 'min_child_samples': 29, 'min_child_weight': 0.0021994266546946336, 'min_split_gain': 1.9271190293311218, 'learning_rate': 0.006531520987790513, 'n_estimators': 477, 'subsample': 0.7680333839254299, 'subsample_freq': 5, 'colsample_bytree': 0.5930645991216087, 'reg_alpha': 0.1095951805531821, 'reg_lambda': 3.183300119052918, 'max_delta_step': 2.671913667632154, 'scale_pos_weight': 14.463964316231873, 'max_bin': 378}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:46,444] Trial 452 finished with value: 0.4386067577901155 and parameters: {'num_leaves': 100, 'max_depth': 6, 'min_child_samples': 31, 'min_child_weight': 0.02158308491742515, 'min_split_gain': 2.2533490302598342, 'learning_rate': 0.005945523153069982, 'n_estimators': 484, 'subsample': 0.7801494025766003, 'subsample_freq': 5, 'colsample_bytree': 0.8451328049209113, 'reg_alpha': 0.14451728406251685, 'reg_lambda': 1.9097411395568265, 'max_delta_step': 2.8672598069494057, 'scale_pos_weight': 15.822905166028358, 'max_bin': 332}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:47,133] Trial 453 finished with value: 0.446747286394816 and parameters: {'num_leaves': 96, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.050473224213248416, 'min_split_gain': 2.1247791661402196, 'learning_rate': 0.005325709722101177, 'n_estimators': 466, 'subsample': 0.800147883258329, 'subsample_freq': 5, 'colsample_bytree': 0.8297307801668726, 'reg_alpha': 0.08315339340285428, 'reg_lambda': 2.3637430424443724, 'max_delta_step': 3.1798625857124785, 'scale_pos_weight': 17.340177432792863, 'max_bin': 298}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:47,808] Trial 454 finished with value: 0.4378859790360703 and parameters: {'num_leaves': 105, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.02554279198129369, 'min_split_gain': 2.354079690744627, 'learning_rate': 0.006372248416385101, 'n_estimators': 458, 'subsample': 0.6218308899933036, 'subsample_freq': 5, 'colsample_bytree': 0.8446281072550472, 'reg_alpha': 0.10415937498425516, 'reg_lambda': 3.5499475377396648, 'max_delta_step': 2.972487858132765, 'scale_pos_weight': 14.04556935820812, 'max_bin': 304}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:48,457] Trial 455 finished with value: 0.45008886770256235 and parameters: {'num_leaves': 149, 'max_depth': 6, 'min_child_samples': 29, 'min_child_weight': 0.0034629420517615995, 'min_split_gain': 2.0384732399632197, 'learning_rate': 0.005708559050517474, 'n_estimators': 477, 'subsample': 0.8171017781930066, 'subsample_freq': 5, 'colsample_bytree': 0.8333148754222773, 'reg_alpha': 0.06303690772283466, 'reg_lambda': 1.783893328991897, 'max_delta_step': 3.2833830921416167, 'scale_pos_weight': 15.232712480022201, 'max_bin': 386}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:48,789] Trial 456 finished with value: 0.3064492733039162 and parameters: {'num_leaves': 107, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.002495940403737298, 'min_split_gain': 2.1651316336833277, 'learning_rate': 0.006229731520725238, 'n_estimators': 240, 'subsample': 0.7855834450931831, 'subsample_freq': 5, 'colsample_bytree': 0.8641549681964326, 'reg_alpha': 0.32771535282464564, 'reg_lambda': 2.846972865795132, 'max_delta_step': 2.545575570739569, 'scale_pos_weight': 14.740586936529688, 'max_bin': 393}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:49,771] Trial 457 finished with value: 0.3663419817577657 and parameters: {'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.0015882581204339848, 'min_split_gain': 2.317504491803422, 'learning_rate': 0.0052604384744383784, 'n_estimators': 451, 'subsample': 0.7733965658212173, 'subsample_freq': 5, 'colsample_bytree': 0.517143874693105, 'reg_alpha': 0.07747601460782512, 'reg_lambda': 2.0603722758046548, 'max_delta_step': 2.746962113063172, 'scale_pos_weight': 13.98573878537592, 'max_bin': 382}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:50,909] Trial 458 finished with value: 0.45348088860994523 and parameters: {'num_leaves': 106, 'max_depth': 7, 'min_child_samples': 41, 'min_child_weight': 0.0025155380519003836, 'min_split_gain': 1.9807576679520909, 'learning_rate': 0.006661739161019971, 'n_estimators': 485, 'subsample': 0.799417346740501, 'subsample_freq': 5, 'colsample_bytree': 0.8246111586896302, 'reg_alpha': 0.043916515128051434, 'reg_lambda': 0.41321642759495264, 'max_delta_step': 2.614151483600489, 'scale_pos_weight': 15.508429701610412, 'max_bin': 321}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:52,398] Trial 459 finished with value: 0.44984250125125125 and parameters: {'num_leaves': 114, 'max_depth': 8, 'min_child_samples': 30, 'min_child_weight': 0.042880981645639846, 'min_split_gain': 2.226157882231883, 'learning_rate': 0.005680493727535782, 'n_estimators': 471, 'subsample': 0.8105115779933745, 'subsample_freq': 5, 'colsample_bytree': 0.8821354888248395, 'reg_alpha': 0.11225664627642042, 'reg_lambda': 3.531634276454494, 'max_delta_step': 2.8297080433652533, 'scale_pos_weight': 14.380692202541145, 'max_bin': 391}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:52,663] Trial 460 finished with value: 0.3700267500214955 and parameters: {'num_leaves': 98, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0018174247771042702, 'min_split_gain': 2.0983416225609304, 'learning_rate': 0.1616065001612778, 'n_estimators': 462, 'subsample': 0.8308401740288663, 'subsample_freq': 6, 'colsample_bytree': 0.8501015351759321, 'reg_alpha': 0.054828018250240314, 'reg_lambda': 2.467344072745193, 'max_delta_step': 2.7251514421097074, 'scale_pos_weight': 14.912656550336315, 'max_bin': 317}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:53,260] Trial 461 finished with value: 0.4450950603062078 and parameters: {'num_leaves': 109, 'max_depth': 6, 'min_child_samples': 35, 'min_child_weight': 0.0052063232005574575, 'min_split_gain': 1.8948872771056324, 'learning_rate': 0.006195686463288301, 'n_estimators': 478, 'subsample': 0.7905230800416795, 'subsample_freq': 5, 'colsample_bytree': 0.8366127406544602, 'reg_alpha': 0.09751244221672027, 'reg_lambda': 1.642804032209252, 'max_delta_step': 2.9873574696353073, 'scale_pos_weight': 14.557268960554856, 'max_bin': 387}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:53,967] Trial 462 finished with value: 0.4395549368754049 and parameters: {'num_leaves': 102, 'max_depth': 7, 'min_child_samples': 32, 'min_child_weight': 0.003226115435808784, 'min_split_gain': 2.2714723767492417, 'learning_rate': 0.006855993746905864, 'n_estimators': 487, 'subsample': 0.7779912869719704, 'subsample_freq': 5, 'colsample_bytree': 0.8966974293840373, 'reg_alpha': 0.06957657192566334, 'reg_lambda': 2.9220850546651365, 'max_delta_step': 3.105834347634909, 'scale_pos_weight': 13.936938436869664, 'max_bin': 286}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:54,523] Trial 463 finished with value: 0.4450950603062078 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_child_samples': 34, 'min_child_weight': 0.0018972244691003938, 'min_split_gain': 2.159995850187698, 'learning_rate': 0.005332273431261183, 'n_estimators': 473, 'subsample': 0.7396897908266495, 'subsample_freq': 5, 'colsample_bytree': 0.8281654573344326, 'reg_alpha': 0.18704027973209914, 'reg_lambda': 3.9384379724094587, 'max_delta_step': 2.9009382291588808, 'scale_pos_weight': 16.038587300506283, 'max_bin': 392}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:55,312] Trial 464 finished with value: 0.3189811237603149 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 39, 'min_child_weight': 0.002126296088696205, 'min_split_gain': 2.0658806681419617, 'learning_rate': 0.005996219297351809, 'n_estimators': 486, 'subsample': 0.7679179217326333, 'subsample_freq': 5, 'colsample_bytree': 0.858491948795588, 'reg_alpha': 0.131491434094721, 'reg_lambda': 2.1375916789571283, 'max_delta_step': 3.037672902192463, 'scale_pos_weight': 7.227199816486442, 'max_bin': 400}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:56,032] Trial 465 finished with value: 0.446747286394816 and parameters: {'num_leaves': 108, 'max_depth': 8, 'min_child_samples': 37, 'min_child_weight': 0.001337223656478247, 'min_split_gain': 1.9585564054358566, 'learning_rate': 0.006565633777426132, 'n_estimators': 464, 'subsample': 0.8074301800029382, 'subsample_freq': 5, 'colsample_bytree': 0.8398282917106674, 'reg_alpha': 0.08486626308113072, 'reg_lambda': 3.0495878186691745, 'max_delta_step': 3.238721893326075, 'scale_pos_weight': 15.33508258725392, 'max_bin': 374}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:57,208] Trial 466 finished with value: 0.40912980545711886 and parameters: {'num_leaves': 94, 'max_depth': 7, 'min_child_samples': 31, 'min_child_weight': 0.03630879374309896, 'min_split_gain': 2.182873769725879, 'learning_rate': 0.007113748677433899, 'n_estimators': 453, 'subsample': 0.8215575996046406, 'subsample_freq': 5, 'colsample_bytree': 0.8232003276300845, 'reg_alpha': 0.0011086795674091845, 'reg_lambda': 0.28459309639121216, 'max_delta_step': 2.8058816912164524, 'scale_pos_weight': 14.94693483513532, 'max_bin': 383}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:58,237] Trial 467 finished with value: 0.433667536208025 and parameters: {'num_leaves': 111, 'max_depth': 7, 'min_child_samples': 36, 'min_child_weight': 0.002848547315186635, 'min_split_gain': 2.02776473628247, 'learning_rate': 0.005002407904815979, 'n_estimators': 479, 'subsample': 0.7966884358876206, 'subsample_freq': 5, 'colsample_bytree': 0.8452435015398011, 'reg_alpha': 0.0670135669126051, 'reg_lambda': 1.8804627787053134, 'max_delta_step': 2.72947753987273, 'scale_pos_weight': 14.346770769883026, 'max_bin': 339}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:58,864] Trial 468 finished with value: 0.4418270547207549 and parameters: {'num_leaves': 99, 'max_depth': 6, 'min_child_samples': 28, 'min_child_weight': 0.0024433215597576877, 'min_split_gain': 2.520557562865454, 'learning_rate': 0.00561668832547981, 'n_estimators': 492, 'subsample': 0.6710984431885372, 'subsample_freq': 5, 'colsample_bytree': 0.8162412352299052, 'reg_alpha': 0.1273730435736784, 'reg_lambda': 2.573864827629296, 'max_delta_step': 2.599411621832874, 'scale_pos_weight': 16.399057474909227, 'max_bin': 389}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:28:59,629] Trial 469 finished with value: 0.4137658086959828 and parameters: {'num_leaves': 106, 'max_depth': 7, 'min_child_samples': 40, 'min_child_weight': 0.004990715597071683, 'min_split_gain': 2.2982241829051917, 'learning_rate': 0.007961594964758682, 'n_estimators': 472, 'subsample': 0.7831651957367166, 'subsample_freq': 5, 'colsample_bytree': 0.8680873585584169, 'reg_alpha': 0.09682032378323535, 'reg_lambda': 0.10301717697760061, 'max_delta_step': 3.0971393459916654, 'scale_pos_weight': 12.107991376090208, 'max_bin': 394}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:00,199] Trial 470 finished with value: 0.4586660210873791 and parameters: {'num_leaves': 115, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0035260126389857686, 'min_split_gain': 2.369755478337098, 'learning_rate': 0.006475824011702271, 'n_estimators': 483, 'subsample': 0.7076025241513582, 'subsample_freq': 5, 'colsample_bytree': 0.8330496370428294, 'reg_alpha': 0.05265592172373555, 'reg_lambda': 1.5203872851056295, 'max_delta_step': 2.9716700001628293, 'scale_pos_weight': 15.659820961416015, 'max_bin': 291}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:01,051] Trial 471 finished with value: 0.4371046464871465 and parameters: {'num_leaves': 110, 'max_depth': 8, 'min_child_samples': 29, 'min_child_weight': 0.004277202341681558, 'min_split_gain': 2.1223233503886796, 'learning_rate': 0.005984492386361391, 'n_estimators': 500, 'subsample': 0.7509416814702088, 'subsample_freq': 4, 'colsample_bytree': 0.8530900801282648, 'reg_alpha': 0.07949468356780476, 'reg_lambda': 3.5104786931054712, 'max_delta_step': 2.8430396247448786, 'scale_pos_weight': 13.790829512415522, 'max_bin': 380}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:01,624] Trial 472 finished with value: 0.46757692052242156 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.0017015390890078204, 'min_split_gain': 2.2173500399714783, 'learning_rate': 0.007248243171909097, 'n_estimators': 466, 'subsample': 0.7699812016496085, 'subsample_freq': 5, 'colsample_bytree': 0.8061462541955456, 'reg_alpha': 0.15426289835602888, 'reg_lambda': 2.221545519419279, 'max_delta_step': 1.56229840585853, 'scale_pos_weight': 14.620088425852442, 'max_bin': 385}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:02,261] Trial 473 finished with value: 0.46757692052242156 and parameters: {'num_leaves': 114, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.0015565566815336643, 'min_split_gain': 2.2296846564646042, 'learning_rate': 0.0069605907370999505, 'n_estimators': 461, 'subsample': 0.7700442993847888, 'subsample_freq': 5, 'colsample_bytree': 0.8014451604457901, 'reg_alpha': 0.1648949191346451, 'reg_lambda': 2.222806032624673, 'max_delta_step': 1.551488114565923, 'scale_pos_weight': 14.6686521796075, 'max_bin': 377}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:02,648] Trial 474 finished with value: 0.3687322950498067 and parameters: {'num_leaves': 116, 'max_depth': 6, 'min_child_samples': 36, 'min_child_weight': 0.0014271273029943926, 'min_split_gain': 2.229656905057222, 'learning_rate': 0.03548171035682736, 'n_estimators': 451, 'subsample': 0.7701711983380779, 'subsample_freq': 5, 'colsample_bytree': 0.8036014207523731, 'reg_alpha': 0.17699168233513235, 'reg_lambda': 2.316685087441235, 'max_delta_step': 1.3942233822029946, 'scale_pos_weight': 14.6422976518062, 'max_bin': 372}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:03,087] Trial 475 finished with value: 0.41206527954855443 and parameters: {'num_leaves': 113, 'max_depth': 8, 'min_child_samples': 35, 'min_child_weight': 0.0011174807387698237, 'min_split_gain': 2.1127579626385904, 'learning_rate': 0.006957344830170341, 'n_estimators': 381, 'subsample': 0.7697589101585044, 'subsample_freq': 5, 'colsample_bytree': 0.8012690536706175, 'reg_alpha': 0.22501494353529788, 'reg_lambda': 2.496368116399754, 'max_delta_step': 1.6110867456053999, 'scale_pos_weight': 14.264493852533514, 'max_bin': 378}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:03,510] Trial 476 finished with value: 0.4604208874849827 and parameters: {'num_leaves': 114, 'max_depth': 7, 'min_child_samples': 38, 'min_child_weight': 0.0021744074883882397, 'min_split_gain': 2.241833214640876, 'learning_rate': 0.00738502076105092, 'n_estimators': 460, 'subsample': 0.7648662570645808, 'subsample_freq': 5, 'colsample_bytree': 0.8118567610444604, 'reg_alpha': 0.19505483423308803, 'reg_lambda': 2.9579089463718673, 'max_delta_step': 1.543494603226054, 'scale_pos_weight': 14.63046061554522, 'max_bin': 377}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:03,897] Trial 477 finished with value: 0.4551692666432666 and parameters: {'num_leaves': 116, 'max_depth': 7, 'min_child_samples': 37, 'min_child_weight': 0.0015189181522510602, 'min_split_gain': 1.925026033938976, 'learning_rate': 0.006926694870198777, 'n_estimators': 478, 'subsample': 0.7785947332270767, 'subsample_freq': 6, 'colsample_bytree': 0.8058676725671275, 'reg_alpha': 0.15572020056061078, 'reg_lambda': 2.101440229036259, 'max_delta_step': 1.4391173993140056, 'scale_pos_weight': 14.070225946187437, 'max_bin': 268}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:04,365] Trial 478 finished with value: 0.45519617215962044 and parameters: {'num_leaves': 113, 'max_depth': 7, 'min_child_samples': 35, 'min_child_weight': 0.0012228640081895382, 'min_split_gain': 2.0473821475828275, 'learning_rate': 0.006556960342110387, 'n_estimators': 489, 'subsample': 0.7624407667978196, 'subsample_freq': 5, 'colsample_bytree': 0.7926767151535067, 'reg_alpha': 0.13787299991244467, 'reg_lambda': 2.8112729040358255, 'max_delta_step': 1.4750986801549542, 'scale_pos_weight': 14.86482452598412, 'max_bin': 369}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:04,869] Trial 479 finished with value: 0.45519617215962044 and parameters: {'num_leaves': 117, 'max_depth': 7, 'min_child_samples': 33, 'min_child_weight': 0.0016022047179910569, 'min_split_gain': 2.1667119027058255, 'learning_rate': 0.007461840175512574, 'n_estimators': 469, 'subsample': 0.78521426829345, 'subsample_freq': 5, 'colsample_bytree': 0.8233754694579815, 'reg_alpha': 0.1427898741177808, 'reg_lambda': 3.801887633341429, 'max_delta_step': 1.6084784240449783, 'scale_pos_weight': 14.362286800802517, 'max_bin': 375}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:05,272] Trial 480 finished with value: 0.2794873594541397 and parameters: {'num_leaves': 109, 'max_depth': 6, 'min_child_samples': 39, 'min_child_weight': 0.001733320272189499, 'min_split_gain': 2.0222796464000914, 'learning_rate': 0.04683467496792936, 'n_estimators': 495, 'subsample': 0.7759469698554361, 'subsample_freq': 5, 'colsample_bytree': 0.8121330879221753, 'reg_alpha': 0.1658547550800562, 'reg_lambda': 2.063791144383276, 'max_delta_step': 1.5659455679629612, 'scale_pos_weight': 6.109935126190187, 'max_bin': 381}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:05,791] Trial 481 finished with value: 0.45160416331119463 and parameters: {'num_leaves': 111, 'max_depth': 8, 'min_child_samples': 37, 'min_child_weight': 0.0018292387264834497, 'min_split_gain': 2.284270344351304, 'learning_rate': 0.007027732757999395, 'n_estimators': 481, 'subsample': 0.7573239654838698, 'subsample_freq': 5, 'colsample_bytree': 0.7975716674318317, 'reg_alpha': 0.19868677170460625, 'reg_lambda': 2.5198477099296914, 'max_delta_step': 1.614592951453623, 'scale_pos_weight': 13.842804721304514, 'max_bin': 384}. Best is trial 445 with value: 0.4694008708708709.
[I 2026-01-30 15:29:06,283] Trial 482 finished with value: 0.4402110082090882 and parameters: {'num_leaves': 114, 'max_depth': 7, 'min_child_samples': 41, 'min_child_weight': 0.001386515954855008, 'min_split_gain': 2.12912012331898, 'learning_rate': 0.007745250693858313, 'n_estimators': 457, 'subsample': 0.6586410816230922, 'subsample_freq': 5, 'colsample_bytree': 0.7842753123960349, 'reg_alpha': 0.28908450519160184, 'reg_lambda': 3.2176436147931, 'max_delta_step': 1.502913833015703, 'scale_pos_weight': 15.2130251057514, 'max_bin': 384}. Best is trial 445 with value: 0.4694008708708709.

In [66]:
# best_params_lgbm = grid_lgbm.best_params_

In [67]:
best_params_lgbm = study_lgbm.best_params

In [68]:
print(best_params_lgbm)

{'num_leaves': 118, 'max_depth': 8, 'min_child_samples': 34, 'min_child_weight': 0.0019900294648756926, 'min_split_gain': 2.0411153790841694, 'learning_rate': 0.006957001076177289, 'n_estimators': 495, 'subsample': 0.7708065302692244, 'subsample_freq': 5, 'colsample_bytree': 0.7646621089769187, 'reg_alpha': 0.11567144028375737, 'reg_lambda': 2.91568675362154, 'max_delta_step': 1.7246538927085886, 'scale_pos_weight': 13.54579054162353, 'max_bin': 373}

In [69]:
final_classifier = lgb.LGBMClassifier(**best_params_lgbm, random_state=42, verbose=-1)

In [70]:
final_classifier.fit(X_train_retained, y_train)

LGBMClassifier(colsample_bytree=0.7646621089769187,
               learning_rate=0.006957001076177289, max_bin=373,
               max_delta_step=1.7246538927085886, max_depth=8,
               min_child_samples=34, min_child_weight=0.0019900294648756926,
               min_split_gain=2.0411153790841694, n_estimators=495,
               num_leaves=118, random_state=42, reg_alpha=0.11567144028375737,
               reg_lambda=2.91568675362154, scale_pos_weight=13.54579054162353,
               subsample=0.7708065302692244, subsample_freq=5, verbose=-1)

In [71]:
y_pred_val = final_classifier.predict(X_val_retained)

In [72]:
y_proba_val = final_classifier.predict_proba(X_val_retained)[:, 1]

In [73]:
print(confusion_matrix(y_val, y_pred_val))

[[647  82]
 [ 13  24]]

In [74]:
print(accuracy_score(y_val, y_pred_val))

0.8759791122715405

In [75]:
print(precision_score(y_val, y_pred_val))

0.22641509433962265

In [76]:
print(recall_score(y_val, y_pred_val))

0.6486486486486487

In [77]:
print(fbeta_score(y_val, y_pred_val, beta=2))

0.47244094488188976

### Threshold tuning

In [78]:
best_threshold = 0.5

In [79]:
best_precision_score = 0

In [80]:
best_recall_score = 0

In [81]:
best_f2_score = 0

In [82]:
for threshold in np.arange(0.1, 0.95, 0.05):
    y_pred_val_threshold = (y_proba_val >= threshold).astype(int)
    recall = recall_score(y_val, y_pred_val_threshold)
    precision = precision_score(y_val, y_pred_val_threshold)
    f2_score = fbeta_score(y_val, y_pred_val_threshold, beta=2)
    
    print(f'Threshold {threshold} has F2 score {f2_score}')
    
    if precision >= 0.15:
        current_recall_score = recall
        if current_recall_score > best_recall_score:
            best_recall_score = current_recall_score
            best_precision_score = precision
            best_threshold = threshold
        elif current_recall_score == best_recall_score and precision > best_precision_score:
            best_precision_score = precision
            best_threshold = threshold
        
        # current_f2_score = f2_score
        # if current_f2_score > best_f2_score:
        #     best_f2_score = current_f2_score
        #     best_threshold = threshold

Threshold 0.1 has F2 score 0.34232365145228216
Threshold 0.15000000000000002 has F2 score 0.3611738148984199
Threshold 0.20000000000000004 has F2 score 0.3864734299516908
Threshold 0.25000000000000006 has F2 score 0.3875968992248062
Threshold 0.30000000000000004 has F2 score 0.3977272727272727
Threshold 0.3500000000000001 has F2 score 0.38922155688622756
Threshold 0.40000000000000013 has F2 score 0.4139072847682119
Threshold 0.45000000000000007 has F2 score 0.43956043956043955
Threshold 0.5000000000000001 has F2 score 0.47244094488188976
Threshold 0.5500000000000002 has F2 score 0.3879310344827586
Threshold 0.6000000000000002 has F2 score 0.35714285714285715
Threshold 0.6500000000000001 has F2 score 0.31088082901554404
Threshold 0.7000000000000002 has F2 score 0.2023121387283237
Threshold 0.7500000000000002 has F2 score 0.09554140127388536
Threshold 0.8000000000000002 has F2 score 0.0
Threshold 0.8500000000000002 has F2 score 0.0
Threshold 0.9000000000000002 has F2 score 0.0

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [83]:
print(best_threshold)

0.40000000000000013

In [84]:
print(best_recall_score)

0.6756756756756757

### Retrain on training + validation set

In [85]:
X_train_full = pd.concat([X_train_retained, X_val_retained], axis=0, ignore_index=True)
y_train_full = pd.concat([y_train, y_val], axis=0, ignore_index=True)

In [86]:
final_classifier.fit(X_train_full, y_train_full)

LGBMClassifier(colsample_bytree=0.7646621089769187,
               learning_rate=0.006957001076177289, max_bin=373,
               max_delta_step=1.7246538927085886, max_depth=8,
               min_child_samples=34, min_child_weight=0.0019900294648756926,
               min_split_gain=2.0411153790841694, n_estimators=495,
               num_leaves=118, random_state=42, reg_alpha=0.11567144028375737,
               reg_lambda=2.91568675362154, scale_pos_weight=13.54579054162353,
               subsample=0.7708065302692244, subsample_freq=5, verbose=-1)

### Evaluate on test set

In [87]:
X_test_retained = X_test[retained_columns]

In [88]:
y_pred_test = final_classifier.predict(X_test_retained)

In [89]:
y_proba_test = final_classifier.predict_proba(X_test_retained)[:, 1]

In [90]:
print(confusion_matrix(y_test, y_pred_test))

[[633  96]
 [ 11  27]]

In [91]:
print(accuracy_score(y_test, y_pred_test))

0.8604954367666232

In [92]:
print(precision_score(y_test, y_pred_test))

0.21951219512195122

In [93]:
print(recall_score(y_test, y_pred_test))

0.7105263157894737

In [94]:
print(fbeta_score(y_test, y_pred_test, beta=2))

0.4909090909090909

### Test with best threshold 0.55

In [95]:
y_pred_test_threshold = (y_proba_test >= best_threshold).astype(int)

In [96]:
print(confusion_matrix(y_test, y_pred_test_threshold))

[[597 132]
 [  9  29]]

In [97]:
print(accuracy_score(y_test, y_pred_test_threshold))

0.8161668839634941

In [98]:
print(precision_score(y_test, y_pred_test_threshold))

0.18012422360248448

In [99]:
print(recall_score(y_test, y_pred_test_threshold))

0.7631578947368421

In [100]:
print(fbeta_score(y_test, y_pred_test_threshold, beta=2))

0.46325878594249204

In [101]:
importances_final = final_classifier.feature_importances_

In [102]:
feature_imp_df_final = pd.DataFrame({'Feature':[col for col in X_train[retained_columns]], 'Importance': importances_final}).sort_values(
    'Importance', ascending=False)

In [103]:
print(feature_imp_df_final)

                       Feature  Importance
2                          bmi        3414
0            avg_glucose_level        2735
1                          age        2363
3             age_ever_married        1146
5                 hypertension         147
8                        smoke         108
9  smoking_status_never_smoked          91
7      work_type_self_employed          79
6                         male          17
4                        urban          10