# Stroke Prediction

## Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from imblearn.under_sampling import TomekLinks
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
import optuna
from optuna.samplers import TPESampler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, fbeta_score, make_scorer

## Import dataset

In [2]:
df = pd.read_csv('../dataset/healthcare-dataset-stroke-data.csv')

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [5]:
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [6]:
df.describe(include=[object])

        gender ever_married work_type Residence_type smoking_status
count     5110         5110      5110           5110           5110
unique       3            2         5              2              4
top     Female          Yes   Private          Urban   never smoked
freq      2994         3353      2925           2596           1892

## Rename column for consistent formatting of name

In [7]:
df.rename(columns={'Residence_type': 'residence_type'}, inplace=True)

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
pd.set_option('display.max_rows', None)

### Impute missing values in BMI column
For 201 entries missing BMI values, these entries will be imputed with the median BMI value

In [10]:
median_bmi = df['bmi'].median()
df['bmi'].fillna(median_bmi, inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7112\2337012406.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bmi'].fillna(median_bmi, inplace=True)

In [11]:
print(df['bmi'].isna().sum())

0

## Feature Engineering

### Converting categorical columns to numerical columns

In [12]:
df['male'] = (df['gender'] == 'Male').astype(int)

In [13]:
df['ever_married'] = (df['ever_married'] == 'Yes').astype(int)

In [14]:
df['urban'] = (df['residence_type'] == 'Urban').astype(int)

In [15]:
df['smoke'] = ((df['smoking_status'] == 'formerly smoked') | (df['smoking_status'] == 'smokes')).astype(int)

In [16]:
df['have_work'] = ((df['work_type'] == 'Govt_job') | (df['work_type'] == 'Private') | (df['work_type'] == 'Self-employed')).astype(int)

In [17]:
df['hypertension_or_heart_disease'] = df['hypertension'] | df['heart_disease']

In [18]:
df = pd.get_dummies(df, columns=['work_type', 'smoking_status'], drop_first = False)

### Extra column for the age of married people

In [19]:
df['age_ever_married'] = df['age'] * df['ever_married']

In [20]:
df['age_hypertension'] = df['age'] * df['hypertension']

In [21]:
df['age_heart_disease'] = df['age'] * df['heart_disease']

In [22]:
df['age_bmi'] = df['age'] * df['bmi']

In [23]:
df['age_avg_glucose_level'] = df['age'] * df['avg_glucose_level']

In [24]:
df['bmi_avg_glucose_level'] = df['bmi'] * df['avg_glucose_level']

In [25]:
df['avg_glucose_level_hypertension'] = df['avg_glucose_level'] * df['hypertension']

### Creating columns representing outstanding values for BMI and Average Glucose Level

In [26]:
df['obese'] = df['bmi'] >= 30

In [27]:
df['high_avg_glucose_level'] = df['avg_glucose_level'] >= 150

In [28]:
df['obese_high_avg_glucose_level'] = df['obese'] | df['high_avg_glucose_level']

In [29]:
df['old'] = df['age'] >= 65

### Converting boolean columns to numerical

In [30]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [31]:
df['risk_count'] = df['obese'] + df['high_avg_glucose_level'] + df['old'] + df['hypertension'] + df['heart_disease']

### Reformatting column names

In [32]:
df.rename(columns={'work_type_Govt_job': 'work_type_govt_job', 'work_type_Never_worked': 'work_type_never_worked', 'work_type_Private': 'work_type_private', 'work_type_Self-employed': 'work_type_self_employed'}, inplace=True)

In [33]:
df.rename(columns={'smoking_status_Unknown': 'smoking_status_unknown', 'smoking_status_formerly smoked': 'smoking_status_formerly_smoked', 'smoking_status_never smoked': 'smoking_status_never_smoked'}, inplace=True)

In [34]:
df.drop(columns=['gender', 'residence_type'], inplace=True)

### Log Transforming BMI and Average Glucose Level columns

In [35]:
df['log_bmi'] = np.log(df['bmi'])

In [36]:
df['log_avg_glucose_level'] = np.log(df['avg_glucose_level'])

In [37]:
df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,male,urban,smoke,have_work,hypertension_or_heart_disease,work_type_govt_job,work_type_never_worked,work_type_private,work_type_self_employed,work_type_children,smoking_status_unknown,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,age_ever_married,age_hypertension,age_heart_disease,age_bmi,age_avg_glucose_level,bmi_avg_glucose_level,avg_glucose_level_hypertension,obese,high_avg_glucose_level,obese_high_avg_glucose_level,old,risk_count,log_bmi,log_avg_glucose_level
0,9046,67.0,0,1,1,228.69,36.6,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,67.0,0.0,67.0,2452.2,15322.23,8370.054,0.00,1,1,1,1,4,3.600048,5.432367
1,51676,61.0,0,0,1,202.21,28.1,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,61.0,0.0,0.0,1714.1,12334.81,5682.101,0.00,0,1,1,0,1,3.335770,5.309307
2,31112,80.0,0,1,1,105.92,32.5,1,1,0,0,1,1,0,0,1,0,0,0,0,1,0,80.0,0.0,80.0,2600.0,8473.60,3442.400,0.00,1,0,1,1,3,3.481240,4.662684
3,60182,49.0,0,0,1,171.23,34.4,1,0,1,1,1,0,0,0,1,0,0,0,0,0,1,49.0,0.0,0.0,1685.6,8390.27,5890.312,0.00,1,1,1,0,2,3.538057,5.143008
4,1665,79.0,1,0,1,174.12,24.0,1,0,0,0,1,1,0,0,0,1,0,0,0,1,0,79.0,79.0,0.0,1896.0,13755.48,4178.880,174.12,0,1,1,1,3,3.178054,5.159745

In [38]:
df.shape

(5110, 36)

## Model Building

### Splitting to training, validation, and testing sets

In [39]:
columns_name = columns_name = [col for col in df.columns if col != 'id']

In [40]:
X = df[columns_name]
X.drop('stroke', axis=1, inplace=True)
y = df['stroke']

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7112\91966498.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('stroke', axis=1, inplace=True)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify = y)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size = 0.5, random_state = 42, stratify = y_test)

### ADASYN Oversampling on Training Data

In [42]:
resampler = TomekLinks()

In [43]:
X_train_res, y_train_res = resampler.fit_resample(X_train, y_train)

### Create base random forest classifier model

In [44]:
base_classifier = xgb.XGBClassifier(random_state=42, eval_metric='logloss')

### Create grid for hyperparameter tuning

In [45]:
param_grid_xgb = {
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [50, 100, 200],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'scale_pos_weight': [1, 3, 5, 10, 15, 20]
}

In [46]:
f2_scorer = make_scorer(fbeta_score, beta=2)

In [47]:
grid_xgb = GridSearchCV(
    estimator=base_classifier,
    param_grid=param_grid_xgb,
    scoring=f2_scorer,
    cv=5,
    verbose=2,
    n_jobs=-1
)

In [48]:
# importance_df = pd.DataFrame({'Feature': X_train_res.columns, 'Importance': base_classifier.feature_importances_})
# importance_df = importance_df.sort_values(by='Importance', ascending=False)
# print(importance_df)

### Fitting base classifier on unsampled data

In [49]:
base_classifier.fit(X_train_res, y_train_res)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [50]:
importances = base_classifier.feature_importances_

In [51]:
feature_imp_df = pd.DataFrame({'Feature':[col for col in X_train], 'Importance': importances}).sort_values(
    'Importance', ascending=False)

In [52]:
print(feature_imp_df)

                           Feature  Importance
0                              age    0.100594
2                    heart_disease    0.092366
3                     ever_married    0.074564
23                         age_bmi    0.058238
10   hypertension_or_heart_disease    0.046116
21                age_hypertension    0.045385
19           smoking_status_smokes    0.043820
20                age_ever_married    0.042206
11              work_type_govt_job    0.042125
18     smoking_status_never_smoked    0.038685
5                              bmi    0.037237
14         work_type_self_employed    0.035073
4                avg_glucose_level    0.031637
29    obese_high_avg_glucose_level    0.031068
31                      risk_count    0.028246
17  smoking_status_formerly_smoked    0.027801
24           age_avg_glucose_level    0.027561
16          smoking_status_unknown    0.027519
25           bmi_avg_glucose_level    0.026254
26  avg_glucose_level_hypertension    0.025215
6                             male    0.025004
13               work_type_private    0.021478
7                            urban    0.020922
22               age_heart_disease    0.019913
8                            smoke    0.015354
28          high_avg_glucose_level    0.010178
1                     hypertension    0.005443
12          work_type_never_worked    0.000000
9                        have_work    0.000000
15              work_type_children    0.000000
27                           obese    0.000000
30                             old    0.000000
32                         log_bmi    0.000000
33           log_avg_glucose_level    0.000000

In [53]:
# retained_columns = ['age', 'heart_disease', 'ever_married', 'age_bmi', 'hypertension_or_heart_disease', 'age_hypertension', 'smoking_status_smokes', 'age_ever_married', 'work_type_govt_job']

In [54]:
retained_columns = ['age', 'heart_disease', 'ever_married', 'age_bmi', 'hypertension_or_heart_disease', 'age_hypertension', 'smoking_status_smokes', 'age_ever_married', 'work_type_govt_job', 'smoking_status_never_smoked']

In [55]:
# retained_columns = ['age', 'hypertension_or_heart_disease', 'work_type_govt_job', 'smoking_status_formerly_smoked', 'smoking_status_unknown', 'bmi', 'work_type_self_employed', 'smoking_status_smokes', 'avg_glucose_level', 'smoking_status_never_smoked']

In [56]:
X_train_res_retained = X_train_res[retained_columns]

In [57]:
X_val_retained = X_val[retained_columns]

### Create optimizing function for hyperparameter tuning with Optuna

In [58]:
MIN_PRECISION = 0.2

In [59]:
def objective_xgb(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'max_delta_step': trial.suggest_int('max_delta_step', 0, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.4, 1.0),
        'colsample_bynode': trial.suggest_float('colsample_bynode', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 10),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 10),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1, 20),
        'tree_method': trial.suggest_categorical('tree_method', ['hist', 'approx']), 
        'grow_policy': trial.suggest_categorical('grow_policy', ['depthwise', 'lossguide']),  
        'max_leaves': trial.suggest_int('max_leaves', 0, 256),
        'min_split_loss': trial.suggest_float('min_split_loss', 0, 5),  
        'max_bin': trial.suggest_int('max_bin', 128, 512),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    
    model = xgb.XGBClassifier(**params)
    
    model.fit(X_train_res_retained, y_train_res)
    
    y_pred_val = model.predict(X_val_retained)
    
    recall = recall_score(y_val, y_pred_val)
    precision = precision_score(y_val, y_pred_val)
    f2_score = fbeta_score(y_val, y_pred_val, beta=2)
    
    if precision < MIN_PRECISION:
        return 0
    # return recall + (precision * 0.01)
    return f2_score + recall * 0.001 + precision * 0.00001

In [60]:
# grid_xgb.fit(X_train_res_retained, y_train_res)

In [61]:
study_xgb = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
study_xgb.optimize(objective_xgb, n_trials=500, show_progress_bar=True)

[I 2026-01-22 14:57:35,841] A new study created in memory with name: no-name-66511d04-6672-498e-a079-2a1b73b11168

  0%|          | 0/500 [00:00<?, ?it/s]

[I 2026-01-22 14:57:37,141] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.24517932047070642, 'n_estimators': 380, 'min_child_weight': 6, 'max_delta_step': 1, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.4348501673009197, 'colsample_bylevel': 0.9197056874649611, 'colsample_bynode': 0.7606690070459252, 'gamma': 3.540362888980227, 'reg_alpha': 0.20584494295802447, 'reg_lambda': 9.699098521619943, 'scale_pos_weight': 16.816410175208013, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 134, 'min_split_loss': 2.1597250932105787, 'max_bin': 240}. Best is trial 0 with value: 0.0.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:57:38,174] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.008851384099881301, 'n_estimators': 181, 'min_child_weight': 4, 'max_delta_step': 5, 'subsample': 0.8925879806965068, 'colsample_bytree': 0.5198042692950159, 'colsample_bylevel': 0.708540663048167, 'colsample_bynode': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 6.075448519014383, 'reg_lambda': 1.7052412368729153, 'scale_pos_weight': 2.235980266720311, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 25, 'min_split_loss': 3.4211651325607844, 'max_bin': 297}. Best is trial 0 with value: 0.0.
[I 2026-01-22 14:57:38,337] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.03797252233376349, 'n_estimators': 65, 'min_child_weight': 10, 'max_delta_step': 2, 'subsample': 0.831261142176991, 'colsample_bytree': 0.5870266456536466, 'colsample_bylevel': 0.7120408127066865, 'colsample_bynode': 0.7280261676059678, 'gamma': 0.9242722776276352, 'reg_alpha': 9.695846277645586, 'reg_lambda': 7.7513282336111455, 'scale_pos_weight': 18.850479889719594, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 50, 'min_split_loss': 0.22613644455269033, 'max_bin': 253}. Best is trial 0 with value: 0.0.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:57:38,865] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.015186917176306207, 'n_estimators': 423, 'min_child_weight': 4, 'max_delta_step': 3, 'subsample': 0.7713480415791243, 'colsample_bytree': 0.4845545349848576, 'colsample_bylevel': 0.8813181884524238, 'colsample_bynode': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 7.722447692966574, 'reg_lambda': 1.987156815341724, 'scale_pos_weight': 1.1049202253484456, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 19, 'min_split_loss': 1.7923286427213632, 'max_bin': 172}. Best is trial 0 with value: 0.0.
[I 2026-01-22 14:57:42,305] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.06416354462323627, 'n_estimators': 199, 'min_child_weight': 1, 'max_delta_step': 3, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.8377637070028385, 'colsample_bylevel': 0.7825344828131279, 'colsample_bynode': 0.932327645545796, 'gamma': 2.3610746258097466, 'reg_alpha': 1.195942459383017, 'reg_lambda': 7.13244787222995, 'scale_pos_weight': 15.454915923721051, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 109, 'min_split_loss': 0.12709563372047594, 'max_bin': 169}. Best is trial 0 with value: 0.0.
[I 2026-01-22 14:57:42,619] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.0677023857369087, 'n_estimators': 191, 'min_child_weight': 6, 'max_delta_step': 9, 'subsample': 0.6246461145744375, 'colsample_bytree': 0.6462297538213778, 'colsample_bylevel': 0.8533306831258292, 'colsample_bynode': 0.5372788992949735, 'gamma': 0.38489954914396496, 'reg_alpha': 2.8975145291376805, 'reg_lambda': 1.6122128725400442, 'scale_pos_weight': 18.66425539450889, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 47, 'min_split_loss': 4.462794992449889, 'max_bin': 335}. Best is trial 0 with value: 0.0.
[I 2026-01-22 14:57:43,667] Trial 6 finished with value: 0.2036804779488791 and parameters: {'max_depth': 13, 'learning_rate': 0.19604504485810242, 'n_estimators': 193, 'min_child_weight': 2, 'max_delta_step': 2, 'subsample': 0.7135538943131281, 'colsample_bytree': 0.8908088595534959, 'colsample_bylevel': 0.916438349953806, 'colsample_bynode': 0.40417127831871447, 'gamma': 2.553736512887829, 'reg_alpha': 4.17411003148779, 'reg_lambda': 2.2210781047073027, 'scale_pos_weight': 3.277441979339973, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 180, 'min_split_loss': 1.81814801189647, 'max_bin': 502}. Best is trial 6 with value: 0.2036804779488791.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:57:44,808] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.014017707981920842, 'n_estimators': 274, 'min_child_weight': 4, 'max_delta_step': 3, 'subsample': 0.5184434736772664, 'colsample_bytree': 0.7657386003879381, 'colsample_bylevel': 0.701607413937317, 'colsample_bynode': 0.4308872507499936, 'gamma': 1.3932323211830573, 'reg_alpha': 9.082658859666537, 'reg_lambda': 2.395618906669724, 'scale_pos_weight': 3.7530025697332388, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 195, 'min_split_loss': 1.1881877199619983, 'max_bin': 408}. Best is trial 6 with value: 0.2036804779488791.
[I 2026-01-22 14:57:46,891] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.06657411588229807, 'n_estimators': 335, 'min_child_weight': 6, 'max_delta_step': 0, 'subsample': 0.917651247794619, 'colsample_bytree': 0.5924680389830415, 'colsample_bylevel': 0.5119111062399125, 'colsample_bynode': 0.4244650849328584, 'gamma': 2.954464715941209, 'reg_alpha': 6.775643618422825, 'reg_lambda': 0.16587828927856152, 'scale_pos_weight': 10.729768107686338, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 99, 'min_split_loss': 4.6836499436836725, 'max_bin': 180}. Best is trial 6 with value: 0.2036804779488791.
[I 2026-01-22 14:57:50,054] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.00795688512312417, 'n_estimators': 467, 'min_child_weight': 9, 'max_delta_step': 2, 'subsample': 0.8299920230170895, 'colsample_bytree': 0.8903333201207295, 'colsample_bylevel': 0.7331204869596775, 'colsample_bynode': 0.7177903470136039, 'gamma': 1.2092614545022584, 'reg_alpha': 0.9310276780589921, 'reg_lambda': 8.972157579533267, 'scale_pos_weight': 18.10794308610328, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 230, 'min_split_loss': 4.4354321213255865, 'max_bin': 428}. Best is trial 6 with value: 0.2036804779488791.
[I 2026-01-22 14:57:50,442] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.22767246707533523, 'n_estimators': 53, 'min_child_weight': 1, 'max_delta_step': 9, 'subsample': 0.71318415356318, 'colsample_bytree': 0.9820282966949807, 'colsample_bylevel': 0.9856172116162216, 'colsample_bynode': 0.5689638013591753, 'gamma': 4.174743509527138, 'reg_alpha': 3.8614380812971323, 'reg_lambda': 4.399492045282824, 'scale_pos_weight': 6.52441096075992, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 174, 'min_split_loss': 3.035921370166128, 'max_bin': 512}. Best is trial 6 with value: 0.2036804779488791.
[I 2026-01-22 14:57:51,752] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.26390876750252223, 'n_estimators': 370, 'min_child_weight': 8, 'max_delta_step': 0, 'subsample': 0.5431844609096353, 'colsample_bytree': 0.7237720640816786, 'colsample_bylevel': 0.9940209692622792, 'colsample_bynode': 0.8755852659446967, 'gamma': 3.223972680035051, 'reg_alpha': 2.665234272933838, 'reg_lambda': 5.149704140209431, 'scale_pos_weight': 11.723030240978208, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 159, 'min_split_loss': 2.050763483630553, 'max_bin': 512}. Best is trial 6 with value: 0.2036804779488791.
[I 2026-01-22 14:57:53,488] Trial 12 finished with value: 0.39634891206423817 and parameters: {'max_depth': 5, 'learning_rate': 0.1587065708222648, 'n_estimators': 279, 'min_child_weight': 3, 'max_delta_step': 6, 'subsample': 0.6043567480669064, 'colsample_bytree': 0.422269694973986, 'colsample_bylevel': 0.5765449602657398, 'colsample_bynode': 0.8280321953052779, 'gamma': 2.127947321819143, 'reg_alpha': 0.17731545149565042, 'reg_lambda': 9.692698520487179, 'scale_pos_weight': 6.180434464317176, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 251, 'min_split_loss': 1.0411231888035033, 'max_bin': 248}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:57:55,212] Trial 13 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.1290911676711121, 'n_estimators': 268, 'min_child_weight': 2, 'max_delta_step': 6, 'subsample': 0.711685652216894, 'colsample_bytree': 0.9893759587550995, 'colsample_bylevel': 0.5590992294063204, 'colsample_bynode': 0.8621369837791616, 'gamma': 2.130301494618079, 'reg_alpha': 4.4874731208455865, 'reg_lambda': 4.4614504207489585, 'scale_pos_weight': 6.366789439030172, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 246, 'min_split_loss': 1.255773118034989, 'max_bin': 375}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:57:56,262] Trial 14 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.13005985344196086, 'n_estimators': 132, 'min_child_weight': 3, 'max_delta_step': 6, 'subsample': 0.6167523913002275, 'colsample_bytree': 0.4038729055141265, 'colsample_bylevel': 0.5911287338308573, 'colsample_bynode': 0.5988830848779871, 'gamma': 1.8682610458078774, 'reg_alpha': 2.338121643384345, 'reg_lambda': 6.0435815433706015, 'scale_pos_weight': 6.719579373180074, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 208, 'min_split_loss': 0.9558390733655346, 'max_bin': 246}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:57:58,094] Trial 15 finished with value: 0.35755068190310124 and parameters: {'max_depth': 9, 'learning_rate': 0.10524842686872334, 'n_estimators': 308, 'min_child_weight': 3, 'max_delta_step': 5, 'subsample': 0.7715675923561651, 'colsample_bytree': 0.8188579840032407, 'colsample_bylevel': 0.40697257697653194, 'colsample_bynode': 0.9963056710298251, 'gamma': 3.8761413958380198, 'reg_alpha': 5.727866197109666, 'reg_lambda': 3.0673521336766596, 'scale_pos_weight': 4.463971746961704, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 249, 'min_split_loss': 2.883553131939835, 'max_bin': 444}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:57:59,539] Trial 16 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.03434179310927581, 'n_estimators': 313, 'min_child_weight': 3, 'max_delta_step': 7, 'subsample': 0.9756357791297634, 'colsample_bytree': 0.7993118582045715, 'colsample_bylevel': 0.405408878966044, 'colsample_bynode': 0.9822278829410831, 'gamma': 4.001209257706107, 'reg_alpha': 5.620404333428747, 'reg_lambda': 3.740742945092843, 'scale_pos_weight': 8.782557644193702, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 255, 'min_split_loss': 3.0273458016441124, 'max_bin': 444}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:58:00,721] Trial 17 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.11417677129061464, 'n_estimators': 246, 'min_child_weight': 5, 'max_delta_step': 5, 'subsample': 0.77996629401445, 'colsample_bytree': 0.6648792642624308, 'colsample_bylevel': 0.41048535862072694, 'colsample_bynode': 0.8402197031903924, 'gamma': 4.943351396596474, 'reg_alpha': 7.262499415468587, 'reg_lambda': 6.152944014142948, 'scale_pos_weight': 13.905011953124527, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 216, 'min_split_loss': 3.71987169315204, 'max_bin': 314}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:58:02,366] Trial 18 finished with value: 0.38878470561622885 and parameters: {'max_depth': 5, 'learning_rate': 0.10300540957522757, 'n_estimators': 313, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.6490454165086229, 'colsample_bytree': 0.7252772202318978, 'colsample_bylevel': 0.4886703550166033, 'colsample_bynode': 0.969373071821104, 'gamma': 3.998351200135164, 'reg_alpha': 8.413630686801335, 'reg_lambda': 3.388198253944107, 'scale_pos_weight': 4.522626301934825, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 147, 'min_split_loss': 2.6037399538355395, 'max_bin': 362}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:58:04,589] Trial 19 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.022113467285250165, 'n_estimators': 493, 'min_child_weight': 8, 'max_delta_step': 10, 'subsample': 0.653387090130186, 'colsample_bytree': 0.5857883088616178, 'colsample_bylevel': 0.6101594922612368, 'colsample_bynode': 0.8073581756019891, 'gamma': 2.81361283892075, 'reg_alpha': 8.269331018230982, 'reg_lambda': 8.137383455721935, 'scale_pos_weight': 8.783110767527303, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 142, 'min_split_loss': 0.8266504750507407, 'max_bin': 359}. Best is trial 12 with value: 0.39634891206423817.
[I 2026-01-22 14:58:06,300] Trial 20 finished with value: 0.3987188826743694 and parameters: {'max_depth': 3, 'learning_rate': 0.08245447077264163, 'n_estimators': 395, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.5668108627043664, 'colsample_bytree': 0.7112319742835451, 'colsample_bylevel': 0.4867113012604595, 'colsample_bynode': 0.6495945092353627, 'gamma': 1.7645676462323436, 'reg_alpha': 8.61737643999649, 'reg_lambda': 0.2535659843942675, 'scale_pos_weight': 5.212740039100449, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 80, 'min_split_loss': 2.384358080293545, 'max_bin': 130}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:07,717] Trial 21 finished with value: 0.3921669923519994 and parameters: {'max_depth': 3, 'learning_rate': 0.08301665141958046, 'n_estimators': 414, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.5941601258791622, 'colsample_bytree': 0.7216227230678939, 'colsample_bylevel': 0.49209384197680045, 'colsample_bynode': 0.6407831815129189, 'gamma': 1.6757066023594405, 'reg_alpha': 8.42697601884212, 'reg_lambda': 0.23756287047009006, 'scale_pos_weight': 5.061273014871269, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 98, 'min_split_loss': 2.5443651138090875, 'max_bin': 128}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:08,969] Trial 22 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.06004551933490784, 'n_estimators': 426, 'min_child_weight': 7, 'max_delta_step': 7, 'subsample': 0.5669427491660636, 'colsample_bytree': 0.6746039546839809, 'colsample_bylevel': 0.48927837746512776, 'colsample_bynode': 0.6552921222166395, 'gamma': 1.7499753910635574, 'reg_alpha': 9.577316973869694, 'reg_lambda': 0.15143024241352102, 'scale_pos_weight': 8.435514348524146, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 83, 'min_split_loss': 3.7699939943093685, 'max_bin': 130}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:10,210] Trial 23 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.1439600863315458, 'n_estimators': 412, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.5095574167225442, 'colsample_bytree': 0.761686136242647, 'colsample_bylevel': 0.635072394187544, 'colsample_bynode': 0.6625300875780012, 'gamma': 0.792653585426062, 'reg_alpha': 6.633711115802345, 'reg_lambda': 1.0175465673498674, 'scale_pos_weight': 6.392035725563907, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 72, 'min_split_loss': 2.4124444921443335, 'max_bin': 130}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:12,283] Trial 24 finished with value: 0.35757739483844747 and parameters: {'max_depth': 4, 'learning_rate': 0.08368344732462576, 'n_estimators': 361, 'min_child_weight': 5, 'max_delta_step': 10, 'subsample': 0.5872483563483755, 'colsample_bytree': 0.5331415946439793, 'colsample_bylevel': 0.5405334559312343, 'colsample_bynode': 0.6427465833657989, 'gamma': 1.7563788736051098, 'reg_alpha': 8.423845165659381, 'reg_lambda': 0.7896992208227719, 'scale_pos_weight': 5.389252051546556, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 109, 'min_split_loss': 1.5931528773510184, 'max_bin': 203}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:15,116] Trial 25 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.04946815891844877, 'n_estimators': 470, 'min_child_weight': 8, 'max_delta_step': 8, 'subsample': 0.5975992972246622, 'colsample_bytree': 0.6193236465410948, 'colsample_bylevel': 0.4502475544282515, 'colsample_bynode': 0.501014388376901, 'gamma': 1.3912485267433863, 'reg_alpha': 7.613648092331612, 'reg_lambda': 0.8863831192564904, 'scale_pos_weight': 7.873124898041849, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 66, 'min_split_loss': 0.7074669513443002, 'max_bin': 198}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:16,929] Trial 26 finished with value: 0.06541753117823706 and parameters: {'max_depth': 4, 'learning_rate': 0.16771863769844086, 'n_estimators': 401, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.5590948349289743, 'colsample_bytree': 0.6935456330529359, 'colsample_bylevel': 0.6552604815712411, 'colsample_bynode': 0.621948757699518, 'gamma': 2.149319177982784, 'reg_alpha': 9.940950790102564, 'reg_lambda': 6.258365550575581, 'scale_pos_weight': 2.4398270530519985, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 120, 'min_split_loss': 2.4651998429086714, 'max_bin': 156}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:19,182] Trial 27 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.005400624624877402, 'n_estimators': 453, 'min_child_weight': 5, 'max_delta_step': 6, 'subsample': 0.6803421410907238, 'colsample_bytree': 0.7392980865669816, 'colsample_bylevel': 0.5558408003864461, 'colsample_bynode': 0.6863581377165149, 'gamma': 0.7194691717863351, 'reg_alpha': 8.901246352707666, 'reg_lambda': 9.934822022149355, 'scale_pos_weight': 12.392529430017454, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 93, 'min_split_loss': 4.009192608846645, 'max_bin': 215}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:21,241] Trial 28 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.02762123529964148, 'n_estimators': 349, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.5418286765987684, 'colsample_bytree': 0.874547994609024, 'colsample_bylevel': 0.4666227330437047, 'colsample_bynode': 0.7910374811919063, 'gamma': 2.5224180904584133, 'reg_alpha': 3.5940475941222414, 'reg_lambda': 3.039760491147214, 'scale_pos_weight': 10.066516454020741, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 44, 'min_split_loss': 1.4537791291224207, 'max_bin': 278}. Best is trial 20 with value: 0.3987188826743694.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:58:22,145] Trial 29 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.291684067687508, 'n_estimators': 393, 'min_child_weight': 6, 'max_delta_step': 4, 'subsample': 0.6145471243797517, 'colsample_bytree': 0.47058664398124855, 'colsample_bylevel': 0.5254510118279018, 'colsample_bynode': 0.9081303371752696, 'gamma': 3.279809433305326, 'reg_alpha': 0.2397128721823123, 'reg_lambda': 8.976122446570367, 'scale_pos_weight': 5.394624454881068, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 1, 'min_split_loss': 2.1534664085997592, 'max_bin': 217}. Best is trial 20 with value: 0.3987188826743694.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:58:23,371] Trial 30 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.0840492860159483, 'n_estimators': 230, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.5807497702910517, 'colsample_bytree': 0.5423155042803732, 'colsample_bylevel': 0.5856939831308418, 'colsample_bynode': 0.7796011413988642, 'gamma': 1.5317941087105387, 'reg_alpha': 4.99914415257795, 'reg_lambda': 0.026457463106309337, 'scale_pos_weight': 1.306300193698669, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 126, 'min_split_loss': 0.5876982660046968, 'max_bin': 145}. Best is trial 20 with value: 0.3987188826743694.
[I 2026-01-22 14:58:24,966] Trial 31 finished with value: 0.407728771244436 and parameters: {'max_depth': 5, 'learning_rate': 0.09402523551387028, 'n_estimators': 310, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.6528186051060549, 'colsample_bytree': 0.7135518406085111, 'colsample_bylevel': 0.4579904092988952, 'colsample_bynode': 0.9269694604194756, 'gamma': 1.9762876937290466, 'reg_alpha': 8.562611701318563, 'reg_lambda': 3.3692309177556385, 'scale_pos_weight': 5.281614831563931, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 148, 'min_split_loss': 2.7724483156966615, 'max_bin': 265}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:26,159] Trial 32 finished with value: 0.12206182762030322 and parameters: {'max_depth': 4, 'learning_rate': 0.1782227874206286, 'n_estimators': 301, 'min_child_weight': 8, 'max_delta_step': 8, 'subsample': 0.6345346741861905, 'colsample_bytree': 0.6378581943537213, 'colsample_bylevel': 0.4588976215643167, 'colsample_bynode': 0.7452890492172959, 'gamma': 2.0895468477556136, 'reg_alpha': 8.888627232631086, 'reg_lambda': 1.1672097275215174, 'scale_pos_weight': 3.076606862783313, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 68, 'min_split_loss': 3.384268107523101, 'max_bin': 271}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:30,313] Trial 33 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.04713891997931421, 'n_estimators': 374, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.6913593193407346, 'colsample_bytree': 0.7079842367232765, 'colsample_bylevel': 0.4544924741966268, 'colsample_bynode': 0.9184106551160687, 'gamma': 1.1538750778314983, 'reg_alpha': 6.49254364693661, 'reg_lambda': 5.143393895349865, 'scale_pos_weight': 7.330376400469571, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 159, 'min_split_loss': 2.8003093325000696, 'max_bin': 295}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:33,320] Trial 34 finished with value: 0.4022745691932534 and parameters: {'max_depth': 3, 'learning_rate': 0.08728524926420303, 'n_estimators': 439, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.5346036268389844, 'colsample_bytree': 0.7788004638041512, 'colsample_bylevel': 0.5066177617045421, 'colsample_bynode': 0.6986416973458605, 'gamma': 1.8256400000405595, 'reg_alpha': 7.64021093704208, 'reg_lambda': 2.5926091444782453, 'scale_pos_weight': 5.176422089957442, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 88, 'min_split_loss': 3.295630535175477, 'max_bin': 233}. Best is trial 31 with value: 0.407728771244436.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 14:58:34,070] Trial 35 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.0926311118027599, 'n_estimators': 338, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.5274760681339411, 'colsample_bytree': 0.7859982816814315, 'colsample_bylevel': 0.6534024461475244, 'colsample_bynode': 0.6951534103058257, 'gamma': 2.3168043775739218, 'reg_alpha': 7.508121301806939, 'reg_lambda': 2.5414534236075124, 'scale_pos_weight': 1.9586463084723413, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 36, 'min_split_loss': 3.391475680156642, 'max_bin': 235}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:34,938] Trial 36 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.050455475706242224, 'n_estimators': 244, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.5004048387460976, 'colsample_bytree': 0.851932622418331, 'colsample_bylevel': 0.43729581595167566, 'colsample_bynode': 0.8180353165815109, 'gamma': 2.757923953032118, 'reg_alpha': 9.359910768509868, 'reg_lambda': 4.101473782232787, 'scale_pos_weight': 9.630323622182736, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 58, 'min_split_loss': 3.3173185125249134, 'max_bin': 266}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:35,640] Trial 37 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.21675871774519903, 'n_estimators': 150, 'min_child_weight': 4, 'max_delta_step': 4, 'subsample': 0.5512337273742044, 'colsample_bytree': 0.9327407467680908, 'colsample_bylevel': 0.52286018583188, 'colsample_bynode': 0.7495755594884644, 'gamma': 1.9089738973472665, 'reg_alpha': 8.030128299202705, 'reg_lambda': 7.146185272989186, 'scale_pos_weight': 3.9762023760003204, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 23, 'min_split_loss': 0.31388380707901187, 'max_bin': 233}. Best is trial 31 with value: 0.407728771244436.
[I 2026-01-22 14:58:36,434] Trial 38 finished with value: 0.42914116108744976 and parameters: {'max_depth': 5, 'learning_rate': 0.15385379691765358, 'n_estimators': 441, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.7435377502389251, 'colsample_bytree': 0.4776138918136622, 'colsample_bylevel': 0.5720507711316412, 'colsample_bynode': 0.9511088185247761, 'gamma': 0.395783996822876, 'reg_alpha': 7.230822636175329, 'reg_lambda': 2.764334000519408, 'scale_pos_weight': 5.714851293054828, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 119, 'min_split_loss': 4.071182845114007, 'max_bin': 329}. Best is trial 38 with value: 0.42914116108744976.
[I 2026-01-22 14:58:37,739] Trial 39 finished with value: 0.15074032255146713 and parameters: {'max_depth': 3, 'learning_rate': 0.0761678983368223, 'n_estimators': 446, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.7434746339575418, 'colsample_bytree': 0.7609458583352304, 'colsample_bylevel': 0.7439179903534252, 'colsample_bynode': 0.9451791205876935, 'gamma': 0.4548068609045923, 'reg_alpha': 6.94422885241984, 'reg_lambda': 1.5941543552137987, 'scale_pos_weight': 3.0485252685785778, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 120, 'min_split_loss': 3.905714905841769, 'max_bin': 335}. Best is trial 38 with value: 0.42914116108744976.
[I 2026-01-22 14:58:38,430] Trial 40 finished with value: 0.43028413163163165 and parameters: {'max_depth': 10, 'learning_rate': 0.034581818517326585, 'n_estimators': 496, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.818817751686393, 'colsample_bytree': 0.46721878483372675, 'colsample_bylevel': 0.8181724376022547, 'colsample_bynode': 0.5296501149683908, 'gamma': 1.0151455413310382, 'reg_alpha': 7.290075626567087, 'reg_lambda': 2.851807192085002, 'scale_pos_weight': 7.5748245401763254, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 81, 'min_split_loss': 4.137022200025853, 'max_bin': 303}. Best is trial 40 with value: 0.43028413163163165.
[I 2026-01-22 14:58:39,445] Trial 41 finished with value: 0.4694008708708709 and parameters: {'max_depth': 8, 'learning_rate': 0.03297293028259158, 'n_estimators': 480, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.8166243141493986, 'colsample_bytree': 0.47439974921074113, 'colsample_bylevel': 0.8517478304788993, 'colsample_bynode': 0.4817917617623201, 'gamma': 0.00018552373955682544, 'reg_alpha': 7.955583679083235, 'reg_lambda': 2.680786642018272, 'scale_pos_weight': 7.610170519752102, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 85, 'min_split_loss': 4.981290749511017, 'max_bin': 307}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:40,509] Trial 42 finished with value: 0.433667536208025 and parameters: {'max_depth': 9, 'learning_rate': 0.020399017154190246, 'n_estimators': 486, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.8230375527094703, 'colsample_bytree': 0.4627711818575466, 'colsample_bylevel': 0.835721714954588, 'colsample_bynode': 0.484733866625561, 'gamma': 0.009734367495747853, 'reg_alpha': 6.241433487606638, 'reg_lambda': 2.7115356040018295, 'scale_pos_weight': 7.327575263643985, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 109, 'min_split_loss': 4.945100288020942, 'max_bin': 313}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:41,681] Trial 43 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.01808988433565463, 'n_estimators': 492, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.8382954247681378, 'colsample_bytree': 0.46706855031235417, 'colsample_bylevel': 0.8259419877271936, 'colsample_bynode': 0.4875915904684107, 'gamma': 0.025690765729647156, 'reg_alpha': 6.054085585111395, 'reg_lambda': 2.1734335261125644, 'scale_pos_weight': 9.366478044839164, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 112, 'min_split_loss': 4.883514522239637, 'max_bin': 301}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:42,534] Trial 44 finished with value: 0.4269531837418814 and parameters: {'max_depth': 10, 'learning_rate': 0.03148572903928727, 'n_estimators': 476, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.8144401972551116, 'colsample_bytree': 0.4970632566547994, 'colsample_bylevel': 0.7966363331312624, 'colsample_bynode': 0.4684879431347901, 'gamma': 0.3966078125080914, 'reg_alpha': 7.097008620901877, 'reg_lambda': 3.278488530581502, 'scale_pos_weight': 7.616370284613718, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 138, 'min_split_loss': 4.384241285657562, 'max_bin': 335}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:43,128] Trial 45 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.03183219882772133, 'n_estimators': 500, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.8095115279508013, 'colsample_bytree': 0.5014648663262915, 'colsample_bylevel': 0.7953959697800316, 'colsample_bynode': 0.4631004386957138, 'gamma': 0.3707763432424346, 'reg_alpha': 6.253293938646898, 'reg_lambda': 1.704390450539497, 'scale_pos_weight': 10.935541936277698, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 139, 'min_split_loss': 4.517293177568084, 'max_bin': 332}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:44,018] Trial 46 finished with value: 0.4188962996296107 and parameters: {'max_depth': 11, 'learning_rate': 0.011179844119896597, 'n_estimators': 470, 'min_child_weight': 10, 'max_delta_step': 5, 'subsample': 0.8796717857849228, 'colsample_bytree': 0.44641076840600735, 'colsample_bylevel': 0.8929002006134633, 'colsample_bynode': 0.5411151450449169, 'gamma': 0.07082891523828139, 'reg_alpha': 6.9568479535773475, 'reg_lambda': 2.7534565497142838, 'scale_pos_weight': 7.372663154057831, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 133, 'min_split_loss': 4.179766937704851, 'max_bin': 378}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:44,967] Trial 47 finished with value: 0.44293136750074247 and parameters: {'max_depth': 10, 'learning_rate': 0.020977927011089893, 'n_estimators': 478, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.8623619681885208, 'colsample_bytree': 0.55161220292385, 'colsample_bylevel': 0.8533627422462862, 'colsample_bynode': 0.5220847773014338, 'gamma': 0.6037243430764272, 'reg_alpha': 5.579539104070203, 'reg_lambda': 3.842891447282147, 'scale_pos_weight': 7.789879598320875, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 106, 'min_split_loss': 4.9094749900009536, 'max_bin': 319}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:46,000] Trial 48 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.02321201862088639, 'n_estimators': 451, 'min_child_weight': 10, 'max_delta_step': 3, 'subsample': 0.8700807242803776, 'colsample_bytree': 0.4463551733924322, 'colsample_bylevel': 0.9530768553310608, 'colsample_bynode': 0.5306606514775699, 'gamma': 0.6113042907305716, 'reg_alpha': 5.457457618738458, 'reg_lambda': 4.662133919277755, 'scale_pos_weight': 19.759068042046465, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 97, 'min_split_loss': 4.8280898468741995, 'max_bin': 315}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:47,670] Trial 49 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.014205236938163068, 'n_estimators': 480, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9294442617876377, 'colsample_bytree': 0.5669732986222329, 'colsample_bylevel': 0.8490477172662492, 'colsample_bynode': 0.5715604931151418, 'gamma': 0.9512996489245846, 'reg_alpha': 4.815058833258143, 'reg_lambda': 4.037261996487095, 'scale_pos_weight': 8.24917467902359, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 111, 'min_split_loss': 4.980358208879066, 'max_bin': 291}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:48,803] Trial 50 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.039582915853540485, 'n_estimators': 428, 'min_child_weight': 8, 'max_delta_step': 5, 'subsample': 0.7436437016315127, 'colsample_bytree': 0.40132468012986566, 'colsample_bylevel': 0.8836395447382829, 'colsample_bynode': 0.5138092112823104, 'gamma': 0.1861550201546186, 'reg_alpha': 5.976577364992551, 'reg_lambda': 3.775478200760103, 'scale_pos_weight': 11.313354126054005, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 78, 'min_split_loss': 4.672514095154351, 'max_bin': 354}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:49,831] Trial 51 finished with value: 0.4480945488339873 and parameters: {'max_depth': 10, 'learning_rate': 0.01822987627647712, 'n_estimators': 461, 'min_child_weight': 9, 'max_delta_step': 6, 'subsample': 0.7998941052135226, 'colsample_bytree': 0.5014670493435314, 'colsample_bylevel': 0.7847588783441872, 'colsample_bynode': 0.46809619462989505, 'gamma': 0.32638122653638313, 'reg_alpha': 5.37723913101329, 'reg_lambda': 3.06901335091133, 'scale_pos_weight': 7.611964868457052, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 167, 'min_split_loss': 4.315522310501533, 'max_bin': 341}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:51,043] Trial 52 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.01939748517622804, 'n_estimators': 454, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.7945973966731326, 'colsample_bytree': 0.5082187797137714, 'colsample_bylevel': 0.8346820158768872, 'colsample_bynode': 0.41594595111424265, 'gamma': 1.0178553396521428, 'reg_alpha': 5.528147816222392, 'reg_lambda': 2.137290189798949, 'scale_pos_weight': 9.475337162251263, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 190, 'min_split_loss': 4.233499798473526, 'max_bin': 395}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:52,648] Trial 53 finished with value: 0.4326685435259821 and parameters: {'max_depth': 10, 'learning_rate': 0.011405995060245734, 'n_estimators': 481, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.8315895612955839, 'colsample_bytree': 0.43410162541970954, 'colsample_bylevel': 0.7637998965891323, 'colsample_bynode': 0.450151062499735, 'gamma': 0.5453687931765145, 'reg_alpha': 6.436008372697514, 'reg_lambda': 2.8449894664580224, 'scale_pos_weight': 7.030527354245935, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 166, 'min_split_loss': 4.657610107734035, 'max_bin': 321}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:53,767] Trial 54 finished with value: 0.4222563937634402 and parameters: {'max_depth': 10, 'learning_rate': 0.017011281882818745, 'n_estimators': 500, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.853745646355176, 'colsample_bytree': 0.4222256467115968, 'colsample_bylevel': 0.7696347879360429, 'colsample_bynode': 0.4453343615471491, 'gamma': 0.6405206426199341, 'reg_alpha': 5.222277162473139, 'reg_lambda': 3.685763864579595, 'scale_pos_weight': 6.921863189516471, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 172, 'min_split_loss': 4.702180774173637, 'max_bin': 306}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:55,490] Trial 55 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.010518724981777184, 'n_estimators': 465, 'min_child_weight': 9, 'max_delta_step': 6, 'subsample': 0.9055564124781772, 'colsample_bytree': 0.5445937882737343, 'colsample_bylevel': 0.9287209965416598, 'colsample_bynode': 0.5715007688965988, 'gamma': 0.16794184162353876, 'reg_alpha': 4.595999025367758, 'reg_lambda': 4.6934701423346175, 'scale_pos_weight': 12.426012590082674, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 159, 'min_split_loss': 4.561222700385602, 'max_bin': 352}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:56,404] Trial 56 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.026887124264664095, 'n_estimators': 487, 'min_child_weight': 8, 'max_delta_step': 5, 'subsample': 0.8500566924290291, 'colsample_bytree': 0.4515791170061196, 'colsample_bylevel': 0.758524278669744, 'colsample_bynode': 0.44249346668333195, 'gamma': 0.5142516073299119, 'reg_alpha': 6.358344271334326, 'reg_lambda': 2.9297014403733574, 'scale_pos_weight': 8.880552216752843, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 191, 'min_split_loss': 4.278402683104009, 'max_bin': 287}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:57,612] Trial 57 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.012406420390120663, 'n_estimators': 465, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.9367586258719979, 'colsample_bytree': 0.43067149973568963, 'colsample_bylevel': 0.815571373093465, 'colsample_bynode': 0.47830955234361466, 'gamma': 0.8030274771522092, 'reg_alpha': 4.130301164220155, 'reg_lambda': 2.0040745167166847, 'scale_pos_weight': 10.406668422053832, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 171, 'min_split_loss': 4.998174724989824, 'max_bin': 316}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:58,457] Trial 58 finished with value: 0.4037683469921534 and parameters: {'max_depth': 7, 'learning_rate': 0.021768324583220575, 'n_estimators': 482, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.8205826055088983, 'colsample_bytree': 0.5258325236776579, 'colsample_bylevel': 0.8631692057215347, 'colsample_bynode': 0.5504433047278224, 'gamma': 0.30617344064996543, 'reg_alpha': 8.031465812554899, 'reg_lambda': 5.446191138117041, 'scale_pos_weight': 6.176947898261833, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 103, 'min_split_loss': 4.755078892746661, 'max_bin': 372}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:58:59,554] Trial 59 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.009041214590977948, 'n_estimators': 432, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.7969855660222703, 'colsample_bytree': 0.4876506473211556, 'colsample_bylevel': 0.7307962073516471, 'colsample_bynode': 0.5087636136739558, 'gamma': 0.028286242146909425, 'reg_alpha': 5.846916419537514, 'reg_lambda': 1.5510827578996564, 'scale_pos_weight': 6.9295983508249, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 211, 'min_split_loss': 4.415104417857431, 'max_bin': 345}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:59:00,599] Trial 60 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.03909946465372296, 'n_estimators': 406, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.7702249398060339, 'colsample_bytree': 0.5622960315540076, 'colsample_bylevel': 0.7026626108358774, 'colsample_bynode': 0.40018965440480814, 'gamma': 1.240983861314842, 'reg_alpha': 3.092068628601293, 'reg_lambda': 3.662200234482798, 'scale_pos_weight': 8.092291054154515, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 58, 'min_split_loss': 3.703770762170528, 'max_bin': 402}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:59:01,646] Trial 61 finished with value: 0.4103786894476444 and parameters: {'max_depth': 10, 'learning_rate': 0.015940317889973694, 'n_estimators': 457, 'min_child_weight': 9, 'max_delta_step': 1, 'subsample': 0.7589983650848176, 'colsample_bytree': 0.4654755831471051, 'colsample_bylevel': 0.7968960119655932, 'colsample_bynode': 0.5948477448522117, 'gamma': 0.2608153790370882, 'reg_alpha': 6.653739252155282, 'reg_lambda': 2.75256116051213, 'scale_pos_weight': 6.240185866456503, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 121, 'min_split_loss': 4.028929068114248, 'max_bin': 336}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:59:02,577] Trial 62 finished with value: 0.4137658086959828 and parameters: {'max_depth': 11, 'learning_rate': 0.02648481463309057, 'n_estimators': 437, 'min_child_weight': 8, 'max_delta_step': 5, 'subsample': 0.7903282401155857, 'colsample_bytree': 0.5145377983072384, 'colsample_bylevel': 0.8695127101523508, 'colsample_bynode': 0.4536439213545547, 'gamma': 0.5772946628098632, 'reg_alpha': 7.2070690245304, 'reg_lambda': 2.453347915789891, 'scale_pos_weight': 6.035839893149636, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 91, 'min_split_loss': 4.58948353758882, 'max_bin': 326}. Best is trial 41 with value: 0.4694008708708709.
[I 2026-01-22 14:59:03,414] Trial 63 finished with value: 0.06499245232245231 and parameters: {'max_depth': 10, 'learning_rate': 0.007241423594751878, 'n_estimators': 487, 'min_child_weight': 10, 'max_delta_step': 5, 'subsample': 0.7244847283964682, 'colsample_bytree': 0.48285142275239545, 'colsample_bylevel': 0.905955107342687, 'colsample_bynode': 0.4238868667985186, 'gamma': 0.8248834280175718, 'reg_alpha': 7.896930958771978, 'reg_lambda': 3.1945509819851265, 'scale_pos_weight': 4.293033672979435, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 108, 'min_split_loss': 4.099922369688394, 'max_bin': 303}. Best is trial 41 with value: 0.4694008708708709.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 15:02:13,668] Trial 291 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.0639066809513193, 'n_estimators': 294, 'min_child_weight': 5, 'max_delta_step': 2, 'subsample': 0.9827520939226941, 'colsample_bytree': 0.5672037148215684, 'colsample_bylevel': 0.706311744939824, 'colsample_bynode': 0.4820650897671621, 'gamma': 2.707767201803402, 'reg_alpha': 8.445446811611799, 'reg_lambda': 9.124947506138783, 'scale_pos_weight': 1.1715455471241576, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 117, 'min_split_loss': 2.525229338626556, 'max_bin': 256}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:14,363] Trial 292 finished with value: 0.4712391269334205 and parameters: {'max_depth': 12, 'learning_rate': 0.0501900812578326, 'n_estimators': 321, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.8590788582275324, 'colsample_bytree': 0.6526038473073063, 'colsample_bylevel': 0.714175221375147, 'colsample_bynode': 0.4428741166817551, 'gamma': 4.261394971397769, 'reg_alpha': 7.89925141040254, 'reg_lambda': 9.559828886945603, 'scale_pos_weight': 7.057402516320617, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 103, 'min_split_loss': 2.457844275421277, 'max_bin': 264}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:15,021] Trial 293 finished with value: 0.42395676434176116 and parameters: {'max_depth': 12, 'learning_rate': 0.051528680172910235, 'n_estimators': 324, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.8587793571452864, 'colsample_bytree': 0.6778249950056359, 'colsample_bylevel': 0.6849591361452217, 'colsample_bynode': 0.4405032498316456, 'gamma': 4.232882998807524, 'reg_alpha': 7.9501052109394035, 'reg_lambda': 9.510006924778612, 'scale_pos_weight': 6.08311033583988, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 128, 'min_split_loss': 2.1481961258297777, 'max_bin': 267}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:15,658] Trial 294 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.08201094313730245, 'n_estimators': 344, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.991685679690488, 'colsample_bytree': 0.6583600283552241, 'colsample_bylevel': 0.7126105851344792, 'colsample_bynode': 0.4118414624007563, 'gamma': 2.8246993038144024, 'reg_alpha': 7.847931390738594, 'reg_lambda': 9.740764096092745, 'scale_pos_weight': 8.673453539388195, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 104, 'min_split_loss': 2.405635040950043, 'max_bin': 250}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:16,542] Trial 295 finished with value: 0.4319691996889688 and parameters: {'max_depth': 12, 'learning_rate': 0.05772867620763366, 'n_estimators': 317, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9620241566068602, 'colsample_bytree': 0.6443837641345207, 'colsample_bylevel': 0.730053096163444, 'colsample_bynode': 0.42766825817474075, 'gamma': 4.3694975322692935, 'reg_alpha': 7.739737705917687, 'reg_lambda': 9.29731748853844, 'scale_pos_weight': 6.926594028917189, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 122, 'min_split_loss': 4.043059410523334, 'max_bin': 262}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:17,364] Trial 296 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.0913941107033929, 'n_estimators': 308, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9817809824275748, 'colsample_bytree': 0.6326865629853683, 'colsample_bylevel': 0.42682732052458583, 'colsample_bynode': 0.45333511706407936, 'gamma': 2.6672311127707067, 'reg_alpha': 0.758437866786336, 'reg_lambda': 9.551590532421297, 'scale_pos_weight': 7.860794609937974, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 114, 'min_split_loss': 2.489305503986988, 'max_bin': 244}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:18,024] Trial 297 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.07680837390033454, 'n_estimators': 332, 'min_child_weight': 10, 'max_delta_step': 8, 'subsample': 0.883047226074309, 'colsample_bytree': 0.6541685819714205, 'colsample_bylevel': 0.6990301364031193, 'colsample_bynode': 0.4418749836101808, 'gamma': 0.019736115893336403, 'reg_alpha': 7.917218803028399, 'reg_lambda': 9.998826420838874, 'scale_pos_weight': 8.122525961583687, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 108, 'min_split_loss': 2.272467653500939, 'max_bin': 276}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:18,432] Trial 298 finished with value: 0.45337969694475333 and parameters: {'max_depth': 11, 'learning_rate': 0.06352353828655298, 'n_estimators': 55, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9747344187014132, 'colsample_bytree': 0.6226984648553961, 'colsample_bylevel': 0.9985233637052706, 'colsample_bynode': 0.4583959383102628, 'gamma': 1.7401330352231361, 'reg_alpha': 9.46257519267262, 'reg_lambda': 8.990127731712988, 'scale_pos_weight': 7.590955325065938, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 132, 'min_split_loss': 2.066642578619335, 'max_bin': 390}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:19,113] Trial 299 finished with value: 0.4269531837418814 and parameters: {'max_depth': 12, 'learning_rate': 0.054116040437387575, 'n_estimators': 237, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.9995990496044527, 'colsample_bytree': 0.6357540851285257, 'colsample_bylevel': 0.716747449550338, 'colsample_bynode': 0.5111935054119784, 'gamma': 2.4826584337285627, 'reg_alpha': 8.197648964413078, 'reg_lambda': 9.721058101097896, 'scale_pos_weight': 7.420443320056024, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 119, 'min_split_loss': 2.613786184824722, 'max_bin': 260}. Best is trial 157 with value: 0.474162679332938.
[I 2026-01-22 15:02:19,692] Trial 300 finished with value: 0.4749592347581913 and parameters: {'max_depth': 13, 'learning_rate': 0.08208437259509903, 'n_estimators': 263, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9877465075402022, 'colsample_bytree': 0.6653431949736452, 'colsample_bylevel': 0.7490846641284998, 'colsample_bynode': 0.4992727947138033, 'gamma': 4.243359629794118, 'reg_alpha': 8.477959607715333, 'reg_lambda': 9.473810284368634, 'scale_pos_weight': 7.039298397028539, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 125, 'min_split_loss': 2.306123830902162, 'max_bin': 284}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:20,355] Trial 301 finished with value: 0.41723625346500354 and parameters: {'max_depth': 11, 'learning_rate': 0.048729635178333765, 'n_estimators': 266, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.8707838342472299, 'colsample_bytree': 0.6800264954105213, 'colsample_bylevel': 0.7320468224489245, 'colsample_bynode': 0.5303080517375128, 'gamma': 4.285218226225665, 'reg_alpha': 8.440631807714064, 'reg_lambda': 9.594146258422366, 'scale_pos_weight': 6.409957900049552, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 128, 'min_split_loss': 2.3328254376041175, 'max_bin': 282}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:21,014] Trial 302 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.24376438288316193, 'n_estimators': 263, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.9707315025559535, 'colsample_bytree': 0.6649654703503661, 'colsample_bylevel': 0.7519136672164246, 'colsample_bynode': 0.5027767535236155, 'gamma': 4.410934607267507, 'reg_alpha': 8.484219148917383, 'reg_lambda': 9.7910651158767, 'scale_pos_weight': 6.915277605237029, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 135, 'min_split_loss': 2.1716752212892487, 'max_bin': 289}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:22,311] Trial 303 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.0428795889549293, 'n_estimators': 258, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.946825367048634, 'colsample_bytree': 0.672221834125641, 'colsample_bylevel': 0.7111245464549751, 'colsample_bynode': 0.5187939277459152, 'gamma': 1.8933335138580574, 'reg_alpha': 8.945680620537404, 'reg_lambda': 9.44763260959324, 'scale_pos_weight': 8.193750190483673, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 124, 'min_split_loss': 2.4529514017017853, 'max_bin': 272}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:22,889] Trial 304 finished with value: 0.3914620155711267 and parameters: {'max_depth': 11, 'learning_rate': 0.08685208769565926, 'n_estimators': 273, 'min_child_weight': 10, 'max_delta_step': 7, 'subsample': 0.9863892879845035, 'colsample_bytree': 0.6427282071311666, 'colsample_bylevel': 0.7224784405047228, 'colsample_bynode': 0.49590336584854905, 'gamma': 2.9266371378555687, 'reg_alpha': 8.628574534283764, 'reg_lambda': 8.586551225661845, 'scale_pos_weight': 5.575314573282835, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 102, 'min_split_loss': 2.2656471022511466, 'max_bin': 291}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:23,585] Trial 305 finished with value: 0.46757692052242156 and parameters: {'max_depth': 7, 'learning_rate': 0.0601550672076311, 'n_estimators': 292, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9789752818245927, 'colsample_bytree': 0.6886749153388743, 'colsample_bylevel': 0.7447239067308821, 'colsample_bynode': 0.48543454723884977, 'gamma': 4.1833895541106125, 'reg_alpha': 8.100600236936465, 'reg_lambda': 9.822919712208563, 'scale_pos_weight': 7.720051718592577, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 141, 'min_split_loss': 2.6974378202318396, 'max_bin': 283}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:24,248] Trial 306 finished with value: 0.4569244998637256 and parameters: {'max_depth': 13, 'learning_rate': 0.059147283223642405, 'n_estimators': 276, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9595383675670316, 'colsample_bytree': 0.6894422154203479, 'colsample_bylevel': 0.7465085197182982, 'colsample_bynode': 0.4913534575908132, 'gamma': 4.170188263691188, 'reg_alpha': 8.05844398031804, 'reg_lambda': 2.6364413355232457, 'scale_pos_weight': 8.772594431150136, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 143, 'min_split_loss': 2.7421120706138864, 'max_bin': 285}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:25,126] Trial 307 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.06336344227304307, 'n_estimators': 286, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.8613665194919157, 'colsample_bytree': 0.6914406553977255, 'colsample_bylevel': 0.7395062806390097, 'colsample_bynode': 0.5031115668923308, 'gamma': 0.14143070458594295, 'reg_alpha': 7.638294690648236, 'reg_lambda': 9.519562175847122, 'scale_pos_weight': 7.806967653835771, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 140, 'min_split_loss': 2.0369245563713894, 'max_bin': 274}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:25,842] Trial 308 finished with value: 0.4586660210873791 and parameters: {'max_depth': 13, 'learning_rate': 0.055335696148520894, 'n_estimators': 290, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9776152834548978, 'colsample_bytree': 0.6631372695469518, 'colsample_bylevel': 0.7530094319887646, 'colsample_bynode': 0.48807833841377524, 'gamma': 2.3605555395807185, 'reg_alpha': 8.274692734949545, 'reg_lambda': 9.158695988229335, 'scale_pos_weight': 8.292619630168351, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 136, 'min_split_loss': 2.325565128620454, 'max_bin': 298}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:26,893] Trial 309 finished with value: 0.4463601466392397 and parameters: {'max_depth': 13, 'learning_rate': 0.06591066033222674, 'n_estimators': 308, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9668187956562106, 'colsample_bytree': 0.6501327761224565, 'colsample_bylevel': 0.6964134490904034, 'colsample_bynode': 0.4794160525761325, 'gamma': 2.801678018079281, 'reg_alpha': 9.128924740923475, 'reg_lambda': 9.995316245967176, 'scale_pos_weight': 7.868689923976761, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 132, 'min_split_loss': 2.192297213406435, 'max_bin': 279}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:28,171] Trial 310 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.07323556611570181, 'n_estimators': 246, 'min_child_weight': 9, 'max_delta_step': 3, 'subsample': 0.8763431024880113, 'colsample_bytree': 0.665520803164183, 'colsample_bylevel': 0.732327668774879, 'colsample_bynode': 0.5123163964517176, 'gamma': 2.0073070298567615, 'reg_alpha': 8.081032506710537, 'reg_lambda': 9.603078267630146, 'scale_pos_weight': 9.060054516567252, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 126, 'min_split_loss': 2.3924151468734807, 'max_bin': 269}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:28,788] Trial 311 finished with value: 0.4319691996889688 and parameters: {'max_depth': 6, 'learning_rate': 0.051342501184381203, 'n_estimators': 285, 'min_child_weight': 10, 'max_delta_step': 5, 'subsample': 0.8517787174370939, 'colsample_bytree': 0.672105785317993, 'colsample_bylevel': 0.7632014283027323, 'colsample_bynode': 0.4721190682379248, 'gamma': 2.6161537605137637, 'reg_alpha': 8.400115475720659, 'reg_lambda': 9.357419736827712, 'scale_pos_weight': 7.115402115543432, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 122, 'min_split_loss': 2.43631098151496, 'max_bin': 264}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:29,204] Trial 312 finished with value: 0.4569244998637256 and parameters: {'max_depth': 7, 'learning_rate': 0.05744377967873116, 'n_estimators': 258, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.9998884290224, 'colsample_bytree': 0.6961669174692008, 'colsample_bylevel': 0.7190288544538421, 'colsample_bynode': 0.4961839733143416, 'gamma': 4.130853607780697, 'reg_alpha': 7.528135888642831, 'reg_lambda': 8.745143173466202, 'scale_pos_weight': 8.5084808872928, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 142, 'min_split_loss': 1.9659331938580897, 'max_bin': 286}. Best is trial 300 with value: 0.4749592347581913.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-01-22 15:02:29,732] Trial 313 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.06735493697176936, 'n_estimators': 270, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9804930137658965, 'colsample_bytree': 0.6823326519383132, 'colsample_bylevel': 0.7051601347281032, 'colsample_bynode': 0.4813896926890546, 'gamma': 2.5561880198481046, 'reg_alpha': 7.902975796815334, 'reg_lambda': 3.2654595004453357, 'scale_pos_weight': 1.97503359056366, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 98, 'min_split_loss': 2.5413547020112017, 'max_bin': 254}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:30,405] Trial 314 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.06128478230552742, 'n_estimators': 297, 'min_child_weight': 9, 'max_delta_step': 5, 'subsample': 0.987322190614858, 'colsample_bytree': 0.6181959153257958, 'colsample_bylevel': 0.6815418223493236, 'colsample_bynode': 0.510529634518305, 'gamma': 4.229904565909421, 'reg_alpha': 8.20656084162261, 'reg_lambda': 8.936433462440128, 'scale_pos_weight': 15.530872229035353, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 130, 'min_split_loss': 2.2372450777547375, 'max_bin': 269}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:30,932] Trial 315 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.07700055601340455, 'n_estimators': 317, 'min_child_weight': 10, 'max_delta_step': 5, 'subsample': 0.972197333744454, 'colsample_bytree': 0.6416625259219811, 'colsample_bylevel': 0.7434306436038102, 'colsample_bynode': 0.900413767757319, 'gamma': 1.309492650705889, 'reg_alpha': 7.8218876922488105, 'reg_lambda': 9.777411420185755, 'scale_pos_weight': 19.832109980892934, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 110, 'min_split_loss': 2.108534050835278, 'max_bin': 294}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:31,360] Trial 316 finished with value: 0.4463601466392397 and parameters: {'max_depth': 6, 'learning_rate': 0.05036117450648897, 'n_estimators': 306, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9912597250258661, 'colsample_bytree': 0.6550446790783303, 'colsample_bylevel': 0.7267538365122974, 'colsample_bynode': 0.4674094217076174, 'gamma': 2.68667258057696, 'reg_alpha': 8.705182753658528, 'reg_lambda': 7.9215417507894195, 'scale_pos_weight': 7.730382862379615, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 124, 'min_split_loss': 2.345535080523807, 'max_bin': 277}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:31,858] Trial 317 finished with value: 0.46218925304425307 and parameters: {'max_depth': 8, 'learning_rate': 0.08630254269310288, 'n_estimators': 281, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9630208053951236, 'colsample_bytree': 0.5634805068447191, 'colsample_bylevel': 0.7567609769808, 'colsample_bynode': 0.5340970776979325, 'gamma': 4.485025082699134, 'reg_alpha': 8.044879871769608, 'reg_lambda': 9.185370304970226, 'scale_pos_weight': 8.08649294151557, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 138, 'min_split_loss': 2.5342046061996175, 'max_bin': 243}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:32,206] Trial 318 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.18959810599688365, 'n_estimators': 280, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9507783554403109, 'colsample_bytree': 0.7115946157632412, 'colsample_bylevel': 0.757420926694778, 'colsample_bynode': 0.544900014274946, 'gamma': 4.397491483161685, 'reg_alpha': 8.153058733658758, 'reg_lambda': 9.164762369093317, 'scale_pos_weight': 8.26983424905516, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 144, 'min_split_loss': 2.65481223172522, 'max_bin': 232}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:32,747] Trial 319 finished with value: 0.43884374246911595 and parameters: {'max_depth': 14, 'learning_rate': 0.08781133353362022, 'n_estimators': 271, 'min_child_weight': 10, 'max_delta_step': 5, 'subsample': 0.959868873170446, 'colsample_bytree': 0.5631353175504797, 'colsample_bylevel': 0.7361841533254905, 'colsample_bynode': 0.5308854965255868, 'gamma': 4.534443273270502, 'reg_alpha': 7.978096566905592, 'reg_lambda': 8.925483176844752, 'scale_pos_weight': 6.737164446401681, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 140, 'min_split_loss': 2.5517272531968795, 'max_bin': 241}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:33,161] Trial 320 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.044839730902632054, 'n_estimators': 256, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.8826821363568944, 'colsample_bytree': 0.5729546963499296, 'colsample_bylevel': 0.7116503234393983, 'colsample_bynode': 0.5263442875001477, 'gamma': 0.1774603019373513, 'reg_alpha': 8.352067738809767, 'reg_lambda': 8.225821527522065, 'scale_pos_weight': 8.923205165128884, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 135, 'min_split_loss': 2.7215978703112857, 'max_bin': 247}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:33,729] Trial 321 finished with value: 0.4604208874849827 and parameters: {'max_depth': 8, 'learning_rate': 0.05472878104504773, 'n_estimators': 287, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9360242545771812, 'colsample_bytree': 0.5471329858915666, 'colsample_bylevel': 0.7435467975231961, 'colsample_bynode': 0.4189580365888424, 'gamma': 4.512209062849794, 'reg_alpha': 8.107239756284372, 'reg_lambda': 9.30445016697568, 'scale_pos_weight': 8.101336593381763, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 134, 'min_split_loss': 2.470363272784825, 'max_bin': 256}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:34,594] Trial 322 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.05355577784851082, 'n_estimators': 287, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9549411346078822, 'colsample_bytree': 0.5526023357576383, 'colsample_bylevel': 0.748710598735289, 'colsample_bynode': 0.8460362646594185, 'gamma': 4.483804677689095, 'reg_alpha': 8.032753861826786, 'reg_lambda': 9.324876235642671, 'scale_pos_weight': 9.501341862003212, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 146, 'min_split_loss': 2.498646681356115, 'max_bin': 255}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:35,017] Trial 323 finished with value: 0.45177850209582593 and parameters: {'max_depth': 7, 'learning_rate': 0.04756688199174078, 'n_estimators': 295, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.9472164386225222, 'colsample_bytree': 0.5433782135873232, 'colsample_bylevel': 0.7493967140658415, 'colsample_bynode': 0.4189933982679139, 'gamma': 4.593520895311329, 'reg_alpha': 7.682912135162166, 'reg_lambda': 9.175112450944498, 'scale_pos_weight': 8.651272216275087, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 136, 'min_split_loss': 2.5864684739369124, 'max_bin': 261}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:35,765] Trial 324 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.057692701043967454, 'n_estimators': 283, 'min_child_weight': 9, 'max_delta_step': 3, 'subsample': 0.6400800271907551, 'colsample_bytree': 0.5411375472666243, 'colsample_bylevel': 0.7628605314104442, 'colsample_bynode': 0.41322802918696255, 'gamma': 4.609381182969442, 'reg_alpha': 8.584001716403302, 'reg_lambda': 9.396221658371042, 'scale_pos_weight': 8.100960841155006, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 94, 'min_split_loss': 2.9337796069999924, 'max_bin': 250}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:36,651] Trial 325 finished with value: 0.44984250125125125 and parameters: {'max_depth': 8, 'learning_rate': 0.053976034274859634, 'n_estimators': 293, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9151466336367913, 'colsample_bytree': 0.6111038210733349, 'colsample_bylevel': 0.7281983980637208, 'colsample_bynode': 0.42774027170126827, 'gamma': 4.358297874753135, 'reg_alpha': 8.343918281397983, 'reg_lambda': 9.541808049697023, 'scale_pos_weight': 7.1461929987415935, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 150, 'min_split_loss': 2.4632567216451955, 'max_bin': 227}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:38,316] Trial 326 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.041592564763630845, 'n_estimators': 356, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9305892300279842, 'colsample_bytree': 0.5533485023653586, 'colsample_bylevel': 0.7406698812581113, 'colsample_bynode': 0.4419710365322598, 'gamma': 4.496343526594624, 'reg_alpha': 7.7776611937729925, 'reg_lambda': 2.8566709347500567, 'scale_pos_weight': 11.717858401224401, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 129, 'min_split_loss': 2.313506791553312, 'max_bin': 170}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:38,866] Trial 327 finished with value: 0.44841184267849943 and parameters: {'max_depth': 12, 'learning_rate': 0.09336445274216272, 'n_estimators': 228, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.9639414466231839, 'colsample_bytree': 0.6279774595649987, 'colsample_bylevel': 0.7582328379251181, 'colsample_bynode': 0.4084846513151772, 'gamma': 2.4140474468848407, 'reg_alpha': 8.019086350905367, 'reg_lambda': 9.133604072463138, 'scale_pos_weight': 8.354926186124304, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 140, 'min_split_loss': 2.6687611401223807, 'max_bin': 238}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:40,335] Trial 328 finished with value: 0.4395549368754049 and parameters: {'max_depth': 15, 'learning_rate': 0.06046310077294905, 'n_estimators': 314, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9345757403748759, 'colsample_bytree': 0.5353497562692149, 'colsample_bylevel': 0.7376438268794678, 'colsample_bynode': 0.42595387861897455, 'gamma': 4.788483976559803, 'reg_alpha': 7.552274901248647, 'reg_lambda': 9.38698655455322, 'scale_pos_weight': 8.070028883706057, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 104, 'min_split_loss': 2.4872140920735175, 'max_bin': 159}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:41,476] Trial 329 finished with value: 0.19463582113363365 and parameters: {'max_depth': 11, 'learning_rate': 0.04805532324650608, 'n_estimators': 339, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.9710597984285905, 'colsample_bytree': 0.6515718518836462, 'colsample_bylevel': 0.7177707358436868, 'colsample_bynode': 0.538516929410549, 'gamma': 4.246754383938628, 'reg_alpha': 8.193838428011144, 'reg_lambda': 2.3946866134407427, 'scale_pos_weight': 3.726631507433021, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 100, 'min_split_loss': 2.2298731897491963, 'max_bin': 263}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:42,116] Trial 330 finished with value: 0.433667536208025 and parameters: {'max_depth': 8, 'learning_rate': 0.08415493312993493, 'n_estimators': 304, 'min_child_weight': 9, 'max_delta_step': 3, 'subsample': 0.9788785360170337, 'colsample_bytree': 0.5200906870405354, 'colsample_bylevel': 0.7263768463496, 'colsample_bynode': 0.4002388706727741, 'gamma': 0.222494349123748, 'reg_alpha': 7.86774606948384, 'reg_lambda': 9.632515794543115, 'scale_pos_weight': 7.465055864506616, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 110, 'min_split_loss': 2.388393447931638, 'max_bin': 247}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:42,875] Trial 331 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.05203438711237681, 'n_estimators': 277, 'min_child_weight': 10, 'max_delta_step': 6, 'subsample': 0.9382654126610921, 'colsample_bytree': 0.6351878000948212, 'colsample_bylevel': 0.7524697230050575, 'colsample_bynode': 0.5153159403028855, 'gamma': 4.1485787932229705, 'reg_alpha': 7.474683244295357, 'reg_lambda': 9.272113499469409, 'scale_pos_weight': 8.650637594373842, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 127, 'min_split_loss': 2.781433857605127, 'max_bin': 280}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:43,736] Trial 332 finished with value: 0.420569626391097 and parameters: {'max_depth': 7, 'learning_rate': 0.06417049721236553, 'n_estimators': 323, 'min_child_weight': 9, 'max_delta_step': 2, 'subsample': 0.9666156329138907, 'colsample_bytree': 0.5788505454486711, 'colsample_bylevel': 0.7675450225532822, 'colsample_bynode': 0.5014412502296515, 'gamma': 0.02662843677894275, 'reg_alpha': 8.795356022380592, 'reg_lambda': 9.00968267206081, 'scale_pos_weight': 6.422158171791826, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 121, 'min_split_loss': 2.575936515119346, 'max_bin': 258}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:44,331] Trial 333 finished with value: 0.45177850209582593 and parameters: {'max_depth': 12, 'learning_rate': 0.10218130987953579, 'n_estimators': 267, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.9437627239931946, 'colsample_bytree': 0.5591250230861685, 'colsample_bylevel': 0.693838313657902, 'colsample_bynode': 0.44295828630398637, 'gamma': 4.444529990962632, 'reg_alpha': 8.594136394882186, 'reg_lambda': 9.493569454567014, 'scale_pos_weight': 7.887793637464812, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 106, 'min_split_loss': 3.0606825525328185, 'max_bin': 272}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:45,638] Trial 334 finished with value: 0.40048882414882414 and parameters: {'max_depth': 8, 'learning_rate': 0.005284091931138052, 'n_estimators': 288, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9103025011419009, 'colsample_bytree': 0.7018451159272978, 'colsample_bylevel': 0.7361180801509147, 'colsample_bynode': 0.6800913898291837, 'gamma': 2.2950526611679827, 'reg_alpha': 6.841456730338598, 'reg_lambda': 9.750502908633608, 'scale_pos_weight': 7.13213385657546, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 134, 'min_split_loss': 2.2841262420958883, 'max_bin': 297}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:46,254] Trial 335 finished with value: 0.45160416331119463 and parameters: {'max_depth': 11, 'learning_rate': 0.07267568683314334, 'n_estimators': 141, 'min_child_weight': 9, 'max_delta_step': 6, 'subsample': 0.9999846695806388, 'colsample_bytree': 0.6725521452853173, 'colsample_bylevel': 0.7069918802158792, 'colsample_bynode': 0.5209642534283098, 'gamma': 4.327072583237091, 'reg_alpha': 8.393463026864838, 'reg_lambda': 9.426540813300088, 'scale_pos_weight': 7.575536166414458, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 113, 'min_split_loss': 2.4350275419381813, 'max_bin': 286}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:47,031] Trial 336 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.059935146666156895, 'n_estimators': 309, 'min_child_weight': 9, 'max_delta_step': 4, 'subsample': 0.979655047852505, 'colsample_bytree': 0.6024250017366832, 'colsample_bylevel': 0.7455711644767052, 'colsample_bynode': 0.5557334635723301, 'gamma': 1.1620273135572425, 'reg_alpha': 6.527502603428763, 'reg_lambda': 9.652050561087794, 'scale_pos_weight': 8.121989415615845, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 118, 'min_split_loss': 2.1851773765981375, 'max_bin': 242}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:47,708] Trial 337 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.05605496341996636, 'n_estimators': 300, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.9895304345335498, 'colsample_bytree': 0.6427718147417745, 'colsample_bylevel': 0.9791880221620719, 'colsample_bynode': 0.436462377317861, 'gamma': 2.5721355751684367, 'reg_alpha': 8.096268355006934, 'reg_lambda': 9.076405353614177, 'scale_pos_weight': 9.19313570719284, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 69, 'min_split_loss': 2.507177359613587, 'max_bin': 267}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:48,200] Trial 338 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.09368164619642748, 'n_estimators': 247, 'min_child_weight': 10, 'max_delta_step': 4, 'subsample': 0.9555623404555716, 'colsample_bytree': 0.6242339866452058, 'colsample_bylevel': 0.7230044309001937, 'colsample_bynode': 0.45047735440220144, 'gamma': 2.7265836245846784, 'reg_alpha': 7.727573963725716, 'reg_lambda': 3.125928574284841, 'scale_pos_weight': 8.583792215405943, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 129, 'min_split_loss': 2.3316672425809886, 'max_bin': 254}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:48,996] Trial 339 finished with value: 0.4371046464871465 and parameters: {'max_depth': 11, 'learning_rate': 0.06766640305896614, 'n_estimators': 322, 'min_child_weight': 9, 'max_delta_step': 3, 'subsample': 0.9717255563500702, 'colsample_bytree': 0.5503853326130241, 'colsample_bylevel': 0.7734931894550181, 'colsample_bynode': 0.4989083238988992, 'gamma': 2.4753617310520255, 'reg_alpha': 8.185268959299606, 'reg_lambda': 7.117036723013908, 'scale_pos_weight': 6.686526461519877, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 139, 'min_split_loss': 2.672374816226041, 'max_bin': 276}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:49,859] Trial 340 finished with value: 0.46757692052242156 and parameters: {'max_depth': 9, 'learning_rate': 0.05027176492904699, 'n_estimators': 281, 'min_child_weight': 9, 'max_delta_step': 0, 'subsample': 0.9802236846958842, 'colsample_bytree': 0.5252897397834402, 'colsample_bylevel': 0.7549379070167005, 'colsample_bynode': 0.41911419652682214, 'gamma': 4.243883786836794, 'reg_alpha': 4.746761392169729, 'reg_lambda': 9.28151743384562, 'scale_pos_weight': 7.584868191728284, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 100, 'min_split_loss': 2.5851634830679298, 'max_bin': 325}. Best is trial 300 with value: 0.4749592347581913.
[I 2026-01-22 15:02:50,802] Trial 341 finished with value: 0.41723625346500354 and parameters: {'max_depth': 9, 'learning_rate': 0.049677809694090184, 'n_estimators': 275, 'min_child_weight': 9, 'max_delta_step': 0, 'subsample': 0.9808598436453311, 'colsample_bytree': 0.5234163232158281, 'colsample_bylevel': 0.7570228120254194, 'colsample_bynode': 0.7022842137534828, 'gamma': 4.182055864472465, 'reg_alpha': 6.318832602997748, 'reg_lambda': 2.1122717074522925, 'scale_pos_weight': 7.1683110259526925, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 90, 'min_split_loss': 2.711541438443197, 'max_bin': 305}. Best is trial 300 with value: 0.4749592347581913.

In [62]:
# best_params_xgb = grid_xgb.best_params_

In [63]:
best_params_xgb = study_xgb.best_params

In [64]:
print(best_params_xgb)

{'max_depth': 13, 'learning_rate': 0.08208437259509903, 'n_estimators': 263, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.9877465075402022, 'colsample_bytree': 0.6653431949736452, 'colsample_bylevel': 0.7490846641284998, 'colsample_bynode': 0.4992727947138033, 'gamma': 4.243359629794118, 'reg_alpha': 8.477959607715333, 'reg_lambda': 9.473810284368634, 'scale_pos_weight': 7.039298397028539, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 125, 'min_split_loss': 2.306123830902162, 'max_bin': 284}

In [65]:
final_classifier = xgb.XGBClassifier(**best_params_xgb, random_state=42, eval_metric='logloss')

In [66]:
final_classifier.fit(X_train_res_retained, y_train_res)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=0.7490846641284998,
              colsample_bynode=0.4992727947138033,
              colsample_bytree=0.6653431949736452, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.243359629794118, grow_policy='depthwise',
              importance_type=None, interaction_constraints=None,
              learning_rate=0.08208437259509903, max_bin=284,
              max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=8,
              max_depth=13, max_leaves=125, min_child_weight=9,
              min_split_loss=2.306123830902162, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=263,
              n_jobs=None, ...)

In [67]:
y_pred_val = final_classifier.predict(X_val_retained)

In [68]:
y_proba_val = final_classifier.predict_proba(X_val_retained)[:, 1]

In [69]:
print(confusion_matrix(y_val, y_pred_val))

[[648  81]
 [ 13  24]]

In [70]:
print(accuracy_score(y_val, y_pred_val))

0.8772845953002611

In [71]:
print(precision_score(y_val, y_pred_val))

0.22857142857142856

In [72]:
print(recall_score(y_val, y_pred_val))

0.6486486486486487

In [73]:
print(fbeta_score(y_val, y_pred_val, beta=2))

0.4743083003952569

### Threshold tuning

In [74]:
best_threshold = 0.5

In [75]:
best_precision_score = 0

In [76]:
best_recall_score = 0

In [77]:
best_f2_score = 0

In [78]:
for threshold in np.arange(0.1, 0.95, 0.05):
    y_pred_val_threshold = (y_proba_val >= threshold).astype(int)
    recall = recall_score(y_val, y_pred_val_threshold)
    precision = precision_score(y_val, y_pred_val_threshold)
    f2_score = fbeta_score(y_val, y_pred_val_threshold, beta=2)
    
    print(f'Threshold {threshold} has F2 score {f2_score}')
    
    if precision >= 0.15:
        current_recall_score = recall
        if current_recall_score > best_recall_score:
            best_recall_score = current_recall_score
            best_precision_score = precision
            best_threshold = threshold
        elif current_recall_score == best_recall_score and precision > best_precision_score:
            best_precision_score = precision
            best_threshold = threshold
        
        # current_f2_score = f2_score
        # if current_f2_score > best_f2_score:
        #     best_f2_score = current_f2_score
        #     best_threshold = threshold

Threshold 0.1 has F2 score 0.3541666666666667
Threshold 0.15000000000000002 has F2 score 0.350109409190372
Threshold 0.20000000000000004 has F2 score 0.35476718403547675
Threshold 0.25000000000000006 has F2 score 0.3669724770642202
Threshold 0.30000000000000004 has F2 score 0.3944020356234097
Threshold 0.3500000000000001 has F2 score 0.4131054131054131
Threshold 0.40000000000000013 has F2 score 0.42207792207792205
Threshold 0.45000000000000007 has F2 score 0.43795620437956206
Threshold 0.5000000000000001 has F2 score 0.4743083003952569
Threshold 0.5500000000000002 has F2 score 0.39094650205761317
Threshold 0.6000000000000002 has F2 score 0.2696078431372549
Threshold 0.6500000000000001 has F2 score 0.19553072625698323
Threshold 0.7000000000000002 has F2 score 0.09259259259259259
Threshold 0.7500000000000002 has F2 score 0.0
Threshold 0.8000000000000002 has F2 score 0.0
Threshold 0.8500000000000002 has F2 score 0.0
Threshold 0.9000000000000002 has F2 score 0.0

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [79]:
print(best_threshold)

0.40000000000000013

In [80]:
print(best_recall_score)

0.7027027027027027

### Retrain on training + validation set

In [81]:
X_train_full = pd.concat([X_train_res_retained, X_val_retained], axis=0, ignore_index=True)
y_train_full = pd.concat([y_train_res, y_val], axis=0, ignore_index=True)

In [82]:
final_classifier.fit(X_train_full, y_train_full)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=0.7490846641284998,
              colsample_bynode=0.4992727947138033,
              colsample_bytree=0.6653431949736452, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=4.243359629794118, grow_policy='depthwise',
              importance_type=None, interaction_constraints=None,
              learning_rate=0.08208437259509903, max_bin=284,
              max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=8,
              max_depth=13, max_leaves=125, min_child_weight=9,
              min_split_loss=2.306123830902162, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=263,
              n_jobs=None, ...)

### Evaluate on test set

In [83]:
X_test_retained = X_test[retained_columns]

In [84]:
y_pred_test = final_classifier.predict(X_test_retained)

In [85]:
y_proba_test = final_classifier.predict_proba(X_test_retained)[:, 1]

In [86]:
print(confusion_matrix(y_test, y_pred_test))

[[649  80]
 [ 14  24]]

In [87]:
print(accuracy_score(y_test, y_pred_test))

0.877444589308996

In [88]:
print(precision_score(y_test, y_pred_test))

0.23076923076923078

In [89]:
print(recall_score(y_test, y_pred_test))

0.631578947368421

In [90]:
print(fbeta_score(y_test, y_pred_test, beta=2))

0.46875

### Test with best threshold 0.45

In [91]:
y_pred_test_threshold = (y_proba_test >= best_threshold).astype(int)

In [92]:
print(confusion_matrix(y_test, y_pred_test_threshold))

[[578 151]
 [  9  29]]

In [93]:
print(accuracy_score(y_test, y_pred_test_threshold))

0.7913950456323338

In [94]:
print(precision_score(y_test, y_pred_test_threshold))

0.16111111111111112

In [95]:
print(recall_score(y_test, y_pred_test_threshold))

0.7631578947368421

In [96]:
print(fbeta_score(y_test, y_pred_test_threshold, beta=2))

0.4367469879518072