# Stroke Prediction

## Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
import optuna
from optuna.samplers import TPESampler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, fbeta_score, make_scorer

## Import dataset

In [2]:
df = pd.read_csv('../dataset/healthcare-dataset-stroke-data.csv')

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [5]:
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [6]:
df.describe(include=[object])

        gender ever_married work_type Residence_type smoking_status
count     5110         5110      5110           5110           5110
unique       3            2         5              2              4
top     Female          Yes   Private          Urban   never smoked
freq      2994         3353      2925           2596           1892

## Rename column for consistent formatting of name

In [7]:
df.rename(columns={'Residence_type': 'residence_type'}, inplace=True)

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
pd.set_option('display.max_rows', None)

### Impute missing values in BMI column
For 201 entries missing BMI values, these entries will be imputed with the median BMI value

In [10]:
median_bmi = df['bmi'].median()
df['bmi'].fillna(median_bmi, inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_32904\2337012406.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bmi'].fillna(median_bmi, inplace=True)

In [11]:
print(df['bmi'].isna().sum())

0

## Feature Engineering

### Converting categorical columns to numerical columns

In [12]:
df['male'] = (df['gender'] == 'Male').astype(int)

In [13]:
df['ever_married'] = (df['ever_married'] == 'Yes').astype(int)

In [14]:
df['urban'] = (df['residence_type'] == 'Urban').astype(int)

In [15]:
df['smoke'] = ((df['smoking_status'] == 'formerly smoked') | (df['smoking_status'] == 'smokes')).astype(int)

In [16]:
df['have_work'] = ((df['work_type'] == 'Govt_job') | (df['work_type'] == 'Private') | (df['work_type'] == 'Self-employed')).astype(int)

In [17]:
df['hypertension_or_heart_disease'] = df['hypertension'] | df['heart_disease']

In [18]:
df = pd.get_dummies(df, columns=['work_type', 'smoking_status'], drop_first = False)

### Extra columns for interaction features

In [19]:
df['age_ever_married'] = df['age'] * df['ever_married']

In [20]:
df['age_hypertension'] = df['age'] * df['hypertension']

In [21]:
df['age_heart_disease'] = df['age'] * df['heart_disease']

In [22]:
df['age_bmi'] = df['age'] * df['bmi']

In [23]:
df['age_avg_glucose_level'] = df['age'] * df['avg_glucose_level']

In [24]:
df['bmi_avg_glucose_level'] = df['bmi'] * df['avg_glucose_level']

In [25]:
df['avg_glucose_level_hypertension'] = df['avg_glucose_level'] * df['hypertension']

### Creating columns representing outstanding values for BMI and Average Glucose Level

In [26]:
df['obese'] = df['bmi'] >= 30

In [27]:
df['high_avg_glucose_level'] = df['avg_glucose_level'] >= 150

In [28]:
df['obese_high_avg_glucose_level'] = df['obese'] | df['high_avg_glucose_level']

### Creating column representing high age

In [29]:
df['old'] = df['age'] >= 65

### Converting boolean columns to numerical

In [30]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

### Accounting for multiple risks

In [31]:
df['risk_count'] = df['obese'] + df['high_avg_glucose_level'] + df['old'] + df['hypertension'] + df['heart_disease']

### Reformatting column names

In [32]:
df.rename(columns={'work_type_Govt_job': 'work_type_govt_job', 'work_type_Never_worked': 'work_type_never_worked', 'work_type_Private': 'work_type_private', 'work_type_Self-employed': 'work_type_self_employed'}, inplace=True)

In [33]:
df.rename(columns={'smoking_status_Unknown': 'smoking_status_unknown', 'smoking_status_formerly smoked': 'smoking_status_formerly_smoked', 'smoking_status_never smoked': 'smoking_status_never_smoked'}, inplace=True)

In [34]:
df.drop(columns=['gender', 'residence_type'], inplace=True)

### Log Transforming BMI and Average Glucose Level columns

In [35]:
df['log_bmi'] = np.log(df['bmi'])

In [36]:
df['log_avg_glucose_level'] = np.log(df['avg_glucose_level'])

In [37]:
df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,male,urban,smoke,have_work,hypertension_or_heart_disease,work_type_govt_job,work_type_never_worked,work_type_private,work_type_self_employed,work_type_children,smoking_status_unknown,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,age_ever_married,age_hypertension,age_heart_disease,age_bmi,age_avg_glucose_level,bmi_avg_glucose_level,avg_glucose_level_hypertension,obese,high_avg_glucose_level,obese_high_avg_glucose_level,old,risk_count,log_bmi,log_avg_glucose_level
0,9046,67.0,0,1,1,228.69,36.6,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,67.0,0.0,67.0,2452.2,15322.23,8370.054,0.00,1,1,1,1,4,3.600048,5.432367
1,51676,61.0,0,0,1,202.21,28.1,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,61.0,0.0,0.0,1714.1,12334.81,5682.101,0.00,0,1,1,0,1,3.335770,5.309307
2,31112,80.0,0,1,1,105.92,32.5,1,1,0,0,1,1,0,0,1,0,0,0,0,1,0,80.0,0.0,80.0,2600.0,8473.60,3442.400,0.00,1,0,1,1,3,3.481240,4.662684
3,60182,49.0,0,0,1,171.23,34.4,1,0,1,1,1,0,0,0,1,0,0,0,0,0,1,49.0,0.0,0.0,1685.6,8390.27,5890.312,0.00,1,1,1,0,2,3.538057,5.143008
4,1665,79.0,1,0,1,174.12,24.0,1,0,0,0,1,1,0,0,0,1,0,0,0,1,0,79.0,79.0,0.0,1896.0,13755.48,4178.880,174.12,0,1,1,1,3,3.178054,5.159745

In [38]:
df.shape

(5110, 36)

## Model Building

### Splitting to training, validation, and testing sets

In [39]:
columns_name = columns_name = [col for col in df.columns if col != 'id']

In [40]:
X = df[columns_name]
X.drop('stroke', axis=1, inplace=True)
y = df['stroke']

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_32904\91966498.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('stroke', axis=1, inplace=True)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify = y)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size = 0.5, random_state = 42, stratify = y_test)

### Create base random forest classifier model

In [42]:
base_classifier = xgb.XGBClassifier(random_state=42, eval_metric='logloss')

### Create grid for hyperparameter tuning

In [43]:
param_grid_xgb = {
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [50, 100, 200],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'scale_pos_weight': [1, 3, 5, 10, 15, 20]
}

In [44]:
f2_scorer = make_scorer(fbeta_score, beta=2)

In [45]:
grid_xgb = GridSearchCV(
    estimator=base_classifier,
    param_grid=param_grid_xgb,
    scoring=f2_scorer,
    cv=5,
    verbose=2,
    n_jobs=-1
)

### Fitting base classifier on unsampled data

In [46]:
base_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [47]:
importances = base_classifier.feature_importances_

In [48]:
feature_imp_df = pd.DataFrame({'Feature':[col for col in X_train], 'Importance': importances}).sort_values(
    'Importance', ascending=False)

In [49]:
print(feature_imp_df)

                           Feature  Importance
0                              age    0.148926
3                     ever_married    0.083450
23                         age_bmi    0.058028
19           smoking_status_smokes    0.053031
21                age_hypertension    0.048881
5                              bmi    0.043420
11              work_type_govt_job    0.039279
18     smoking_status_never_smoked    0.037942
31                      risk_count    0.036048
4                avg_glucose_level    0.034835
26  avg_glucose_level_hypertension    0.033516
10   hypertension_or_heart_disease    0.032696
20                age_ever_married    0.032403
25           bmi_avg_glucose_level    0.031465
16          smoking_status_unknown    0.030754
22               age_heart_disease    0.028763
8                            smoke    0.028084
7                            urban    0.027726
6                             male    0.027300
2                    heart_disease    0.027104
14         work_type_self_employed    0.027079
13               work_type_private    0.025810
24           age_avg_glucose_level    0.025014
17  smoking_status_formerly_smoked    0.022777
29    obese_high_avg_glucose_level    0.015668
1                     hypertension    0.000000
15              work_type_children    0.000000
12          work_type_never_worked    0.000000
27                           obese    0.000000
28          high_avg_glucose_level    0.000000
30                             old    0.000000
9                        have_work    0.000000
32                         log_bmi    0.000000
33           log_avg_glucose_level    0.000000

In [50]:
# retained_columns = ['age', 'ever_married', 'age_bmi', 'smoking_status_smokes', 'age_hypertension', 'bmi', 'work_type_govt_job', 'smoking_status_never_smoked']

In [51]:
# retained_columns = ['age', 'ever_married', 'age_bmi', 'smoking_status_smokes', 'age_hypertension', 'bmi', 'work_type_govt_job', 'smoking_status_never_smoked', 'risk_count']

In [52]:
# retained_columns = ['age', 'ever_married', 'age_bmi', 'smoking_status_smokes', 'age_hypertension', 'bmi', 'work_type_govt_job', 'smoking_status_never_smoked', 'risk_count', 'avg_glucose_level']

In [53]:
# retained_columns = ['age', 'smoking_status_unknown', 'ever_married', 'smoking_status_smokes', 'smoking_status_never_smoked', 'age_heart_disease', 'bmi', 'age_hypertension']

In [54]:
# retained_columns = ['age', 'smoking_status_unknown', 'ever_married', 'smoking_status_smokes', 'smoking_status_never_smoked', 'age_heart_disease', 'bmi', 'age_hypertension', 'work_type_private', 'age_ever_married', 'work_type_self_employed', 'urban']

In [55]:
retained_columns = ['age', 'smoking_status_unknown', 'ever_married', 'smoking_status_smokes', 'smoking_status_never_smoked', 'age_heart_disease', 'bmi', 'age_hypertension', 'work_type_private', 'age_ever_married']

In [56]:
# retained_columns = ['age', 'smoking_status_unknown', 'ever_married', 'smoking_status_smokes', 'smoking_status_never_smoked', 'age_heart_disease', 'bmi', 'age_hypertension', 'work_type_private']

In [57]:
X_train_retained = X_train[retained_columns]

In [58]:
X_val_retained = X_val[retained_columns]

### Create optimizing function for hyperparameter tuning with Optuna

In [59]:
MIN_PRECISION = 0.2

In [60]:
def objective_xgb(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'max_delta_step': trial.suggest_int('max_delta_step', 0, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.4, 1.0),
        'colsample_bynode': trial.suggest_float('colsample_bynode', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 10),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 10),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1, 20),
        'tree_method': trial.suggest_categorical('tree_method', ['hist', 'approx']), 
        'grow_policy': trial.suggest_categorical('grow_policy', ['depthwise', 'lossguide']),  
        'max_leaves': trial.suggest_int('max_leaves', 0, 256),
        'min_split_loss': trial.suggest_float('min_split_loss', 0, 5),  
        'max_bin': trial.suggest_int('max_bin', 128, 512),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    
    model = xgb.XGBClassifier(**params)
    
    model.fit(X_train_retained, y_train)
    
    y_pred_val = model.predict(X_val_retained)
    
    recall = recall_score(y_val, y_pred_val)
    precision = precision_score(y_val, y_pred_val)
    f2_score = fbeta_score(y_val, y_pred_val, beta=2)
    
    if precision < MIN_PRECISION:
        return 0
    return recall + (precision * 0.01)
    # return f2_score + recall * 0.001 + precision * 0.00001

In [61]:
study_xgb = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
study_xgb.optimize(objective_xgb, n_trials=500, show_progress_bar=True)

[I 2026-02-02 21:54:49,367] A new study created in memory with name: no-name-acb2574c-67ab-477c-a0fb-a6b47e828fb2

  0%|          | 0/500 [00:00<?, ?it/s]

[I 2026-02-02 21:54:49,781] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.24517932047070642, 'n_estimators': 380, 'min_child_weight': 6, 'max_delta_step': 1, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.4348501673009197, 'colsample_bylevel': 0.9197056874649611, 'colsample_bynode': 0.7606690070459252, 'gamma': 3.540362888980227, 'reg_alpha': 0.20584494295802447, 'reg_lambda': 9.699098521619943, 'scale_pos_weight': 16.816410175208013, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 134, 'min_split_loss': 2.1597250932105787, 'max_bin': 240}. Best is trial 0 with value: 0.0.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:54:50,210] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.008851384099881301, 'n_estimators': 181, 'min_child_weight': 4, 'max_delta_step': 5, 'subsample': 0.8925879806965068, 'colsample_bytree': 0.5198042692950159, 'colsample_bylevel': 0.708540663048167, 'colsample_bynode': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 6.075448519014383, 'reg_lambda': 1.7052412368729153, 'scale_pos_weight': 2.235980266720311, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 25, 'min_split_loss': 3.4211651325607844, 'max_bin': 297}. Best is trial 0 with value: 0.0.
[I 2026-02-02 21:54:50,300] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.03797252233376349, 'n_estimators': 65, 'min_child_weight': 10, 'max_delta_step': 2, 'subsample': 0.831261142176991, 'colsample_bytree': 0.5870266456536466, 'colsample_bylevel': 0.7120408127066865, 'colsample_bynode': 0.7280261676059678, 'gamma': 0.9242722776276352, 'reg_alpha': 9.695846277645586, 'reg_lambda': 7.7513282336111455, 'scale_pos_weight': 18.850479889719594, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 50, 'min_split_loss': 0.22613644455269033, 'max_bin': 253}. Best is trial 0 with value: 0.0.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:54:50,532] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.015186917176306207, 'n_estimators': 423, 'min_child_weight': 4, 'max_delta_step': 3, 'subsample': 0.7713480415791243, 'colsample_bytree': 0.4845545349848576, 'colsample_bylevel': 0.8813181884524238, 'colsample_bynode': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 7.722447692966574, 'reg_lambda': 1.987156815341724, 'scale_pos_weight': 1.1049202253484456, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 19, 'min_split_loss': 1.7923286427213632, 'max_bin': 172}. Best is trial 0 with value: 0.0.
[I 2026-02-02 21:54:51,563] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.06416354462323627, 'n_estimators': 199, 'min_child_weight': 1, 'max_delta_step': 3, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.8377637070028385, 'colsample_bylevel': 0.7825344828131279, 'colsample_bynode': 0.932327645545796, 'gamma': 2.3610746258097466, 'reg_alpha': 1.195942459383017, 'reg_lambda': 7.13244787222995, 'scale_pos_weight': 15.454915923721051, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 109, 'min_split_loss': 0.12709563372047594, 'max_bin': 169}. Best is trial 0 with value: 0.0.
[I 2026-02-02 21:54:51,685] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.0677023857369087, 'n_estimators': 191, 'min_child_weight': 6, 'max_delta_step': 9, 'subsample': 0.6246461145744375, 'colsample_bytree': 0.6462297538213778, 'colsample_bylevel': 0.8533306831258292, 'colsample_bynode': 0.5372788992949735, 'gamma': 0.38489954914396496, 'reg_alpha': 2.8975145291376805, 'reg_lambda': 1.6122128725400442, 'scale_pos_weight': 18.66425539450889, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 47, 'min_split_loss': 4.462794992449889, 'max_bin': 335}. Best is trial 0 with value: 0.0.
[I 2026-02-02 21:54:52,018] Trial 6 finished with value: 0.13721846846846847 and parameters: {'max_depth': 13, 'learning_rate': 0.19604504485810242, 'n_estimators': 193, 'min_child_weight': 2, 'max_delta_step': 2, 'subsample': 0.7135538943131281, 'colsample_bytree': 0.8908088595534959, 'colsample_bylevel': 0.916438349953806, 'colsample_bynode': 0.40417127831871447, 'gamma': 2.553736512887829, 'reg_alpha': 4.17411003148779, 'reg_lambda': 2.2210781047073027, 'scale_pos_weight': 3.277441979339973, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 180, 'min_split_loss': 1.81814801189647, 'max_bin': 502}. Best is trial 6 with value: 0.13721846846846847.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:54:52,460] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.014017707981920842, 'n_estimators': 274, 'min_child_weight': 4, 'max_delta_step': 3, 'subsample': 0.5184434736772664, 'colsample_bytree': 0.7657386003879381, 'colsample_bylevel': 0.701607413937317, 'colsample_bynode': 0.4308872507499936, 'gamma': 1.3932323211830573, 'reg_alpha': 9.082658859666537, 'reg_lambda': 2.395618906669724, 'scale_pos_weight': 3.7530025697332388, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 195, 'min_split_loss': 1.1881877199619983, 'max_bin': 408}. Best is trial 6 with value: 0.13721846846846847.
[I 2026-02-02 21:54:52,982] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.06657411588229807, 'n_estimators': 335, 'min_child_weight': 6, 'max_delta_step': 0, 'subsample': 0.917651247794619, 'colsample_bytree': 0.5924680389830415, 'colsample_bylevel': 0.5119111062399125, 'colsample_bynode': 0.4244650849328584, 'gamma': 2.954464715941209, 'reg_alpha': 6.775643618422825, 'reg_lambda': 0.16587828927856152, 'scale_pos_weight': 10.729768107686338, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 99, 'min_split_loss': 4.6836499436836725, 'max_bin': 180}. Best is trial 6 with value: 0.13721846846846847.
[I 2026-02-02 21:54:53,519] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.00795688512312417, 'n_estimators': 467, 'min_child_weight': 9, 'max_delta_step': 2, 'subsample': 0.8299920230170895, 'colsample_bytree': 0.8903333201207295, 'colsample_bylevel': 0.7331204869596775, 'colsample_bynode': 0.7177903470136039, 'gamma': 1.2092614545022584, 'reg_alpha': 0.9310276780589921, 'reg_lambda': 8.972157579533267, 'scale_pos_weight': 18.10794308610328, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 230, 'min_split_loss': 4.4354321213255865, 'max_bin': 428}. Best is trial 6 with value: 0.13721846846846847.
[I 2026-02-02 21:54:53,726] Trial 10 finished with value: 0.3533513513513514 and parameters: {'max_depth': 12, 'learning_rate': 0.22767246707533523, 'n_estimators': 53, 'min_child_weight': 1, 'max_delta_step': 9, 'subsample': 0.71318415356318, 'colsample_bytree': 0.9820282966949807, 'colsample_bylevel': 0.9856172116162216, 'colsample_bynode': 0.5689638013591753, 'gamma': 4.174743509527138, 'reg_alpha': 3.8614380812971323, 'reg_lambda': 4.399492045282824, 'scale_pos_weight': 6.52441096075992, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 174, 'min_split_loss': 3.035921370166128, 'max_bin': 512}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:53,950] Trial 11 finished with value: 0.32632432432432434 and parameters: {'max_depth': 12, 'learning_rate': 0.26181255259978864, 'n_estimators': 83, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.7126325384062089, 'colsample_bytree': 0.9945127062027537, 'colsample_bylevel': 0.9967462283558063, 'colsample_bynode': 0.5690652783408267, 'gamma': 4.376902630752761, 'reg_alpha': 4.018863257283632, 'reg_lambda': 4.565433566509627, 'scale_pos_weight': 6.269257107832177, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 171, 'min_split_loss': 3.1143937745945793, 'max_bin': 512}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:54,174] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.17328230739026962, 'n_estimators': 61, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.714700836759475, 'colsample_bytree': 0.9894920975667472, 'colsample_bylevel': 0.9968484310338426, 'colsample_bynode': 0.5925101071718903, 'gamma': 4.743802698071374, 'reg_alpha': 4.288273188344727, 'reg_lambda': 4.724026819032199, 'scale_pos_weight': 8.105576409090107, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 161, 'min_split_loss': 3.352725713024431, 'max_bin': 504}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:54,533] Trial 13 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.11816056952075882, 'n_estimators': 122, 'min_child_weight': 2, 'max_delta_step': 8, 'subsample': 0.7884745869448389, 'colsample_bytree': 0.9970694659293917, 'colsample_bylevel': 0.5688485557473757, 'colsample_bynode': 0.6030900672809134, 'gamma': 3.9838351137817747, 'reg_alpha': 2.6628900136048363, 'reg_lambda': 4.914531278934391, 'scale_pos_weight': 7.301752398226039, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 232, 'min_split_loss': 3.124765961888235, 'max_bin': 434}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:54,876] Trial 14 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.26019527928999, 'n_estimators': 119, 'min_child_weight': 3, 'max_delta_step': 7, 'subsample': 0.67455198366465, 'colsample_bytree': 0.7626957551933566, 'colsample_bylevel': 0.9762806439749894, 'colsample_bynode': 0.5455712685833589, 'gamma': 4.157593261184087, 'reg_alpha': 5.335186133356887, 'reg_lambda': 3.975384398581193, 'scale_pos_weight': 6.719579373180074, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 149, 'min_split_loss': 2.8509324825591182, 'max_bin': 374}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:55,149] Trial 15 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.12424206446727844, 'n_estimators': 116, 'min_child_weight': 8, 'max_delta_step': 6, 'subsample': 0.5927174272601871, 'colsample_bytree': 0.9196483355228751, 'colsample_bylevel': 0.40697257697653194, 'colsample_bynode': 0.6346585012462289, 'gamma': 3.418111155099192, 'reg_alpha': 2.813321835198381, 'reg_lambda': 6.6933280770424215, 'scale_pos_weight': 12.939797188364821, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 200, 'min_split_loss': 3.74824933215402, 'max_bin': 470}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:55,799] Trial 16 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.03434179310927581, 'n_estimators': 282, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.9756357791297634, 'colsample_bytree': 0.807845567083049, 'colsample_bylevel': 0.8139566329840936, 'colsample_bynode': 0.8880504745353941, 'gamma': 4.272159525907846, 'reg_alpha': 3.8559082359026844, 'reg_lambda': 5.818903279310672, 'scale_pos_weight': 5.425155854360744, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 253, 'min_split_loss': 2.515455607674821, 'max_bin': 465}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:55,971] Trial 17 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.2992804570977294, 'n_estimators': 53, 'min_child_weight': 3, 'max_delta_step': 8, 'subsample': 0.7292397071109628, 'colsample_bytree': 0.9439525687219475, 'colsample_bylevel': 0.6146109364289585, 'colsample_bynode': 0.5153361547596588, 'gamma': 2.143667952488051, 'reg_alpha': 5.451617479073246, 'reg_lambda': 3.4464651053125817, 'scale_pos_weight': 9.919605685788152, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 90, 'min_split_loss': 3.8854781763157407, 'max_bin': 373}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:56,332] Trial 18 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.11402392974336452, 'n_estimators': 143, 'min_child_weight': 2, 'max_delta_step': 5, 'subsample': 0.82344211012971, 'colsample_bytree': 0.6972191186655672, 'colsample_bylevel': 0.9434579587088643, 'colsample_bynode': 0.6619891626202123, 'gamma': 3.4326176238924893, 'reg_alpha': 2.1074591736960278, 'reg_lambda': 5.730998571203722, 'scale_pos_weight': 4.8209776974538086, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 170, 'min_split_loss': 1.2382855501603451, 'max_bin': 470}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:57,300] Trial 19 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.022113467285250165, 'n_estimators': 271, 'min_child_weight': 5, 'max_delta_step': 9, 'subsample': 0.5317314701657627, 'colsample_bytree': 0.8464378050813091, 'colsample_bylevel': 0.8252447186735188, 'colsample_bynode': 0.8063543248356785, 'gamma': 4.526868594044793, 'reg_alpha': 6.871416849884073, 'reg_lambda': 4.21750624193076, 'scale_pos_weight': 9.71089039659423, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 211, 'min_split_loss': 2.686895996988028, 'max_bin': 512}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:57,867] Trial 20 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.1681351716291161, 'n_estimators': 242, 'min_child_weight': 7, 'max_delta_step': 7, 'subsample': 0.6280241166652184, 'colsample_bytree': 0.9715023248625198, 'colsample_bylevel': 0.6231702059875769, 'colsample_bynode': 0.499300612613056, 'gamma': 3.787608372349923, 'reg_alpha': 3.637584650067376, 'reg_lambda': 3.4468947341569525, 'scale_pos_weight': 12.937380656128994, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 129, 'min_split_loss': 3.6670915535281283, 'max_bin': 130}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:58,298] Trial 21 finished with value: 0.21969447708578144 and parameters: {'max_depth': 13, 'learning_rate': 0.18642842068567572, 'n_estimators': 95, 'min_child_weight': 2, 'max_delta_step': 10, 'subsample': 0.6984539682355769, 'colsample_bytree': 0.8886559434424287, 'colsample_bylevel': 0.9167686636804903, 'colsample_bynode': 0.4776165305910416, 'gamma': 2.9745537889257174, 'reg_alpha': 4.6998151195900375, 'reg_lambda': 2.6574300509182534, 'scale_pos_weight': 3.3380809592881846, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 173, 'min_split_loss': 1.9384389906537556, 'max_bin': 508}. Best is trial 10 with value: 0.3533513513513514.
[I 2026-02-02 21:54:58,583] Trial 22 finished with value: 0.3537149877149877 and parameters: {'max_depth': 14, 'learning_rate': 0.09345229344329939, 'n_estimators': 86, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.6721990183833476, 'colsample_bytree': 0.9256321666948388, 'colsample_bylevel': 0.9631227981765501, 'colsample_bynode': 0.4818728691601044, 'gamma': 2.9347404562492447, 'reg_alpha': 5.069793722433016, 'reg_lambda': 3.246913570810357, 'scale_pos_weight': 5.534515634480517, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 183, 'min_split_loss': 2.1766193370878653, 'max_bin': 453}. Best is trial 22 with value: 0.3537149877149877.
[I 2026-02-02 21:54:59,156] Trial 23 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.08836420931932232, 'n_estimators': 155, 'min_child_weight': 1, 'max_delta_step': 9, 'subsample': 0.7594810469168436, 'colsample_bytree': 0.9329182136038049, 'colsample_bylevel': 0.9891823930265646, 'colsample_bynode': 0.5540077237220687, 'gamma': 1.8998124914070689, 'reg_alpha': 6.020412838169907, 'reg_lambda': 5.562958584731771, 'scale_pos_weight': 8.238222055004265, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 150, 'min_split_loss': 1.230341406761042, 'max_bin': 458}. Best is trial 22 with value: 0.3537149877149877.
[I 2026-02-02 21:54:59,470] Trial 24 finished with value: 0.0 and parameters: {'max_depth': 11, 'learning_rate': 0.1305504489227142, 'n_estimators': 89, 'min_child_weight': 3, 'max_delta_step': 8, 'subsample': 0.6581707301396353, 'colsample_bytree': 0.9976158136423581, 'colsample_bylevel': 0.8816419111224911, 'colsample_bynode': 0.6446457690396155, 'gamma': 2.96512489187772, 'reg_alpha': 3.420688209635638, 'reg_lambda': 3.1634487428229234, 'scale_pos_weight': 5.726465847432939, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 217, 'min_split_loss': 2.9624959017943238, 'max_bin': 397}. Best is trial 22 with value: 0.3537149877149877.
[I 2026-02-02 21:54:59,706] Trial 25 finished with value: 0.3805658783783784 and parameters: {'max_depth': 14, 'learning_rate': 0.09066800724420553, 'n_estimators': 50, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.5778610056515864, 'colsample_bytree': 0.9355610503993412, 'colsample_bylevel': 0.9511313444595396, 'colsample_bynode': 0.5781686683396863, 'gamma': 4.45138078254226, 'reg_alpha': 4.922320391020824, 'reg_lambda': 0.8863831192564904, 'scale_pos_weight': 6.767639762308867, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 200, 'min_split_loss': 2.2959360913775924, 'max_bin': 447}. Best is trial 25 with value: 0.3805658783783784.
[I 2026-02-02 21:54:59,940] Trial 26 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.04901440962534956, 'n_estimators': 156, 'min_child_weight': 3, 'max_delta_step': 9, 'subsample': 0.5666554307930975, 'colsample_bytree': 0.7885885298150965, 'colsample_bylevel': 0.772859683910545, 'colsample_bynode': 0.484603725691899, 'gamma': 3.800884082088612, 'reg_alpha': 8.261908287058644, 'reg_lambda': 0.5585727541478889, 'scale_pos_weight': 11.65206148664454, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 255, 'min_split_loss': 2.231887543657713, 'max_bin': 334}. Best is trial 25 with value: 0.3805658783783784.
[I 2026-02-02 21:55:00,223] Trial 27 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.08135890750511406, 'n_estimators': 50, 'min_child_weight': 2, 'max_delta_step': 7, 'subsample': 0.6364755952464735, 'colsample_bytree': 0.8447709567448617, 'colsample_bylevel': 0.9486317374902726, 'colsample_bynode': 0.6043902276144635, 'gamma': 4.998433837184765, 'reg_alpha': 5.101768474377273, 'reg_lambda': 1.041032511947535, 'scale_pos_weight': 8.669373350973238, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 190, 'min_split_loss': 0.8056525956530032, 'max_bin': 437}. Best is trial 25 with value: 0.3805658783783784.
[I 2026-02-02 21:55:00,976] Trial 28 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.04779355256701441, 'n_estimators': 113, 'min_child_weight': 1, 'max_delta_step': 10, 'subsample': 0.5485353619623159, 'colsample_bytree': 0.9404455158479501, 'colsample_bylevel': 0.8753301507181483, 'colsample_bynode': 0.6793033206642956, 'gamma': 4.6049894347606655, 'reg_alpha': 1.9603232665024444, 'reg_lambda': 1.314921010241907, 'scale_pos_weight': 4.6100930665968285, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 144, 'min_split_loss': 1.5661630267913638, 'max_bin': 377}. Best is trial 25 with value: 0.3805658783783784.
[I 2026-02-02 21:55:01,250] Trial 29 finished with value: 0.4614594594594595 and parameters: {'max_depth': 15, 'learning_rate': 0.02805167123644583, 'n_estimators': 234, 'min_child_weight': 5, 'max_delta_step': 8, 'subsample': 0.5916638087066872, 'colsample_bytree': 0.7216731059131875, 'colsample_bylevel': 0.9409865580135862, 'colsample_bynode': 0.4678376975519757, 'gamma': 3.279809433305326, 'reg_alpha': 6.191200147560616, 'reg_lambda': 3.0173948509796844, 'scale_pos_weight': 7.291024275251861, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 221, 'min_split_loss': 2.3614631954545118, 'max_bin': 303}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:01,762] Trial 30 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.02294663572425414, 'n_estimators': 350, 'min_child_weight': 5, 'max_delta_step': 6, 'subsample': 0.596013704475711, 'colsample_bytree': 0.717395341958325, 'colsample_bylevel': 0.9411475784459488, 'colsample_bynode': 0.46400693555083977, 'gamma': 3.336517983452623, 'reg_alpha': 7.1656367121793405, 'reg_lambda': 0.7184705323300484, 'scale_pos_weight': 8.978016128941977, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 232, 'min_split_loss': 2.262814237831213, 'max_bin': 278}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:01,992] Trial 31 finished with value: 0.4347512730121426 and parameters: {'max_depth': 14, 'learning_rate': 0.027534040331871026, 'n_estimators': 83, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.5944609559581293, 'colsample_bytree': 0.8782271824612509, 'colsample_bylevel': 0.9099470246019478, 'colsample_bynode': 0.5272001046312624, 'gamma': 3.7857508460972924, 'reg_alpha': 5.592949549223634, 'reg_lambda': 2.9218601265080455, 'scale_pos_weight': 7.095648590563213, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 211, 'min_split_loss': 2.350619279462435, 'max_bin': 309}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:02,286] Trial 32 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.027171778826134935, 'n_estimators': 227, 'min_child_weight': 8, 'max_delta_step': 8, 'subsample': 0.5793123238132397, 'colsample_bytree': 0.40894960382690426, 'colsample_bylevel': 0.9012551345299822, 'colsample_bynode': 0.515590262970854, 'gamma': 3.6662115935706945, 'reg_alpha': 6.03562456320522, 'reg_lambda': 2.901027402226296, 'scale_pos_weight': 7.5864817062904395, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 212, 'min_split_loss': 2.3490342833542024, 'max_bin': 314}. Best is trial 29 with value: 0.4614594594594595.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:55:02,533] Trial 33 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.015770542093386384, 'n_estimators': 157, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.6067827049461495, 'colsample_bytree': 0.7175320085040979, 'colsample_bylevel': 0.8311694173189011, 'colsample_bynode': 0.46624143460341716, 'gamma': 2.805985675172747, 'reg_alpha': 5.821611228491469, 'reg_lambda': 3.6452956997519848, 'scale_pos_weight': 2.0608343243125997, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 238, 'min_split_loss': 2.0166752634071194, 'max_bin': 258}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:02,833] Trial 34 finished with value: 0.1374078624078624 and parameters: {'max_depth': 5, 'learning_rate': 0.030588670899985196, 'n_estimators': 89, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.5545918407785169, 'colsample_bytree': 0.8697932377812064, 'colsample_bylevel': 0.9442558610398512, 'colsample_bynode': 0.8035819588627684, 'gamma': 3.294823340841484, 'reg_alpha': 4.918703287018977, 'reg_lambda': 1.930263444964858, 'scale_pos_weight': 4.361418320552243, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 201, 'min_split_loss': 2.5579688414069186, 'max_bin': 232}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:03,131] Trial 35 finished with value: 0.08483108108108109 and parameters: {'max_depth': 13, 'learning_rate': 0.04629185216615121, 'n_estimators': 393, 'min_child_weight': 10, 'max_delta_step': 8, 'subsample': 0.6677953260561759, 'colsample_bytree': 0.5849533840133874, 'colsample_bylevel': 0.8544603788750742, 'colsample_bynode': 0.5144588438820705, 'gamma': 2.6715658675792917, 'reg_alpha': 7.613992511651735, 'reg_lambda': 2.855163727964341, 'scale_pos_weight': 2.2751739579252765, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 219, 'min_split_loss': 1.5502464338404405, 'max_bin': 296}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:03,781] Trial 36 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.00524783632103996, 'n_estimators': 315, 'min_child_weight': 8, 'max_delta_step': 6, 'subsample': 0.5016826140767412, 'colsample_bytree': 0.8178949264357647, 'colsample_bylevel': 0.7714129315006609, 'colsample_bynode': 0.44929728549621895, 'gamma': 3.928688966305366, 'reg_alpha': 6.444614084222539, 'reg_lambda': 0.0807220681808638, 'scale_pos_weight': 11.12399739272219, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 188, 'min_split_loss': 0.664131303516414, 'max_bin': 345}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:04,103] Trial 37 finished with value: 0.21843843843843844 and parameters: {'max_depth': 9, 'learning_rate': 0.018975603345775586, 'n_estimators': 221, 'min_child_weight': 5, 'max_delta_step': 4, 'subsample': 0.6250562539841238, 'colsample_bytree': 0.5134925509494237, 'colsample_bylevel': 0.9066056580818234, 'colsample_bynode': 0.41953347724188644, 'gamma': 2.207102887417861, 'reg_alpha': 4.708240156883281, 'reg_lambda': 1.4525684257120688, 'scale_pos_weight': 5.699457112958993, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 118, 'min_split_loss': 1.526420723595123, 'max_bin': 300}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:05,147] Trial 38 finished with value: 0.3538041815400306 and parameters: {'max_depth': 15, 'learning_rate': 0.010325868975717448, 'n_estimators': 179, 'min_child_weight': 9, 'max_delta_step': 9, 'subsample': 0.6482412528879159, 'colsample_bytree': 0.9153941249829505, 'colsample_bylevel': 0.9630506448714119, 'colsample_bynode': 0.624121876768506, 'gamma': 3.1727440065356833, 'reg_alpha': 5.618547439702097, 'reg_lambda': 2.1911582611409184, 'scale_pos_weight': 7.149376015082636, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 247, 'min_split_loss': 1.9885185301326858, 'max_bin': 222}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:05,373] Trial 39 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.0111168414580725, 'n_estimators': 186, 'min_child_weight': 9, 'max_delta_step': 7, 'subsample': 0.5372405164548955, 'colsample_bytree': 0.6529707184521641, 'colsample_bylevel': 0.8773225868533917, 'colsample_bynode': 0.6319993982528661, 'gamma': 3.20984148158266, 'reg_alpha': 7.667260160890099, 'reg_lambda': 2.0182582800150524, 'scale_pos_weight': 15.168725023207731, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 3, 'min_split_loss': 2.6678129531842876, 'max_bin': 225}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:05,931] Trial 40 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.00777368006139082, 'n_estimators': 248, 'min_child_weight': 9, 'max_delta_step': 9, 'subsample': 0.6449863977187894, 'colsample_bytree': 0.7592480360340246, 'colsample_bylevel': 0.9223405785221895, 'colsample_bynode': 0.7546578371522265, 'gamma': 3.627426256602196, 'reg_alpha': 8.717966162983013, 'reg_lambda': 2.3751293967673877, 'scale_pos_weight': 9.31936490996824, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 243, 'min_split_loss': 1.8231844027805257, 'max_bin': 206}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:06,299] Trial 41 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.040233159761857124, 'n_estimators': 138, 'min_child_weight': 10, 'max_delta_step': 10, 'subsample': 0.5700051345945261, 'colsample_bytree': 0.9113856531765729, 'colsample_bylevel': 0.9591211498856679, 'colsample_bynode': 0.5843046747243008, 'gamma': 3.052247907100532, 'reg_alpha': 6.42854389423941, 'reg_lambda': 1.7169699584532614, 'scale_pos_weight': 7.180298122286527, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 224, 'min_split_loss': 2.1258143127977718, 'max_bin': 273}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:06,671] Trial 42 finished with value: 0.32682432432432434 and parameters: {'max_depth': 15, 'learning_rate': 0.05939377595544766, 'n_estimators': 99, 'min_child_weight': 6, 'max_delta_step': 9, 'subsample': 0.686926840495343, 'colsample_bytree': 0.9593598908950937, 'colsample_bylevel': 0.9671601698388015, 'colsample_bynode': 0.5319282856562276, 'gamma': 1.832146665974242, 'reg_alpha': 5.5891602729824825, 'reg_lambda': 0.9255765264800211, 'scale_pos_weight': 5.278391236843037, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 202, 'min_split_loss': 2.425855356275972, 'max_bin': 345}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:06,993] Trial 43 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.01286980924630623, 'n_estimators': 199, 'min_child_weight': 4, 'max_delta_step': 8, 'subsample': 0.6053741059219493, 'colsample_bytree': 0.8688521802850024, 'colsample_bylevel': 0.9298625545540727, 'colsample_bynode': 0.40187711658085795, 'gamma': 2.4140751444372714, 'reg_alpha': 4.456940607167056, 'reg_lambda': 2.50849336690502, 'scale_pos_weight': 6.349503550418578, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 245, 'min_split_loss': 1.7544931054682888, 'max_bin': 197}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:07,187] Trial 44 finished with value: 0.19131040131040133 and parameters: {'max_depth': 14, 'learning_rate': 0.08245551735023722, 'n_estimators': 73, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.6510297079508115, 'colsample_bytree': 0.9015402845636867, 'colsample_bylevel': 0.854316370465792, 'colsample_bynode': 0.6833123104188761, 'gamma': 2.7378743032682715, 'reg_alpha': 5.1914832849808334, 'reg_lambda': 3.651927820859275, 'scale_pos_weight': 3.881768646153225, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 211, 'min_split_loss': 2.1031759824750473, 'max_bin': 149}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:07,524] Trial 45 finished with value: 0.3535927306616962 and parameters: {'max_depth': 13, 'learning_rate': 0.00988503811679537, 'n_estimators': 169, 'min_child_weight': 8, 'max_delta_step': 9, 'subsample': 0.6127705920668949, 'colsample_bytree': 0.8650219124978064, 'colsample_bylevel': 0.8948156936933348, 'colsample_bynode': 0.44130916981741874, 'gamma': 4.027263683275779, 'reg_alpha': 6.663939378487865, 'reg_lambda': 8.987319379735801, 'scale_pos_weight': 7.684281861187972, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 69, 'min_split_loss': 2.7569880575663026, 'max_bin': 249}. Best is trial 29 with value: 0.4614594594594595.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:55:07,870] Trial 46 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.006022414709183384, 'n_estimators': 212, 'min_child_weight': 6, 'max_delta_step': 10, 'subsample': 0.5751974652226473, 'colsample_bytree': 0.9587166215113213, 'colsample_bylevel': 0.9703076089888533, 'colsample_bynode': 0.6135154743754306, 'gamma': 3.14998367245953, 'reg_alpha': 6.203825128838996, 'reg_lambda': 3.0019052746564654, 'scale_pos_weight': 2.56647088112381, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 185, 'min_split_loss': 3.2996681025145485, 'max_bin': 415}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:08,074] Trial 47 finished with value: 0.08380835380835382 and parameters: {'max_depth': 12, 'learning_rate': 0.016829489855796274, 'n_estimators': 72, 'min_child_weight': 9, 'max_delta_step': 8, 'subsample': 0.5106777956746407, 'colsample_bytree': 0.8264667475027827, 'colsample_bylevel': 0.9654743404399069, 'colsample_bynode': 0.564548518144719, 'gamma': 3.569501049018885, 'reg_alpha': 7.2715703115477766, 'reg_lambda': 4.04412723531038, 'scale_pos_weight': 6.845914704075418, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 161, 'min_split_loss': 2.3278225024344943, 'max_bin': 483}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:08,794] Trial 48 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.026188209991761288, 'n_estimators': 289, 'min_child_weight': 4, 'max_delta_step': 9, 'subsample': 0.7335658037236431, 'colsample_bytree': 0.9095161495819454, 'colsample_bylevel': 0.6635193456354027, 'colsample_bynode': 0.5353285810912445, 'gamma': 4.81047286980914, 'reg_alpha': 3.319685570646607, 'reg_lambda': 2.2897309013564016, 'scale_pos_weight': 19.759068042046465, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 234, 'min_split_loss': 0.9337861879438556, 'max_bin': 358}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:09,327] Trial 49 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.03796333339264996, 'n_estimators': 126, 'min_child_weight': 5, 'max_delta_step': 10, 'subsample': 0.679164626449974, 'colsample_bytree': 0.7971458428254833, 'colsample_bylevel': 0.4983197151119929, 'colsample_bynode': 0.9653241569689999, 'gamma': 0.6649992546894374, 'reg_alpha': 5.693755938923144, 'reg_lambda': 0.4229399161114409, 'scale_pos_weight': 10.30216253530615, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 224, 'min_split_loss': 1.4086182281722317, 'max_bin': 322}. Best is trial 29 with value: 0.4614594594594595.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:55:09,807] Trial 50 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.09949450170160976, 'n_estimators': 105, 'min_child_weight': 4, 'max_delta_step': 1, 'subsample': 0.5818553915742474, 'colsample_bytree': 0.6045747934127993, 'colsample_bylevel': 0.7947937037624382, 'colsample_bynode': 0.5768561104829175, 'gamma': 4.340559153263046, 'reg_alpha': 4.341356160300686, 'reg_lambda': 1.2633069372328778, 'scale_pos_weight': 1.3258724273076314, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 206, 'min_split_loss': 1.7923453148073931, 'max_bin': 395}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:10,352] Trial 51 finished with value: 0.24597051597051597 and parameters: {'max_depth': 13, 'learning_rate': 0.007014726911131919, 'n_estimators': 174, 'min_child_weight': 8, 'max_delta_step': 9, 'subsample': 0.6099926201252741, 'colsample_bytree': 0.8838627899277368, 'colsample_bylevel': 0.8905898338135135, 'colsample_bynode': 0.45062650772364365, 'gamma': 4.0440373847659545, 'reg_alpha': 6.82143554899494, 'reg_lambda': 9.917710371058796, 'scale_pos_weight': 7.801881132040133, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 64, 'min_split_loss': 2.797012756938071, 'max_bin': 265}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:10,893] Trial 52 finished with value: 0.1374078624078624 and parameters: {'max_depth': 15, 'learning_rate': 0.009520249284595673, 'n_estimators': 171, 'min_child_weight': 9, 'max_delta_step': 9, 'subsample': 0.6197612661625885, 'colsample_bytree': 0.8594738645879894, 'colsample_bylevel': 0.9175557119439154, 'colsample_bynode': 0.49212846244437364, 'gamma': 4.449665409451744, 'reg_alpha': 6.462088750458969, 'reg_lambda': 8.957733895365482, 'scale_pos_weight': 6.165527710498887, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 38, 'min_split_loss': 2.5884509148842327, 'max_bin': 222}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:12,014] Trial 53 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.010393840741129128, 'n_estimators': 258, 'min_child_weight': 8, 'max_delta_step': 8, 'subsample': 0.6359088161784858, 'colsample_bytree': 0.9325308853679476, 'colsample_bylevel': 0.9945340668240557, 'colsample_bynode': 0.4384176492472356, 'gamma': 3.8318704427855534, 'reg_alpha': 5.402466642766243, 'reg_lambda': 8.145654606749678, 'scale_pos_weight': 8.124921383765756, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 76, 'min_split_loss': 2.8748219092231375, 'max_bin': 243}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:12,442] Trial 54 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.012490904924311756, 'n_estimators': 209, 'min_child_weight': 10, 'max_delta_step': 10, 'subsample': 0.5515916055198445, 'colsample_bytree': 0.9620613387520681, 'colsample_bylevel': 0.7396075049647197, 'colsample_bynode': 0.42089458385105066, 'gamma': 4.128192158692883, 'reg_alpha': 8.056810096519287, 'reg_lambda': 5.179521533056174, 'scale_pos_weight': 6.956881621857006, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 108, 'min_split_loss': 3.125765244603305, 'max_bin': 289}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:13,132] Trial 55 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.0569630854903828, 'n_estimators': 467, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.5275918423381389, 'colsample_bytree': 0.8798588193729558, 'colsample_bylevel': 0.8693199301966239, 'colsample_bynode': 0.5049736748312182, 'gamma': 3.5027888229503423, 'reg_alpha': 4.863510869118811, 'reg_lambda': 3.2566179355547193, 'scale_pos_weight': 8.781837324173754, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 249, 'min_split_loss': 2.43068391319031, 'max_bin': 245}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:13,699] Trial 56 finished with value: 0.299588963963964 and parameters: {'max_depth': 15, 'learning_rate': 0.0722819013890037, 'n_estimators': 135, 'min_child_weight': 8, 'max_delta_step': 7, 'subsample': 0.8897664852610536, 'colsample_bytree': 0.7763672685709282, 'colsample_bylevel': 0.8973892251233132, 'colsample_bynode': 0.5385014547735443, 'gamma': 4.672561462404772, 'reg_alpha': 7.250802718493082, 'reg_lambda': 6.556834686501078, 'scale_pos_weight': 5.05155485351615, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 196, 'min_split_loss': 1.973602291953553, 'max_bin': 451}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:14,095] Trial 57 finished with value: 0.032027027027027026 and parameters: {'max_depth': 13, 'learning_rate': 0.019480286015680436, 'n_estimators': 73, 'min_child_weight': 2, 'max_delta_step': 10, 'subsample': 0.6924716074479192, 'colsample_bytree': 0.7406388531398707, 'colsample_bylevel': 0.9316404122341749, 'colsample_bynode': 0.46901903078958856, 'gamma': 2.5422375364388397, 'reg_alpha': 9.872367329046094, 'reg_lambda': 1.7018853015869917, 'scale_pos_weight': 6.088477968925717, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 180, 'min_split_loss': 4.06860525525652, 'max_bin': 487}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:15,243] Trial 58 finished with value: 0.032027027027027026 and parameters: {'max_depth': 11, 'learning_rate': 0.008781609330842714, 'n_estimators': 233, 'min_child_weight': 9, 'max_delta_step': 9, 'subsample': 0.585573233227607, 'colsample_bytree': 0.9277918599887927, 'colsample_bylevel': 0.9792382762249124, 'colsample_bynode': 0.6169859990479286, 'gamma': 3.71517487543577, 'reg_alpha': 5.845039634810991, 'reg_lambda': 9.190330362381033, 'scale_pos_weight': 4.299420965422925, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 28, 'min_split_loss': 3.506225967118629, 'max_bin': 309}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:16,262] Trial 59 finished with value: 0.4076442113755547 and parameters: {'max_depth': 14, 'learning_rate': 0.14191132736443077, 'n_estimators': 298, 'min_child_weight': 2, 'max_delta_step': 5, 'subsample': 0.659092478200336, 'colsample_bytree': 0.8583079520548467, 'colsample_bylevel': 0.8371700205031167, 'colsample_bynode': 0.5557396417364181, 'gamma': 2.870857569782657, 'reg_alpha': 6.767321197423245, 'reg_lambda': 3.7853254534323293, 'scale_pos_weight': 7.432092431463565, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 225, 'min_split_loss': 2.1689305141311968, 'max_bin': 181}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:17,019] Trial 60 finished with value: 0.21929313929313932 and parameters: {'max_depth': 14, 'learning_rate': 0.142961405516314, 'n_estimators': 301, 'min_child_weight': 1, 'max_delta_step': 4, 'subsample': 0.6544472715979776, 'colsample_bytree': 0.8356865895204361, 'colsample_bylevel': 0.805992462949279, 'colsample_bynode': 0.553220408641939, 'gamma': 2.9059893881533982, 'reg_alpha': 3.974347212221756, 'reg_lambda': 3.812656471884382, 'scale_pos_weight': 3.423258348504789, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 223, 'min_split_loss': 2.175807892076275, 'max_bin': 174}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:17,404] Trial 61 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.15362104840252602, 'n_estimators': 64, 'min_child_weight': 2, 'max_delta_step': 5, 'subsample': 0.6221573347780436, 'colsample_bytree': 0.8585612000101692, 'colsample_bylevel': 0.8365497845620712, 'colsample_bynode': 0.5228829317861191, 'gamma': 3.1479980159782137, 'reg_alpha': 6.592382599793236, 'reg_lambda': 4.436266489245351, 'scale_pos_weight': 8.422543781759384, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 241, 'min_split_loss': 2.7036818790639185, 'max_bin': 192}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:18,277] Trial 62 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.09942002925799727, 'n_estimators': 361, 'min_child_weight': 1, 'max_delta_step': 4, 'subsample': 0.6625350455880598, 'colsample_bytree': 0.9030080196694762, 'colsample_bylevel': 0.9515648200573651, 'colsample_bynode': 0.49522153728341944, 'gamma': 3.398916753969877, 'reg_alpha': 6.1790895501415015, 'reg_lambda': 3.3270426694598205, 'scale_pos_weight': 7.539198195995571, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 228, 'min_split_loss': 1.7119791817619991, 'max_bin': 213}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:18,559] Trial 63 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.22562655720253796, 'n_estimators': 81, 'min_child_weight': 2, 'max_delta_step': 5, 'subsample': 0.7797109604861157, 'colsample_bytree': 0.9746342609844311, 'colsample_bylevel': 0.9994064730994675, 'colsample_bynode': 0.47995056430570693, 'gamma': 3.949584053243006, 'reg_alpha': 5.329868780847897, 'reg_lambda': 5.138854647098101, 'scale_pos_weight': 9.65460926651948, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 164, 'min_split_loss': 1.9664628660352026, 'max_bin': 159}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:19,273] Trial 64 finished with value: 0.35338260135135136 and parameters: {'max_depth': 13, 'learning_rate': 0.10144157787501573, 'n_estimators': 263, 'min_child_weight': 1, 'max_delta_step': 6, 'subsample': 0.5969842989070105, 'colsample_bytree': 0.6679907595021157, 'colsample_bylevel': 0.9027270113187326, 'colsample_bynode': 0.5983762792541835, 'gamma': 4.291831375315085, 'reg_alpha': 6.982961046369405, 'reg_lambda': 2.7055019990034213, 'scale_pos_weight': 6.487534129867554, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 210, 'min_split_loss': 2.452502870259306, 'max_bin': 194}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:20,489] Trial 65 finished with value: 0.35338260135135136 and parameters: {'max_depth': 15, 'learning_rate': 0.03298691493693799, 'n_estimators': 334, 'min_child_weight': 3, 'max_delta_step': 3, 'subsample': 0.7049268334602788, 'colsample_bytree': 0.94812823215501, 'colsample_bylevel': 0.930308509407298, 'colsample_bynode': 0.5585104592359128, 'gamma': 2.660227346755032, 'reg_alpha': 5.699462583861254, 'reg_lambda': 2.131761614907602, 'scale_pos_weight': 7.346032661392711, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 254, 'min_split_loss': 2.2283845035125847, 'max_bin': 283}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:21,114] Trial 66 finished with value: 0.2997417417417418 and parameters: {'max_depth': 14, 'learning_rate': 0.06862642257598175, 'n_estimators': 108, 'min_child_weight': 1, 'max_delta_step': 9, 'subsample': 0.7296766785843306, 'colsample_bytree': 0.9238458782033978, 'colsample_bylevel': 0.8601488298883105, 'colsample_bynode': 0.6540919264468973, 'gamma': 2.8538175314191854, 'reg_alpha': 5.112506833840247, 'reg_lambda': 4.6460393545217675, 'scale_pos_weight': 5.289734062957642, 'tree_method': 'approx', 'grow_policy': 'lossguide', 'max_leaves': 141, 'min_split_loss': 2.9934727028945485, 'max_bin': 262}. Best is trial 29 with value: 0.4614594594594595.
[I 2026-02-02 21:55:21,707] Trial 67 finished with value: 0.4615844594594595 and parameters: {'max_depth': 13, 'learning_rate': 0.1350566106378958, 'n_estimators': 161, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.6415984011354976, 'colsample_bytree': 0.8428454195919024, 'colsample_bylevel': 0.9547688124178584, 'colsample_bynode': 0.4485300225574171, 'gamma': 3.100884348436828, 'reg_alpha': 4.564811983297836, 'reg_lambda': 4.184449527372065, 'scale_pos_weight': 9.038323674302559, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 193, 'min_split_loss': 2.7814867671038255, 'max_bin': 184}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:23,449] Trial 68 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.12464904060615475, 'n_estimators': 310, 'min_child_weight': 6, 'max_delta_step': 7, 'subsample': 0.642742785346337, 'colsample_bytree': 0.8088970649189278, 'colsample_bylevel': 0.9525738615024925, 'colsample_bynode': 0.5786762972156052, 'gamma': 3.0521466334517644, 'reg_alpha': 4.648192316898838, 'reg_lambda': 4.040015465872816, 'scale_pos_weight': 11.228912180407963, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 194, 'min_split_loss': 2.076866285269862, 'max_bin': 130}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:24,046] Trial 69 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.18377197597568, 'n_estimators': 51, 'min_child_weight': 1, 'max_delta_step': 8, 'subsample': 0.5626440644663095, 'colsample_bytree': 0.8871143949909457, 'colsample_bylevel': 0.9714974549674097, 'colsample_bynode': 0.7211789670225525, 'gamma': 3.2525511032186083, 'reg_alpha': 4.191515393597897, 'reg_lambda': 4.251673299648573, 'scale_pos_weight': 12.313309159448687, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 182, 'min_split_loss': 3.217508590015963, 'max_bin': 165}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:25,057] Trial 70 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.21817000990710383, 'n_estimators': 190, 'min_child_weight': 6, 'max_delta_step': 8, 'subsample': 0.6753581244073027, 'colsample_bytree': 0.8457072746446648, 'colsample_bylevel': 0.9828408945853888, 'colsample_bynode': 0.4606417693700046, 'gamma': 2.4047012304323503, 'reg_alpha': 3.7774579005955045, 'reg_lambda': 3.1240009073758346, 'scale_pos_weight': 9.204769985934204, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 215, 'min_split_loss': 2.5596655795052583, 'max_bin': 184}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:25,676] Trial 71 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.024836514634844944, 'n_estimators': 165, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.608399804626294, 'colsample_bytree': 0.8587029316867474, 'colsample_bylevel': 0.9157003181883119, 'colsample_bynode': 0.4356391770167842, 'gamma': 3.453925442649944, 'reg_alpha': 5.951994068869716, 'reg_lambda': 3.5438060049072315, 'scale_pos_weight': 7.959907615185016, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 203, 'min_split_loss': 2.7778166108447397, 'max_bin': 151}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:26,087] Trial 72 finished with value: 0.38053222453222457 and parameters: {'max_depth': 13, 'learning_rate': 0.15115604352628503, 'n_estimators': 150, 'min_child_weight': 8, 'max_delta_step': 9, 'subsample': 0.6259404017576718, 'colsample_bytree': 0.8989873453057152, 'colsample_bylevel': 0.892717678519624, 'colsample_bynode': 0.41568892089131726, 'gamma': 3.0580255692770577, 'reg_alpha': 6.185488301456442, 'reg_lambda': 2.635234907970351, 'scale_pos_weight': 5.830347609256465, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 232, 'min_split_loss': 2.302444849554441, 'max_bin': 206}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:26,540] Trial 73 finished with value: 0.0 and parameters: {'max_depth': 14, 'learning_rate': 0.15554092037733624, 'n_estimators': 152, 'min_child_weight': 7, 'max_delta_step': 6, 'subsample': 0.6322749850307156, 'colsample_bytree': 0.9004234145914609, 'colsample_bylevel': 0.9378872601198704, 'colsample_bynode': 0.41058340274508354, 'gamma': 2.1567543411028662, 'reg_alpha': 5.403796701037724, 'reg_lambda': 2.5878950931084996, 'scale_pos_weight': 5.834837650851359, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 236, 'min_split_loss': 2.3522204328448297, 'max_bin': 185}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:26,988] Trial 74 finished with value: 0.0 and parameters: {'max_depth': 15, 'learning_rate': 0.13562909050246147, 'n_estimators': 123, 'min_child_weight': 2, 'max_delta_step': 10, 'subsample': 0.6603565209395705, 'colsample_bytree': 0.9446382127160975, 'colsample_bylevel': 0.8813738386347454, 'colsample_bynode': 0.48181368310482475, 'gamma': 3.0498726276804935, 'reg_alpha': 6.235825626867607, 'reg_lambda': 2.831281635183471, 'scale_pos_weight': 6.870287545435194, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 219, 'min_split_loss': 1.8686160731643509, 'max_bin': 233}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:27,928] Trial 75 finished with value: 0.0 and parameters: {'max_depth': 12, 'learning_rate': 0.11416773434971611, 'n_estimators': 433, 'min_child_weight': 8, 'max_delta_step': 7, 'subsample': 0.5935994811423351, 'colsample_bytree': 0.9188674259000835, 'colsample_bylevel': 0.8431525883028145, 'colsample_bynode': 0.45719841425770386, 'gamma': 2.61131661742884, 'reg_alpha': 0.08141493198826932, 'reg_lambda': 3.8855873105883383, 'scale_pos_weight': 8.508351878908778, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 229, 'min_split_loss': 2.248891782873029, 'max_bin': 207}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:28,256] Trial 76 finished with value: 0.299542195256481 and parameters: {'max_depth': 14, 'learning_rate': 0.0882034622470019, 'n_estimators': 140, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.8072891759350691, 'colsample_bytree': 0.9799278971745001, 'colsample_bylevel': 0.9138939670718004, 'colsample_bynode': 0.5047975946962452, 'gamma': 2.819524657295238, 'reg_alpha': 4.925583704770455, 'reg_lambda': 1.8683782229009347, 'scale_pos_weight': 4.749838165959236, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 193, 'min_split_loss': 4.946110729521658, 'max_bin': 145}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:28,611] Trial 77 finished with value: 0.3808783783783784 and parameters: {'max_depth': 13, 'learning_rate': 0.20038393375674757, 'n_estimators': 93, 'min_child_weight': 9, 'max_delta_step': 9, 'subsample': 0.6417791247861256, 'colsample_bytree': 0.47355280437702996, 'colsample_bylevel': 0.9473722625301559, 'colsample_bynode': 0.5235351986831066, 'gamma': 3.3342866665939974, 'reg_alpha': 4.699558846073726, 'reg_lambda': 2.31798961619467, 'scale_pos_weight': 5.663397898232892, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 247, 'min_split_loss': 2.5986701802162586, 'max_bin': 429}. Best is trial 67 with value: 0.4615844594594595.
[I 2026-02-02 21:55:29,521] Trial 78 finished with value: 0.0 and parameters: {'max_depth': 13, 'learning_rate': 0.1972796099410971, 'n_estimators': 93, 'min_child_weight': 10, 'max_delta_step': 8, 'subsample': 0.6306123214073149, 'colsample_bytree': 0.4507236810939468, 'colsample_bylevel': 0.9451045771626968, 'colsample_bynode': 0.6285281840982161, 'gamma': 3.318537252480026, 'reg_alpha': 4.4456867044434105, 'reg_lambda': 2.263715991223942, 'scale_pos_weight': 10.19156966902846, 'tree_method': 'hist', 'grow_policy': 'lossguide', 'max_leaves': 249, 'min_split_loss': 2.9395803863043453, 'max_bin': 438}. Best is trial 67 with value: 0.4615844594594595.

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

[I 2026-02-02 21:57:57,949] Trial 382 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.06817487666868674, 'n_estimators': 187, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9057114814072367, 'colsample_bytree': 0.454831266214088, 'colsample_bylevel': 0.8303256653294292, 'colsample_bynode': 0.5710286931575097, 'gamma': 0.5142944707499623, 'reg_alpha': 7.927690814572234, 'reg_lambda': 8.089403546311866, 'scale_pos_weight': 1.630866809339107, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 101, 'min_split_loss': 1.2251099830030976, 'max_bin': 167}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:57:58,366] Trial 383 finished with value: 0.5965945945945946 and parameters: {'max_depth': 8, 'learning_rate': 0.06291887359703566, 'n_estimators': 198, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.9113145558381401, 'colsample_bytree': 0.44256005127988535, 'colsample_bylevel': 0.8559065153707329, 'colsample_bynode': 0.603955914353459, 'gamma': 0.3993309581601735, 'reg_alpha': 8.1451996068388, 'reg_lambda': 8.38299406153413, 'scale_pos_weight': 9.017704085658591, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 95, 'min_split_loss': 1.4899716785121164, 'max_bin': 176}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:57:58,894] Trial 384 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.05803401714297124, 'n_estimators': 172, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.888363386206987, 'colsample_bytree': 0.4600992592898946, 'colsample_bylevel': 0.8116879946405556, 'colsample_bynode': 0.6405478786928863, 'gamma': 0.33506354686134016, 'reg_alpha': 0.5432928529541032, 'reg_lambda': 7.843342579746369, 'scale_pos_weight': 9.784102564639007, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 68, 'min_split_loss': 1.3147590307507417, 'max_bin': 196}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:57:59,237] Trial 385 finished with value: 0.5966129432184478 and parameters: {'max_depth': 7, 'learning_rate': 0.05330620281600681, 'n_estimators': 188, 'min_child_weight': 8, 'max_delta_step': 9, 'subsample': 0.9180280094357585, 'colsample_bytree': 0.4332430758242904, 'colsample_bylevel': 0.8205860819193435, 'colsample_bynode': 0.5812132304465027, 'gamma': 0.4704006159055043, 'reg_alpha': 0.883129056450771, 'reg_lambda': 7.253717506140293, 'scale_pos_weight': 8.666823628530576, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 173, 'min_split_loss': 1.423147858087162, 'max_bin': 184}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:57:59,538] Trial 386 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.06589903246786034, 'n_estimators': 197, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.8972129678250643, 'colsample_bytree': 0.4683949241606724, 'colsample_bylevel': 0.809347811539699, 'colsample_bynode': 0.6156273507383044, 'gamma': 0.2882445039264372, 'reg_alpha': 7.990312099049967, 'reg_lambda': 8.053412728331963, 'scale_pos_weight': 9.221863372297346, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 177, 'min_split_loss': 1.6754869471014586, 'max_bin': 157}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:57:59,787] Trial 387 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.07313039548452713, 'n_estimators': 179, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9025741059713066, 'colsample_bytree': 0.4876645192021757, 'colsample_bylevel': 0.7557843764666072, 'colsample_bynode': 0.5468866709156925, 'gamma': 0.07813430825425846, 'reg_alpha': 1.1192418246501799, 'reg_lambda': 8.270472490151155, 'scale_pos_weight': 10.327621496860747, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 135, 'min_split_loss': 0.9743058358854257, 'max_bin': 166}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:00,047] Trial 388 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.05999922438981056, 'n_estimators': 160, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9129331785512685, 'colsample_bytree': 0.41039701066436823, 'colsample_bylevel': 0.7658837663396959, 'colsample_bynode': 0.5638356055331456, 'gamma': 0.0005835567470987152, 'reg_alpha': 1.4276703914354203, 'reg_lambda': 7.885140437276693, 'scale_pos_weight': 9.609772943550512, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 42, 'min_split_loss': 1.5535743337903123, 'max_bin': 174}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:00,313] Trial 389 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.049101707060008305, 'n_estimators': 207, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.922680664183797, 'colsample_bytree': 0.4740928375524223, 'colsample_bylevel': 0.8426090021374647, 'colsample_bynode': 0.5917600613011234, 'gamma': 0.1858475621118211, 'reg_alpha': 7.765989496417402, 'reg_lambda': 8.563027599886468, 'scale_pos_weight': 8.726124394437495, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 184, 'min_split_loss': 1.1286637138846831, 'max_bin': 150}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:00,582] Trial 390 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.05392887682875473, 'n_estimators': 224, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.8823199148007916, 'colsample_bytree': 0.44415749327791326, 'colsample_bylevel': 0.798479721129654, 'colsample_bynode': 0.6081462508751103, 'gamma': 0.3636002406110194, 'reg_alpha': 2.1761185938123266, 'reg_lambda': 8.16976004729842, 'scale_pos_weight': 9.960761119069497, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 185, 'min_split_loss': 1.7135555103734992, 'max_bin': 212}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:00,853] Trial 391 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.04444901180016999, 'n_estimators': 201, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.9054900485661158, 'colsample_bytree': 0.49744425529732245, 'colsample_bylevel': 0.7824576493870323, 'colsample_bynode': 0.6261942639085525, 'gamma': 0.2563870783944084, 'reg_alpha': 0.22734957459364796, 'reg_lambda': 7.673784257027587, 'scale_pos_weight': 9.419865175201005, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 17, 'min_split_loss': 0.385739188292646, 'max_bin': 181}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:01,322] Trial 392 finished with value: 0.5965945945945946 and parameters: {'max_depth': 7, 'learning_rate': 0.06624001607322744, 'n_estimators': 189, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.8140316482726024, 'colsample_bytree': 0.4527581850338045, 'colsample_bylevel': 0.8206334617615618, 'colsample_bynode': 0.5770403274309378, 'gamma': 0.09984922945691806, 'reg_alpha': 0.6744741061049495, 'reg_lambda': 6.906776065867168, 'scale_pos_weight': 9.037002400689754, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 179, 'min_split_loss': 1.2597898672635566, 'max_bin': 190}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:01,614] Trial 393 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.07652967861500795, 'n_estimators': 217, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.8923107020533343, 'colsample_bytree': 0.4822874856442244, 'colsample_bylevel': 0.7692286391874326, 'colsample_bynode': 0.5994674657613939, 'gamma': 0.16868967635238769, 'reg_alpha': 0.43921841912006654, 'reg_lambda': 8.733642022753754, 'scale_pos_weight': 8.442202520497856, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 187, 'min_split_loss': 1.3800328074145891, 'max_bin': 162}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:01,864] Trial 394 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.06151028881397734, 'n_estimators': 176, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9181505583768916, 'colsample_bytree': 0.4199717328110651, 'colsample_bylevel': 0.8084636536914518, 'colsample_bynode': 0.628961990497799, 'gamma': 0.40523822545957605, 'reg_alpha': 0.8723004179166903, 'reg_lambda': 8.342230072313177, 'scale_pos_weight': 10.367158452439096, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 167, 'min_split_loss': 1.5243963903984095, 'max_bin': 173}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:02,146] Trial 395 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.0392266972140695, 'n_estimators': 166, 'min_child_weight': 8, 'max_delta_step': 10, 'subsample': 0.9002322748314115, 'colsample_bytree': 0.5035074593928834, 'colsample_bylevel': 0.8287947698810767, 'colsample_bynode': 0.5901133547148463, 'gamma': 0.25052628416556566, 'reg_alpha': 1.6056914210158282, 'reg_lambda': 7.60857563412166, 'scale_pos_weight': 10.765225296891023, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 181, 'min_split_loss': 1.4682489945851132, 'max_bin': 170}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:02,396] Trial 396 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.0692239822010525, 'n_estimators': 195, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.9271221414260714, 'colsample_bytree': 0.46390807045160426, 'colsample_bylevel': 0.7907130059812759, 'colsample_bynode': 0.535814474112437, 'gamma': 0.07986447111631995, 'reg_alpha': 8.24435041145931, 'reg_lambda': 8.93727493815029, 'scale_pos_weight': 11.865068605465469, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 144, 'min_split_loss': 1.5951268938583374, 'max_bin': 153}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:02,659] Trial 397 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.056135886131273835, 'n_estimators': 208, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.9099936877531318, 'colsample_bytree': 0.4053215416439913, 'colsample_bylevel': 0.778898995584559, 'colsample_bynode': 0.6151045781710066, 'gamma': 4.876854616936216, 'reg_alpha': 1.074307187861248, 'reg_lambda': 7.953672085402759, 'scale_pos_weight': 8.92859519259278, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 119, 'min_split_loss': 1.157350854726553, 'max_bin': 182}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:02,929] Trial 398 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.046769612636305795, 'n_estimators': 234, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.8715074757900673, 'colsample_bytree': 0.43091738509329247, 'colsample_bylevel': 0.7511850838031691, 'colsample_bynode': 0.5104507384702914, 'gamma': 0.32085082359026373, 'reg_alpha': 0.2181031335904977, 'reg_lambda': 0.6685852421966291, 'scale_pos_weight': 9.883055528682524, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 192, 'min_split_loss': 1.3463710741305153, 'max_bin': 164}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:03,229] Trial 399 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.05117832801726519, 'n_estimators': 188, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.8883410442474868, 'colsample_bytree': 0.48337174973513214, 'colsample_bylevel': 0.8019602389347407, 'colsample_bynode': 0.6402839945156283, 'gamma': 0.16448930425746006, 'reg_alpha': 0.6507045821146933, 'reg_lambda': 9.198596403114442, 'scale_pos_weight': 9.368475920611113, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 175, 'min_split_loss': 1.7275589037598122, 'max_bin': 201}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:03,580] Trial 400 finished with value: 0.05655405405405406 and parameters: {'max_depth': 7, 'learning_rate': 0.00603407147025511, 'n_estimators': 221, 'min_child_weight': 8, 'max_delta_step': 10, 'subsample': 0.8589653024784997, 'colsample_bytree': 0.4966795040518225, 'colsample_bylevel': 0.7921951238303286, 'colsample_bynode': 0.5553535284153679, 'gamma': 0.0016172955419629376, 'reg_alpha': 1.3459495514474478, 'reg_lambda': 0.3223794849635418, 'scale_pos_weight': 8.511529943295006, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 109, 'min_split_loss': 1.4458795840197345, 'max_bin': 159}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:03,909] Trial 401 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.06430488147722305, 'n_estimators': 180, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.8979515001737266, 'colsample_bytree': 0.45189294021981885, 'colsample_bylevel': 0.7715410118849696, 'colsample_bynode': 0.6019309107781905, 'gamma': 0.47871575088420715, 'reg_alpha': 9.018581459865297, 'reg_lambda': 8.31040594023156, 'scale_pos_weight': 9.611058984373052, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 185, 'min_split_loss': 1.25664201423709, 'max_bin': 177}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:04,352] Trial 402 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.07163496449402725, 'n_estimators': 203, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9170741632051653, 'colsample_bytree': 0.46786898597594695, 'colsample_bylevel': 0.8188263997979662, 'colsample_bynode': 0.5670394174495873, 'gamma': 0.23962163510199647, 'reg_alpha': 7.84524293945171, 'reg_lambda': 8.656030584433978, 'scale_pos_weight': 11.290252834936961, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 131, 'min_split_loss': 1.5296540875374132, 'max_bin': 169}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:04,677] Trial 403 finished with value: 0.5155135135135135 and parameters: {'max_depth': 8, 'learning_rate': 0.07960135784131069, 'n_estimators': 214, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.8772377564127581, 'colsample_bytree': 0.5080760818469339, 'colsample_bylevel': 0.834714586592071, 'colsample_bynode': 0.6179588471226938, 'gamma': 1.8282904149893497, 'reg_alpha': 1.8573743257552002, 'reg_lambda': 8.007373498070685, 'scale_pos_weight': 8.921723525185973, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 192, 'min_split_loss': 1.3560672990642935, 'max_bin': 190}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:04,938] Trial 404 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.05710469960370417, 'n_estimators': 231, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9080919627681316, 'colsample_bytree': 0.4790672594776294, 'colsample_bylevel': 0.8068486430070433, 'colsample_bynode': 0.5827456786031522, 'gamma': 0.11434866269696123, 'reg_alpha': 0.8911167514522571, 'reg_lambda': 6.654024342008964, 'scale_pos_weight': 10.208811367935056, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 158, 'min_split_loss': 1.6553510774379294, 'max_bin': 146}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:05,223] Trial 405 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.060954688598381004, 'n_estimators': 196, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9270218556590497, 'colsample_bytree': 0.42205988139125694, 'colsample_bylevel': 0.7593607585503126, 'colsample_bynode': 0.6083694541934082, 'gamma': 0.3183548566768064, 'reg_alpha': 8.52879353773213, 'reg_lambda': 7.770980861321776, 'scale_pos_weight': 9.378118479139935, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 93, 'min_split_loss': 1.0553697469064227, 'max_bin': 157}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:05,480] Trial 406 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.04216320485988695, 'n_estimators': 186, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.8882531239292254, 'colsample_bytree': 0.49275500748899637, 'colsample_bylevel': 0.7817193109233359, 'colsample_bynode': 0.6310748108070158, 'gamma': 0.0012594811306334691, 'reg_alpha': 7.669489487268638, 'reg_lambda': 0.016949702486467544, 'scale_pos_weight': 9.882885502640182, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 179, 'min_split_loss': 1.6033356718564653, 'max_bin': 179}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:05,718] Trial 407 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.06580016001382565, 'n_estimators': 171, 'min_child_weight': 7, 'max_delta_step': 7, 'subsample': 0.904261298329644, 'colsample_bytree': 0.4364769030244109, 'colsample_bylevel': 0.8004687394223117, 'colsample_bynode': 0.5943061466388195, 'gamma': 0.16661294770958593, 'reg_alpha': 0.4325960970914833, 'reg_lambda': 7.489137211824456, 'scale_pos_weight': 8.530429998532583, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 8, 'min_split_loss': 1.200367080232848, 'max_bin': 360}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:05,991] Trial 408 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.07384982967411206, 'n_estimators': 207, 'min_child_weight': 7, 'max_delta_step': 10, 'subsample': 0.9171327614781364, 'colsample_bytree': 0.4752726013833405, 'colsample_bylevel': 0.8545413767455138, 'colsample_bynode': 0.5692071649232846, 'gamma': 4.608401508722158, 'reg_alpha': 8.030207871799044, 'reg_lambda': 8.182014771252817, 'scale_pos_weight': 9.134795852426885, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 115, 'min_split_loss': 1.454924142583756, 'max_bin': 166}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:06,299] Trial 409 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.05465408193510966, 'n_estimators': 225, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.9338631120874767, 'colsample_bytree': 0.45955211766510506, 'colsample_bylevel': 0.7877812638494792, 'colsample_bynode': 0.584910944449691, 'gamma': 0.10148390434053287, 'reg_alpha': 0.21122879871059838, 'reg_lambda': 1.3695987393349256, 'scale_pos_weight': 10.786289350053265, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 186, 'min_split_loss': 0.7139869484226028, 'max_bin': 186}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:06,612] Trial 410 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.04935424742821799, 'n_estimators': 238, 'min_child_weight': 7, 'max_delta_step': 8, 'subsample': 0.8991164287928931, 'colsample_bytree': 0.5056884678282368, 'colsample_bylevel': 0.8753083858612224, 'colsample_bynode': 0.6149649217917471, 'gamma': 0.38746423093948157, 'reg_alpha': 0.7022443673728404, 'reg_lambda': 9.41885460031326, 'scale_pos_weight': 8.830496488831448, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 123, 'min_split_loss': 1.7535732672964714, 'max_bin': 173}. Best is trial 314 with value: 0.7048165238409141.
[I 2026-02-02 21:58:07,151] Trial 411 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.07985216694686592, 'n_estimators': 193, 'min_child_weight': 8, 'max_delta_step': 10, 'subsample': 0.8821128708015733, 'colsample_bytree': 0.4909048140069346, 'colsample_bylevel': 0.7705116805393438, 'colsample_bynode': 0.5513028929527392, 'gamma': 0.23050588883381476, 'reg_alpha': 1.2062570707105296, 'reg_lambda': 8.58507278400737, 'scale_pos_weight': 9.62101942480605, 'tree_method': 'approx', 'grow_policy': 'depthwise', 'max_leaves': 165, 'min_split_loss': 1.2988295492933832, 'max_bin': 197}. Best is trial 314 with value: 0.7048165238409141.

In [62]:
# grid_xgb.fit(X_train_retained, y_train)

In [63]:
# best_params_xgb = grid_xgb.best_params_

In [64]:
best_params_xgb = study_xgb.best_params

In [65]:
print(best_params_xgb)

{'max_depth': 8, 'learning_rate': 0.05455471168883755, 'n_estimators': 186, 'min_child_weight': 7, 'max_delta_step': 9, 'subsample': 0.9150538744186808, 'colsample_bytree': 0.4776895536294967, 'colsample_bylevel': 0.8074122734272388, 'colsample_bynode': 0.5731967866429041, 'gamma': 0.17409349437318175, 'reg_alpha': 0.017374679636583235, 'reg_lambda': 7.834188155939701, 'scale_pos_weight': 10.611449136206812, 'tree_method': 'hist', 'grow_policy': 'depthwise', 'max_leaves': 105, 'min_split_loss': 1.4238466980269138, 'max_bin': 170}

In [66]:
final_classifier = xgb.XGBClassifier(**best_params_xgb, random_state=42, eval_metric='logloss')

In [67]:
final_classifier.fit(X_train_retained, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=0.8074122734272388,
              colsample_bynode=0.5731967866429041,
              colsample_bytree=0.4776895536294967, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=0.17409349437318175, grow_policy='depthwise',
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05455471168883755, max_bin=170,
              max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=9,
              max_depth=8, max_leaves=105, min_child_weight=7,
              min_split_loss=1.4238466980269138, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=186,
              n_jobs=None, ...)

In [68]:
y_pred_val = final_classifier.predict(X_val_retained)

In [69]:
y_proba_val = final_classifier.predict_proba(X_val_retained)[:, 1]

In [70]:
print(confusion_matrix(y_val, y_pred_val))

[[632  97]
 [ 11  26]]

In [71]:
print(accuracy_score(y_val, y_pred_val))

0.8590078328981723

In [72]:
print(precision_score(y_val, y_pred_val))

0.21138211382113822

In [73]:
print(recall_score(y_val, y_pred_val))

0.7027027027027027

In [74]:
print(fbeta_score(y_val, y_pred_val, beta=2))

0.4797047970479705

### Threshold tuning

In [75]:
best_threshold = 0.5

In [76]:
best_precision_score = 0

In [77]:
best_recall_score = 0

In [78]:
best_f2_score = 0

In [79]:
for threshold in np.arange(0.1, 0.95, 0.05):
    y_pred_val_threshold = (y_proba_val >= threshold).astype(int)
    recall = recall_score(y_val, y_pred_val_threshold)
    precision = precision_score(y_val, y_pred_val_threshold)
    f2_score = fbeta_score(y_val, y_pred_val_threshold, beta=2)
    
    print(f'Threshold {threshold} has F2 score {f2_score}')
    
    if precision >= 0.15:
        current_recall_score = recall
        if current_recall_score > best_recall_score:
            best_recall_score = current_recall_score
            best_precision_score = precision
            best_threshold = threshold
        elif current_recall_score == best_recall_score and precision > best_precision_score:
            best_precision_score = precision
            best_threshold = threshold
        
        # current_f2_score = f2_score
        # if current_f2_score > best_f2_score:
        #     best_f2_score = current_f2_score
        #     best_threshold = threshold

Threshold 0.1 has F2 score 0.33081285444234404
Threshold 0.15000000000000002 has F2 score 0.3340080971659919
Threshold 0.20000000000000004 has F2 score 0.35181236673773986
Threshold 0.25000000000000006 has F2 score 0.36666666666666664
Threshold 0.30000000000000004 has F2 score 0.37349397590361444
Threshold 0.3500000000000001 has F2 score 0.4068241469816273
Threshold 0.40000000000000013 has F2 score 0.42028985507246375
Threshold 0.45000000000000007 has F2 score 0.4368932038834951
Threshold 0.5000000000000001 has F2 score 0.4797047970479705
Threshold 0.5500000000000002 has F2 score 0.371900826446281
Threshold 0.6000000000000002 has F2 score 0.365296803652968
Threshold 0.6500000000000001 has F2 score 0.28350515463917525
Threshold 0.7000000000000002 has F2 score 0.25
Threshold 0.7500000000000002 has F2 score 0.12269938650306748
Threshold 0.8000000000000002 has F2 score 0.06578947368421052
Threshold 0.8500000000000002 has F2 score 0.03333333333333333
Threshold 0.9000000000000002 has F2 score 0.0

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [80]:
print(best_threshold)

0.45000000000000007

In [81]:
print(best_f2_score)

0

### Retrain on training + validation set

In [82]:
X_train_full = pd.concat([X_train_retained, X_val_retained], axis=0, ignore_index=True)
y_train_full = pd.concat([y_train, y_val], axis=0, ignore_index=True)

In [83]:
final_classifier.fit(X_train_full, y_train_full)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=0.8074122734272388,
              colsample_bynode=0.5731967866429041,
              colsample_bytree=0.4776895536294967, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='logloss', feature_types=None, feature_weights=None,
              gamma=0.17409349437318175, grow_policy='depthwise',
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05455471168883755, max_bin=170,
              max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=9,
              max_depth=8, max_leaves=105, min_child_weight=7,
              min_split_loss=1.4238466980269138, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=186,
              n_jobs=None, ...)

### Evaluate on test set

In [84]:
X_test_retained = X_test[retained_columns]

In [85]:
y_pred_test = final_classifier.predict(X_test_retained)

In [86]:
y_proba_test = final_classifier.predict_proba(X_test_retained)[:, 1]

In [87]:
print(confusion_matrix(y_test, y_pred_test))

[[621 108]
 [ 11  27]]

In [88]:
print(accuracy_score(y_test, y_pred_test))

0.8448500651890483

In [89]:
print(precision_score(y_test, y_pred_test))

0.2

In [90]:
print(recall_score(y_test, y_pred_test))

0.7105263157894737

In [91]:
print(fbeta_score(y_test, y_pred_test, beta=2))

0.47038327526132406

### Test with best threshold 0.55

In [92]:
y_pred_test_threshold = (y_proba_test >= best_threshold).astype(int)

In [93]:
print(confusion_matrix(y_test, y_pred_test_threshold))

[[595 134]
 [ 10  28]]

In [94]:
print(accuracy_score(y_test, y_pred_test_threshold))

0.8122555410691004

In [95]:
print(precision_score(y_test, y_pred_test_threshold))

0.1728395061728395

In [96]:
print(recall_score(y_test, y_pred_test_threshold))

0.7368421052631579

In [97]:
print(fbeta_score(y_test, y_pred_test_threshold, beta=2))

0.445859872611465